-- ============================================
-- DEPRECATED LEGACY SCRIPT
-- 不要再运行这个历史爱发电 / payment orders 汇总脚本
-- ============================================
--
-- 这个文件曾经同时承载：
-- - payment_orders / payment_events / payment_checkout_sessions 表结构
-- - afdian_orders 兼容层
-- - fn_ensure_redemption_code_for_payment_order
-- - fn_apply_payment_order_review
-- - fn_process_afdian_payment
-- - fn_finalize_afdian_custom_payment
-- - 相关 RLS / grants / 查询函数
--
-- 现在这些能力已经由更晚的 hardened migrations 分拆接管。
-- 如果再手工执行这份历史整包脚本，可能把旧支付入口、旧授权和旧兼容逻辑重新刷回数据库。
--
-- 请改用以下文件：
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_add_payment_ops_hardening.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_harden_payment_redemption_entrypoints.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_add_custom_recharge_quote_resolution.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/verify_payment_redemption_hardening.sql
--
-- 当前应以 supabase/migrations 中的版本为准，不要再从这个文件执行任何 SQL。
