-- Deprecated stub.
--
-- This root helper previously redefined get_overview_stats_with_trend() with
-- old single-site login-based semantics.
--
-- The active trend-aware overview SQL now lives in:
-- - supabase/analytics_site_filter.sql
--
-- Relevant hardening migrations:
-- - supabase/migrations/20260405_admin_analytics_explicit_range_dates.sql
-- - supabase/migrations/20260405_admin_analytics_site_attribution_alignment.sql
-- - supabase/migrations/20260405_admin_analytics_business_active_alignment.sql
--
-- Do not add executable analytics trend definitions back into this file.
