-- Deprecated stub.
--
-- This root helper previously shipped executable advanced analytics SQL with
-- legacy proxy funnel, login-based retention, and single-site assumptions.
--
-- The active advanced analytics SQL now lives in:
-- - supabase/analytics_advanced_site_filter.sql
-- - supabase/analytics_site_filter.sql
--
-- Relevant cleanup migrations:
-- - supabase/migrations/20260405_admin_analytics_remove_legacy_conversion_funnel.sql
-- - supabase/migrations/20260405_admin_analytics_retention_remove_login_fallback.sql
-- - supabase/migrations/20260405_admin_analytics_heatmap_remove_login_fallback.sql
--
-- Do not add executable analytics funnel, retention, or geo definitions back
-- into this file.
