-- Deprecated stub.
--
-- This root helper previously shipped executable single-site analytics RPCs
-- such as get_overview_stats(), get_user_trend(), get_content_trend(),
-- get_revenue_trend(), get_channel_breakdown(), and get_activity_heatmap().
--
-- The active admin analytics SQL now lives in:
-- - supabase/analytics_site_filter.sql
-- - supabase/analytics_advanced_site_filter.sql
--
-- Recent hardening and cleanup migrations for the active definitions:
-- - supabase/migrations/20260405_admin_analytics_explicit_range_dates.sql
-- - supabase/migrations/20260405_admin_analytics_site_attribution_alignment.sql
-- - supabase/migrations/20260405_admin_analytics_business_active_alignment.sql
-- - supabase/migrations/20260405_admin_analytics_heatmap_remove_login_fallback.sql
--
-- Do not add executable analytics RPC definitions back into this file.
