-- ============================================
-- DEPRECATED LEGACY SCRIPT
-- 不要再运行这个历史双站点 RPC 汇总脚本
-- ============================================
--
-- 这个文件曾经批量定义过：
-- - fn_purchase_shop_item
-- - fn_get_user_balance
-- - fn_recharge_points
-- - fn_add_points
-- - fn_deduct_points
-- - fn_redeem_code
-- 等一整套双站点函数。
--
-- 在当前系统里，这些能力已经被更晚的 hardened migrations 分拆接管。
-- 如果今天再手工执行这份历史汇总脚本，可能把旧签名、旧授权和旧业务逻辑重新刷回数据库。
--
-- 请改用以下文件：
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_harden_shop_purchase_identity.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_harden_points_mutation_rpcs.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_harden_payment_redemption_entrypoints.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_retire_legacy_redemption_overloads.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/verify_payment_redemption_hardening.sql
--
-- 当前应以 supabase/migrations 中的版本为准，不要再从这个文件执行任何 SQL。
