-- ============================================
-- DEPRECATED LEGACY SCRIPT
-- 不要再运行这个历史兑换码 site 修补脚本
-- ============================================
--
-- 这个文件曾经做过：
-- - 给 fn_generate_codes 增加 p_site
-- - 给 fn_generate_custom_codes 增加 p_site
-- - 补 redemption_batches / redemption_codes 的 site 列
--
-- 当前这些逻辑都已经由更晚的 hardened migrations 接管。
-- 如果今天再手工执行这份旧脚本，可能把历史版本的发码入口重新刷回数据库。
--
-- 请改用以下文件：
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/migrations/20260322_harden_payment_redemption_entrypoints.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/fn_generate_custom_codes.sql
-- - /Volumes/chao/AI/xianyu_profit_calculator/supabase/verify_payment_redemption_hardening.sql
--
-- 当前应以 supabase/migrations 中的版本为准，不要再从这个文件执行任何 SQL。
