-- Clean up previous attempts (if any)
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user;
drop trigger if exists on_prompts_fts_update on public.prompts;
drop function if exists public.handle_prompts_fts;
drop table if exists public.guestbook;
drop table if exists public.prompts;
drop table if exists public.profiles;

-- 1. PROFILES Table
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  username text unique,
  avatar_url text,
  updated_at timestamp with time zone,
  
  primary key (id),
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Trigger: Automatically handle new user signup
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. GUESTBOOK Table
create table public.guestbook (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  message text not null,
  reply jsonb, 
  ua text, 
  location text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.guestbook enable row level security;

create policy "Guestbook is viewable by everyone."
  on guestbook for select
  using ( true );

create policy "Authenticated users can post messages."
  on guestbook for insert
  with check ( auth.uid() = user_id );

-- 3. PROMPTS Table
create table public.prompts (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  prompt text, 
  tags text[],
  images text[],
  author_name text,
  author_avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  fts tsvector -- We will update this via trigger
);

-- Index for fast search
create index prompts_fts_idx on public.prompts using gin (fts);

alter table public.prompts enable row level security;

create policy "Prompts are viewable by everyone."
  on prompts for select
  using ( true );

create policy "Service role can manage prompts."
  on prompts for all
  using ( auth.role() = 'service_role' );

-- Function to calculate FTS
create function public.handle_prompts_fts()
returns trigger as $$
begin
  new.fts :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.description, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.prompt, '')), 'C') ||
    setweight(to_tsvector('simple', array_to_string(new.tags, ' ')), 'B');
  return new;
end;
$$ language plpgsql;

-- Trigger to update FTS on insert/update
create trigger on_prompts_fts_update
  before insert or update on public.prompts
  for each row execute procedure public.handle_prompts_fts();
