-- ============================================
-- DEPRECATED LEGACY SCRIPT
-- 不要再运行这个历史单站点积分脚本
-- ============================================
--
-- 这个文件曾经定义过旧版：
-- - fn_add_points(UUID, INT, TEXT, TEXT)
-- - fn_deduct_points(INT, TEXT, TEXT)
--
-- 在当前双站点 / 支付安全收口后的系统里，
-- 直接重放这些历史定义会把 points RPC 回退到旧的单站点实现，
-- 可能绕开现在的 site 绑定和 hardened migrations。
--
-- 请改用以下文件：
-- - supabase/migrations/20260322_harden_points_mutation_rpcs.sql
-- - supabase/fn_recharge_points.sql
-- - supabase/fn_get_user_balance.sql
-- - supabase/migrations/20260322_retire_legacy_redemption_overloads.sql
--
-- 当前应以 supabase/migrations 中的版本为准，不要再从这个文件执行任何 SQL。
