-- ============================================
-- DEPRECATED LEGACY SCRIPT
-- 不要再运行这个历史兑换码脚本
-- ============================================
--
-- 这个文件曾经定义过旧版：
-- - fn_redeem_code(VARCHAR)
-- - fn_dispatch_code(VARCHAR, VARCHAR)
-- - fn_revoke_code(VARCHAR, VARCHAR)
-- - fn_check_code_status(VARCHAR)
--
-- 其中旧版 fn_redeem_code(VARCHAR) 会绕回单站点积分入口，
-- 重新暴露已经下线的 legacy overload 风险。
--
-- 请改用以下文件：
-- - supabase/migrations/20260322_harden_payment_redemption_entrypoints.sql
-- - supabase/migrations/20260322_retire_legacy_redemption_overloads.sql
-- - supabase/fn_redeem_code_v2.sql
-- - supabase/verify_payment_redemption_hardening.sql
--
-- 当前应以 supabase/migrations 中的版本为准，不要再从这个文件执行任何 SQL。
