const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const adminHtml = fs.readFileSync(path.join(root, 'admin-studio.html'), 'utf8');
const adminJs = fs.readFileSync(path.join(root, 'admin-studio.js'), 'utf8');
const adminConfigJs = fs.readFileSync(path.join(root, 'admin-config.js'), 'utf8');
const adminBootstrapJs = fs.readFileSync(path.join(root, 'js/admin-studio-bootstrap.js'), 'utf8');
const adminCss = fs.readFileSync(path.join(root, 'css/admin-studio-page.css'), 'utf8');
const adminApi = fs.readFileSync(path.join(root, 'api/admin.js'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

test('admin studio exposes AI creation as a dedicated module with segmented management panels', () => {
    assert.match(adminHtml, /data-module="ai-creation"[\s\S]*<span>AI 创作<\/span>/);
    assert.match(adminHtml, /id="module-ai-creation"/);
    assert.match(adminHtml, /id="aiCreationPanelSource"/);
    assert.match(adminHtml, /id="aiCreationPanelMount"/);
    assert.match(adminHtml, /id="aiCreationTabsNav"/);
    assert.match(adminHtml, /class="ai-creation-toolbar"/);
    assert.match(adminHtml, /class="ai-creation-actions"/);
    assert.doesNotMatch(adminHtml, /AI 创作工作台/);
    assert.doesNotMatch(adminHtml, /class="settings-section ai-image-admin-hero"/);
    assert.doesNotMatch(adminHtml, /data-settings-view="ai-image"/);
    assert.doesNotMatch(adminHtml, /id="settings-view-ai-image"/);
    ['overview', 'models', 'user-api', 'pricing', 'guardrails', 'storage', 'agents'].forEach((viewName) => {
        assert.match(adminHtml, new RegExp(`data-ai-creation-view="${viewName}"`));
    });
    [
        'data-ai-creation-panel="overview"',
        'data-ai-creation-panel="models"',
        'data-ai-creation-panel="user-api"',
        'data-ai-creation-panel="pricing"',
        'data-ai-creation-panel="guardrails"',
        'data-ai-creation-panel="storage"',
        'data-ai-creation-panel="agents"'
    ].forEach((marker) => {
        assert.equal(adminHtml.includes(marker), true, `admin-studio.html should contain ${marker}`);
    });
    assert.match(adminHtml, /id="aiImageRuntimeStatus"/);
    assert.match(adminHtml, /data-ai-image-runtime="queue"/);
    assert.match(adminHtml, /data-ai-image-runtime="failure"/);
    assert.match(adminHtml, /id="aiImageModelVendorDropdown"[\s\S]*<input type="hidden" id="aiImageModelVendorInput"/);
    assert.match(adminHtml, /data-value="custom">自定义/);
    assert.match(adminHtml, /id="aiImageModelVendorLabelInput"[\s\S]*placeholder="输入厂商名称，如 OpenRouter \/ 火山方舟"/);
    assert.match(adminHtml, /id="aiImageModelProtocolDropdown"[\s\S]*<input type="hidden" id="aiImageModelProtocolInput"/);
    assert.match(adminHtml, /id="aiImageModelBaseUrlInput"/);
    assert.match(adminHtml, /id="aiImageModelNameInput"/);
    assert.doesNotMatch(adminHtml, /id="aiImageVisibleModelPicker"/);
    assert.match(adminHtml, /id="aiImageDetectedImageModelsInput"/);
    assert.match(adminHtml, /id="aiImageDetectedChatModelsInput"/);
    assert.match(adminHtml, /id="aiImageVideoModelAliasesInput"/);
    assert.match(adminHtml, /id="aiImageDetectedVideoModelsInput"/);
    assert.match(adminHtml, /id="aiImageDetectedUnknownModelsInput"/);
    assert.match(adminHtml, /id="aiImageVisionModelsInput"/);
    assert.match(adminJs, /前台可见模型/);
    assert.match(adminJs, /前台展示名称（默认同模型 ID）/);
    assert.match(adminJs, /data-admin-input-action="settings-edit-ai-image-model-display-name"/);
    assert.match(adminJs, /function updateAiImageModelDisplayName\(model = '', value = '', providerId = ''\)/);
    assert.match(adminCss, /\.ai-image-admin-model-display-name/);
    assert.match(adminHtml, /保存前台可见/);
    assert.doesNotMatch(adminHtml, /保存前台可见模型/);
    assert.match(adminHtml, /data-admin-action="settings-create-ai-image-model-provider"/);
    assert.match(adminHtml, /id="aiImageChatModelAliasesInput"/);
    assert.match(adminHtml, /data-admin-action="settings-prompt-ai-image-model-key"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-model-config"/);
    assert.doesNotMatch(adminHtml, /data-admin-action="settings-test-ai-image-model-config"/);
    assert.doesNotMatch(adminHtml, /data-admin-action="settings-discover-ai-image-model-config"/);
    assert.doesNotMatch(adminHtml, /id="aiImageModelProbeStatus"/);
    assert.doesNotMatch(adminHtml, /id="aiImageModelProbeGrid"/);
    assert.match(adminHtml, /class="ai-image-admin-model-workspace"/);
    assert.match(adminHtml, /class="ai-image-admin-model-sidebar"/);
    assert.match(adminHtml, /class="ai-image-admin-model-detail"/);
    assert.match(adminHtml, /class="[^"]*ai-image-admin-model-provider-list[^"]*" id="aiImageModelProviderList"/);
    assert.match(adminHtml, /id="aiImageModelProviderDetail"/);
    assert.match(adminHtml, /id="aiImageModelProbeButton"/);
    assert.match(adminHtml, /id="aiImageFailedModelProbeButton"/);
    assert.match(adminHtml, /id="aiImageModelDiscoveryButton"/);
    assert.match(adminHtml, /id="aiImageModelDeleteButton"/);
    assert.match(adminHtml, /id="aiImageModelDeleteButton"[\s\S]*data-admin-action="settings-save-ai-image-model-config"/);
    assert.match(adminHtml, /id="aiImageApiBaseUrlInput"/);
    assert.match(adminHtml, /id="aiImageApiBaseList"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-api-base"/);
    assert.match(adminHtml, /id="aiImageGuardSubmitUserInput"/);
    assert.match(adminHtml, /id="aiImageGuardActiveInput"/);
    assert.match(adminHtml, /class="ai-image-admin-info"[\s\S]*data-ai-image-tooltip="单个登录用户每分钟最多可提交的 AI 图片任务数。"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-guardrails"/);
    assert.match(adminHtml, /id="aiImageStorageUsage"/);
    assert.match(adminHtml, /id="aiImageStoragePreviewRetentionInput"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-storage-policy"/);
    assert.match(adminHtml, /class="ai-image-admin-pricing-workspace"/);
    assert.match(adminHtml, /class="ai-image-admin-pricing-sidebar"/);
    assert.match(adminHtml, /class="ai-image-admin-pricing-editor"/);
    assert.match(adminHtml, /class="[^"]*ai-image-admin-pricing-list[^"]*" id="aiImagePricingList"/);
    assert.match(adminHtml, /id="aiImagePricingStrategyDropdown"[\s\S]*<input type="hidden" id="aiImagePricingStrategyInput" value="per_request"/);
    assert.match(adminHtml, /id="aiImagePricingProviderDropdown"[\s\S]*<input type="hidden" id="aiImagePricingProviderInput"/);
    assert.match(adminHtml, /id="aiImagePricingModelDropdown"[\s\S]*<input type="hidden" id="aiImagePricingModelInput"/);
    const pricingModeDropdown = adminHtml.match(/id="aiImagePricingModeDropdown"[\s\S]*?<\/label>/)?.[0] || '';
    assert.match(pricingModeDropdown, /data-value="text">图片生成/);
    assert.match(pricingModeDropdown, /data-value="video">视频生成/);
    assert.match(pricingModeDropdown, /data-value="chat">文本对话/);
    assert.doesNotMatch(pricingModeDropdown, /图片拓展|反推提示词|智能体/);
    assert.match(adminJs, /AI_IMAGE_PRICING_MODE_ALIASES/);
    assert.match(adminJs, /image:\s*'text'/);
    assert.match(adminJs, /agent:\s*'text'/);
    assert.match(adminJs, /reverse:\s*'chat'/);
    assert.match(adminJs, /label:\s*'应用全部'/);
    assert.match(adminJs, /hint:\s*providerLabel \|\| '当前上游'/);
    assert.match(adminJs, /ai-image-admin-pricing-group__rules/);
    assert.match(adminJs, /function syncAiImageModelVendorCustomField/);
    assert.match(adminJs, /vendorLabel,\s*\n\s*vendor_label:\s*vendorLabel/);
    assert.match(adminJs, /请输入自定义模型厂商名称/);
    assert.match(adminHtml, /data-ai-pricing-field="resolution"/);
    assert.match(adminHtml, /data-ai-pricing-field="quantity"/);
    assert.match(adminHtml, /data-ai-pricing-field="imageOutput"/);
    assert.match(adminHtml, /Sub2API 实际扣费/);
    assert.match(adminHtml, /按 Sub2API 使用记录里的 actual_cost 扣费/);
    assert.match(adminHtml, /id="aiImagePricingInputRateInput"/);
    assert.match(adminHtml, /id="aiImagePricingOutputRateInput"/);
    assert.match(adminHtml, /id="aiImagePricingCacheWriteRateInput"/);
    assert.match(adminHtml, /id="aiImagePricingCacheReadRateInput"/);
    assert.match(adminHtml, /id="aiImagePricingImageOutputRateInput"/);
    assert.match(adminHtml, /id="aiImagePricingEstimateCacheWriteTokensInput"/);
    assert.match(adminHtml, /data-ai-pricing-token-manual hidden/);
    assert.match(adminCss, /data-ai-pricing-token-manual\]\[hidden\][\s\S]*display:\s*none !important/);
    assert.match(adminHtml, /id="aiImageAgentList"/);
    assert.match(adminHtml, /data-admin-action="settings-run-ai-image-worker-once"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-pricing"/);
    assert.match(adminHtml, /data-admin-action="settings-new-ai-image-pricing"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-agent"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImagePricingModeInput"/);
    assert.doesNotMatch(adminHtml, /<input class="config-input" id="aiImagePricingModelInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImagePricingResolutionInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImagePricingRatioInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImageApiBaseSiteInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImageModelVendorInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImageModelProtocolInput"/);
    assert.doesNotMatch(adminHtml, /id="aiImageModelGroupDropdown"/);
    assert.doesNotMatch(adminHtml, />默认模型</);
    assert.doesNotMatch(adminHtml, />模型组\s*</);
    assert.doesNotMatch(adminHtml, /生图模型 \/ 别名/);
    assert.match(adminHtml, /id="aiImagePricingModeDropdown"[\s\S]*<input type="hidden" id="aiImagePricingModeInput"/);
    assert.match(adminHtml, /id="aiImageApiBaseSiteDropdown"[\s\S]*<input type="hidden" id="aiImageApiBaseSiteInput"/);
    assert.match(adminJs, /function isAiImagePricingImageOutputTokenMode/);
    assert.match(adminJs, /manualTokenFields\.forEach/);
    assert.match(adminJs, /const isSub2ApiActualCost = strategy === 'token_sub2api'/);
    assert.match(adminJs, /provider_id:\s*providerId/);
    assert.match(adminJs, /!draft\.metadata\?\.provider_id \|\| draft\.metadata\.provider_id === '\*'/);
    assert.match(adminJs, /请先选择模型或应用全部/);
    assert.doesNotMatch(adminJs, /draft\.model === '\*'/);
});

test('admin studio loads and mutates AI image config through admin scoped APIs', () => {
    assert.match(adminJs, /route:\s*'ai-image\/config'/);
    assert.match(adminJs, /route=ai-image\/model-config/);
    assert.match(adminJs, /fetchAiImageAdminConfig/);
    assert.match(adminJs, /fetchAiImageModelConfig/);
    assert.match(adminJs, /promptForAiImageModelKey/);
    assert.match(adminJs, /saveAiImageModelConfig/);
    assert.match(adminJs, /testAiImageModelConfig/);
    assert.match(adminJs, /discoverAiImageModelConfig/);
    assert.match(adminJs, /createAiImageModelProviderDraft/);
    assert.match(adminJs, /toggleAiImageVisibleModel/);
    assert.doesNotMatch(adminJs, /renderAiImageVisibleModelPicker/);
    assert.match(adminJs, /renderAiImageProviderVisibleModelSection/);
    assert.match(adminJs, /settings-toggle-ai-image-provider-models/);
    assert.match(adminJs, /toggleAiImageModelProviderModels/);
    assert.match(adminJs, /return selectAiImageModelProvider\(normalizedProviderId\);/);
    assert.match(adminJs, /ai-image-admin-provider-list-item/);
    assert.match(adminJs, /ai-image-admin-provider-list-loading/);
    assert.match(adminJs, /data-admin-action="settings-select-ai-image-model-provider"/);
    assert.match(adminJs, /getElementById\('aiImageModelProviderDetail'\)/);
    assert.match(adminJs, /button\.dataset\.providerId = provider\.providerId \|\| ''/);
    assert.doesNotMatch(adminJs, /data-admin-action="settings-toggle-ai-image-provider-models"[\s\S]*aria-expanded/);
    assert.doesNotMatch(adminJs, /ai-image-admin-provider-list-item__(?:meta|foot)/);
    assert.doesNotMatch(adminJs, /ai-image-admin-model-detail-summary/);
    assert.match(adminJs, /modelProbes: Object\.create\(null\)/);
    assert.match(adminJs, /function setAiImageModelProbe\(probe = null\)/);
    assert.match(adminJs, /adminAiImageState\.modelProbes\[providerId\] = normalizedProbe/);
    assert.match(adminJs, /function renderAiImageProviderProbePanel\(provider = \{\}\)/);
    assert.match(adminJs, /data-provider-probe="\$\{escapeHtml\(provider\.providerId \|\| ''\)\}"/);
    assert.match(adminJs, /settings-discover-ai-image-model-provider/);
    assert.doesNotMatch(adminJs, /settings-discover-ai-image-model-config/);
    assert.match(adminJs, /settings-toggle-ai-image-visible-model/);
    assert.match(adminJs, /action:\s*'discover-models'/);
    assert.match(adminJs, /detectedImageModels: nextImageModels/);
    assert.match(adminJs, /detectedChatModels: nextChatModels/);
    assert.match(adminJs, /detectedVideoModels: nextVideoModels/);
    assert.match(adminJs, /生成视频/);
    assert.match(adminJs, /action:\s*'test-model'/);
    assert.match(adminJs, /matrix:\s*true/);
    assert.match(adminJs, /function buildAiImageModelProbeTargets\(draft = \{\}\)/);
    assert.match(adminJs, /chatModels\.flatMap\(\(model\) => \['chat', 'vision'\]/);
    assert.match(adminJs, /function runAiImageModelProbeTargets\(/);
    assert.match(adminJs, /probeTargets:\s*\[target\]/);
    assert.match(adminJs, /timeoutMs:\s*isFirstTarget && discoverModels \? 35000 : 45000/);
    assert.match(adminJs, /createUnverifiedAiImageModelProbeCheck\(target, error\)/);
    assert.match(adminJs, /progressCompleted:\s*completed/);
    assert.match(adminJs, /const nextVisionModels = mergeAiImageModelCandidates\(/);
    assert.doesNotMatch(adminJs, /mergeAiImageModelCandidates\(\s*draft\.visionModels,\s*draft\.vision_models,\s*check\.visionModels/);
    assert.match(adminJs, /setAiImageModelsInputValue\(document\.getElementById\('aiImageVisionModelsInput'\)/);
    assert.match(adminJs, /模型自检请求失败，未返回有效检测结果/);
    assert.match(adminJs, /const resolutions = \['1k', '2k', '4k'\]/);
    assert.match(adminJs, /ai-image-admin-probe-item/);
    assert.match(adminJs, /\[item\.model \|\| '', modeLabel/);
    assert.match(adminJs, /verificationStatus === 'unverified'/);
    assert.match(adminJs, /is-warning/);
    assert.match(adminJs, /项未验证/);
    assert.match(adminJs, /ai-image-admin-probe-discovery/);
    assert.match(adminJs, /settings-apply-ai-image-discovered-model/);
    assert.match(adminJs, /settings-classify-ai-image-unknown-model/);
    assert.match(adminJs, /function applyAiImageDiscoveredModel\(model = '', group = 'unknown', providerId = ''\)/);
    assert.match(adminJs, /function classifyAiImageUnknownModel\(model = '', group = 'image', providerId = ''\)/);
    assert.match(adminJs, /removeAiImageModelCandidate\(provider\.detectedUnknownModels \|\| provider\.detected_unknown_models, normalizedModel\)/);
    assert.match(adminJs, /renderAiImageUnknownModelClassifier\(label, providerId\)/);
    assert.match(adminJs, /设为文本/);
    assert.match(adminJs, /设为生图/);
    assert.match(adminJs, /设为视频/);
    assert.match(adminJs, /function renderAiImageVisibleModelPill\(model = '', group = 'image', selectedModels = \[\], providerId = '', modelDisplayNames = \{\}\) \{[\s\S]*data-provider-id="\$\{escapeHtml\(providerId \|\| ''\)\}"/);
    assert.match(adminJs, /function renderAiImageDiscoveredModelButton\(model = '', group = 'unknown', providerId = ''\) \{[\s\S]*data-provider-id="\$\{escapeHtml\(providerId \|\| ''\)\}"/);
    assert.match(adminJs, /renderAiImageDiscoveredModelButton\(model, group\.group, provider\.providerId \|\| ''\)/);
    assert.match(adminJs, /function getAiImageProbeUpstreamText\(upstream = \{\}\)/);
    assert.match(adminJs, /通道 ID/);
    assert.match(adminJs, /请求 ID/);
    assert.match(adminJs, /function inferAiImageModelGroup\(value, imageModels = \[\], chatModels = \[\], videoModels = \[\], fallback = 'image'\)/);
    assert.match(adminJs, /function scopeAiImageModelsByGroup\(modelGroup = 'image', imageModels = \[\], chatModels = \[\], videoModels = \[\]\)/);
    assert.match(adminJs, /chatModels: group === 'image' \|\| group === 'video' \? \[\] : normalizeAiImageModelsList\(chatModels, ''\)/);
    assert.match(adminJs, /hiddenInput\.dataset\.adminDropdownDirty = '1'/);
    assert.match(adminJs, /hiddenInput\.dispatchEvent\(new Event\('change', \{ bubbles: true \}\)\)/);
    assert.match(adminJs, /inferAiImageModelGroupFromLists\(draftImageModels, draftChatModels, draftVideoModels\)/);
    assert.match(adminJs, /function buildAiImageProviderIdSuggestion\(providerId = 'default', modelGroup = 'image', existingProviders = \[\]\)/);
    assert.match(adminJs, /function ensureAiImageProviderIdForDraft\(draft = \{\}, provider = null, config = getAiImageModelConfig\(\)\)/);
    assert.match(adminJs, /deleteAiImageModelConfig/);
    assert.match(adminJs, /settings-delete-ai-image-model-config/);
    assert.match(adminJs, /window\.deleteAiImageModelConfig\?\.\(actionEl\.dataset\.providerId \|\| actionEl\.dataset\.provider_id \|\| ''\)/);
    assert.match(adminJs, /adminAiImageState\.apiBaseUrls/);
    assert.match(adminJs, /saveAiImageApiBaseUrl/);
    assert.match(adminJs, /disableAiImageApiBaseUrl/);
    assert.match(adminJs, /save-api-base-url/);
    assert.match(adminJs, /disable-api-base-url/);
    assert.match(adminJs, /adminAiImageState\.guardrails/);
    assert.match(adminJs, /DEFAULT_AI_IMAGE_GUARDRAILS/);
    assert.match(adminJs, /saveAiImageGuardrails/);
    assert.match(adminJs, /action:\s*'save-guardrails'/);
    assert.match(adminJs, /adminAiImageState\.storageUsage/);
    assert.match(adminJs, /saveAiImageStoragePolicy/);
    assert.match(adminJs, /action:\s*'save-storage-policy'/);
    assert.match(adminJs, /adminAiImageState\.runtime/);
    assert.match(adminJs, /function renderAiImageAdminPanel\(\) \{[\s\S]*initCustomDropdown\?\.\(\);[\s\S]*bindAiImageAdminTooltips\(\);/);
    assert.match(adminJs, /getAiImageRuntimeHealth/);
    assert.match(adminJs, /getAiImageRuntimeText\('queue'\)/);
    assert.match(adminJs, /postAiImageAdminConfig/);
    assert.match(adminJs, /saveAiImagePricingRule/);
    assert.match(adminJs, /selectAiImagePricingRule/);
    assert.match(adminJs, /resetAiImagePricingEditor/);
    assert.match(adminJs, /calculateAiImagePricingTokenPoints/);
    assert.match(adminJs, /billing_strategy:\s*strategy/);
    assert.match(adminJs, /cache_write_tokens:\s*normalizeAiImagePricingInt\(tokenConfig\.estimateCacheWriteTokens/);
    assert.match(adminJs, /saveAiImageAgent/);
    assert.match(adminJs, /deleteAiImagePricingRule/);
    assert.match(adminJs, /settings-delete-ai-image-pricing/);
    assert.doesNotMatch(adminJs, /<i class="fas fa-clone"><\/i> 复制新建/);
    assert.match(adminJs, /settings-test-ai-image-model-provider-full/);
    assert.match(adminHtml, /<i class="fas fa-stethoscope"><\/i> 模型自检/);
    assert.match(adminJs, /settings-test-ai-image-model-provider-failed/);
    assert.match(adminHtml, /<i class="fas fa-rotate"><\/i> 自检故障模型/);
    assert.match(adminJs, /function retryAiImageFailedModelChecks\(providerId = ''\)/);
    assert.match(adminJs, /probe\.checks\.filter\(\(item\) => !item\.ok\)/);
    assert.match(adminJs, /runAiImageModelProbeTargets\(\{[\s\S]*probeTargets,[\s\S]*discoverModels:\s*false/);
    assert.match(adminJs, /getAiImageModelProbeCheckKey\(item = \{\}\)[\s\S]*item\.model[\s\S]*item\.mode[\s\S]*item\.resolution/);
    assert.match(adminJs, /const mergedChecks = probe\.checks\.map\(\(item\) => retriedCheckMap\.get\(getAiImageModelProbeCheckKey\(item\)\) \|\| item\)/);
    assert.match(adminJs, /window\.retryAiImageFailedModelChecks = retryAiImageFailedModelChecks/);
    assert.match(adminHtml, /<i class="fas fa-magnifying-glass"><\/i> 检测上游支持模型/);
    assert.doesNotMatch(adminJs, /data-admin-action="settings-test-ai-image-model-provider"/);
    assert.doesNotMatch(adminJs, /<i class="fas fa-plug"><\/i> 连通性/);
    assert.doesNotMatch(adminJs, /打开这一行到上方编辑器/);
    assert.doesNotMatch(adminJs, /<i class="fas fa-pen"><\/i> 编辑/);
    assert.match(adminJs, /const canDelete = provider\.source === 'stored'/);
    assert.match(adminJs, /const canProbe = Boolean\(provider\.configured\)/);
    assert.match(adminJs, /deleteButton[\s\S]*删除当前上游后台安全存储配置/);
    assert.match(adminJs, /只有后台托管的上游可以在这里删除/);
    assert.match(adminJs, /const activePricing = adminAiImageState\.pricing\.filter\(\(rule\) => rule\.is_active !== false\)/);
    assert.match(adminHtml, /data-admin-action="settings-delete-ai-image-pricing"/);
    assert.match(adminJs, /window\.deleteAiImagePricingRule = deleteAiImagePricingRule/);
    assert.doesNotMatch(adminJs, /testAiImageModelProviderConnectivity/);
    assert.match(adminJs, /disableAiImagePricingRule/);
    assert.match(adminJs, /disableAiImageAgent/);
    assert.match(adminJs, /\/api\/admin\?route=ai-image\/run/);
    assert.match(adminJs, /switchAiCreationView/);
    assert.match(adminJs, /initAiCreationModule/);
    assert.match(adminJs, /window\.AdminShell\.registerModule\('ai-creation'/);
    assert.match(adminJs, /case 'switch-ai-creation-view':[\s\S]*window\.switchAiCreationView\?\.\(actionEl\.dataset\.aiCreationView\);/);
    assert.match(adminJs, /if \(normalizedViewName === 'ai-image'\) \{[\s\S]*window\.switchModule\?\.\('ai-creation'/);
    assert.match(adminApi, /aiImageModelConfigHandler/);
    assert.match(adminApi, /'ai-image\/model-config': aiImageModelConfigHandler/);
});

test('legacy AI image settings view redirects to the dedicated AI creation module', () => {
    assert.match(adminConfigJs, /const SETTINGS_VIEW_DOMAIN_MAP = Object\.freeze\(\{[\s\S]*'ai-image': \[\],[\s\S]*\}\);/);
    assert.match(adminConfigJs, /function normalizeSettingsViewName\(viewName = ''\) \{[\s\S]*SETTINGS_VIEW_DOMAIN_MAP\[normalizedView\][\s\S]*return normalizedView;[\s\S]*return 'pricing';[\s\S]*\}/);
    assert.match(adminConfigJs, /if \(viewName === 'ai-image'\) \{[\s\S]*activateModule\('ai-creation'[\s\S]*reason: 'legacy-settings-ai-image'/);
    assert.match(adminJs, /case 'switch-settings-view':[\s\S]*window\.switchSettingsView\?\.\(actionEl\.dataset\.settingsView\);[\s\S]*break;/);
    assert.match(adminJs, /if \(normalizedViewName === 'ai-image'\) \{[\s\S]*aiCreationView:[\s\S]*reason: 'legacy-ai-image-settings-view'/);
});

test('AI creation module inherits settings manage permission and bootstrap activation', () => {
    assert.match(adminBootstrapJs, /modules: \['settings', 'ai-creation', 'xianyu-fulfillment'\]/);
    assert.match(adminBootstrapJs, /'ai-creation': \{[\s\S]*label: 'AI 创作'[\s\S]*anyOf: \['settings\.manage'\]/);
    assert.match(adminBootstrapJs, /case 'ai-creation':[\s\S]*fetchAiImageAdminConfig\?\.\(\{ force: false \}\)/);
    assert.match(adminBootstrapJs, /if \(normalizedModuleId === 'ai-creation'\) \{[\s\S]*window\.initAiCreationModule\?\.\(\{\}, options\);/);
});

test('AI image real executor dispatches image, reverse, and chat modes', () => {
    const modelSource = fs.readFileSync(path.join(root, 'server/api-handlers/_ai-image-models.js'), 'utf8');
    const runHandlerSource = fs.readFileSync(path.join(root, 'server/api-handlers/admin/ai-image/run.js'), 'utf8');
    const workerSource = fs.readFileSync(path.join(root, 'scripts/ai-image-worker.js'), 'utf8');

    assert.match(modelSource, /TEXT_VISION_MODES = Object\.freeze\(new Set\(\['reverse', 'chat'\]\)\)/);
    assert.match(modelSource, /executeOpenAiCompatibleTextVision/);
    assert.match(modelSource, /chat\/completions/);
    assert.match(modelSource, /executeOpenAiCompatibleAiImageTask/);
    assert.match(runHandlerSource, /createOpenAiCompatibleImageExecutor/);
    assert.match(workerSource, /createOpenAiCompatibleImageExecutor/);
});

test('AI image admin settings keep scoped styling and worker command contract', () => {
    assert.equal(packageJson.scripts['ai-image:worker'], 'node scripts/ai-image-worker.js');
    assert.match(adminCss, /20260621_AI_IMAGE_ADMIN_SETTINGS_1/);
    assert.match(adminCss, /#module-comments \.module-content,\s*#module-ai-creation \.module-content,\s*#module-ops-alerts \.view-section > \.module-content \{[\s\S]*padding-left: var\(--admin-studio-stage-inline-gutter\);[\s\S]*padding-right: var\(--admin-studio-stage-inline-gutter\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-creation-toolbar \{[\s\S]*display: flex;[\s\S]*border-bottom: 1px solid rgba\(148, 163, 184, 0\.22\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-creation-actions \{[\s\S]*flex: 0 0 auto;/);
    assert.match(adminCss, /#module-ai-creation \.ai-creation-tabs/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-card\[data-ai-creation-panel\] \{[\s\S]*grid-column: 1 \/ -1;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-grid/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-card,\s*#module-ai-creation \.ai-image-admin-card \.config-card-body \{[\s\S]*max-height: none;[\s\S]*overflow: visible;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-form--api-base/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-row/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-card\[data-config="ai-image-guardrails"\]/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-guardrail-grid/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-card\[data-config="ai-image-storage"\]/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-storage-usage/);
    assert.match(adminCss, /\.ai-image-admin-floating-tooltip/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-select \.select-options/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-probe-grid/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-probe-item\.is-error/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-probe-item\.is-warning/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-probe-discovery/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-models/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-workspace \{[\s\S]*grid-template-columns: minmax\(260px, 0\.34fr\) minmax\(0, 1fr\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-sidebar/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-detail/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-list-item/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-list-item\.is-active/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-list-loading/);
    assert.doesNotMatch(adminCss, /#module-ai-creation \.ai-image-admin-model-detail-summary/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-empty--wide/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-pill\.is-selected/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-pill\.is-selected:hover \{[\s\S]*transform: none;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-classifier/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-empty \{[\s\S]*box-sizing: border-box;[\s\S]*max-width: 100%;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-section:is\(:hover, :focus-within, :active\) \{[\s\S]*transform: none !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-models--detail:is\(:hover, :focus-within, :active\) \{[\s\S]*box-shadow: none !important;[\s\S]*transform: none !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-model-empty:is\(:hover, :focus, :focus-visible, :active\) \{[\s\S]*transform: none !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-sidebar:is\(:hover, :focus-within, :active\) \{[\s\S]*background: rgba\(248, 250, 252, 0\.74\) !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-card:is\(:hover, :focus-within, :active\) \{[\s\S]*background: var\(--admin-studio-light-surface, var\(--card-bg\)\) !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-visible-models:is\(:hover, :focus-within, :active\) \{[\s\S]*linear-gradient\(135deg, rgba\(248, 250, 252, 0\.96\), rgba\(239, 246, 255, 0\.72\)\)/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-list-item:is\(:hover, :focus-visible\) \{[\s\S]*background: rgba\(239, 246, 255, 0\.84\) !important;[\s\S]*cursor: pointer !important;/);
    assert.doesNotMatch(adminCss, /html:not\(\[data-theme="dark"\]\) \.admin-main-content :is\([\s\S]{0,260}#module-ai-creation[\s\S]{0,260}\) :is\([\s\S]*background-image: none !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-chip/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-scroll-list \{[\s\S]*overflow-y: auto;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-provider-list \{[\s\S]*max-height: none;[\s\S]*overflow: visible;/);
    assert.doesNotMatch(adminCss, /#module-ai-creation \.ai-image-admin-model-provider-list \{[\s\S]*max-height: clamp\(120px, 24vh, 240px\);/);
    assert.doesNotMatch(adminCss, /#module-ai-creation \.ai-image-admin-provider-card__body\[hidden\]/);
    assert.doesNotMatch(adminCss, /#module-ai-creation \.ai-image-admin-row--model-provider \{/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-actions \{[\s\S]*background: rgba\(248, 250, 252, 0\.64\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-model-actions \.btn-add-config\[data-admin-action="settings-save-ai-image-model-config"\] \{[\s\S]*margin-left: auto;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-models--detail \{[\s\S]*border: 1px solid rgba\(118, 157, 202, 0\.16\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-provider-models--detail \.ai-image-admin-visible-models__grid/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-pricing-group__rules \{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 210px\), 1fr\)\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-pricing-rule \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-pricing-list \{[\s\S]*max-height: min\(68vh, 680px\);/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-form--pricing \[hidden\],[\s\S]*#module-ai-creation \.ai-image-admin-pricing-token-grid \[hidden\] \{[\s\S]*display: none !important;/);
    assert.match(adminCss, /#module-ai-creation \.ai-image-admin-delete-button/);
});
