const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const adminHtml = fs.readFileSync(path.join(root, 'admin-studio.html'), 'utf8');
const adminJs = fs.readFileSync(path.join(root, 'admin-studio.js'), 'utf8');
const adminConfigJs = fs.readFileSync(path.join(root, 'admin-config.js'), 'utf8');
const adminCss = fs.readFileSync(path.join(root, 'css/admin-studio-page.css'), 'utf8');
const adminApi = fs.readFileSync(path.join(root, 'api/admin.js'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

test('settings page exposes AI image admin tab and management panels', () => {
    assert.match(adminHtml, /data-settings-view="ai-image"/);
    assert.match(adminHtml, /id="settings-view-ai-image"/);
    assert.match(adminHtml, /id="aiImageRuntimeStatus"/);
    assert.match(adminHtml, /data-ai-image-runtime="queue"/);
    assert.match(adminHtml, /data-ai-image-runtime="failure"/);
    assert.match(adminHtml, /id="aiImageModelVendorDropdown"[\s\S]*<input type="hidden" id="aiImageModelVendorInput"/);
    assert.match(adminHtml, /id="aiImageModelProtocolDropdown"[\s\S]*<input type="hidden" id="aiImageModelProtocolInput"/);
    assert.match(adminHtml, /id="aiImageModelBaseUrlInput"/);
    assert.match(adminHtml, /id="aiImageModelNameInput"/);
    assert.doesNotMatch(adminHtml, /id="aiImageVisibleModelPicker"/);
    assert.match(adminHtml, /id="aiImageDetectedImageModelsInput"/);
    assert.match(adminHtml, /id="aiImageDetectedChatModelsInput"/);
    assert.match(adminHtml, /id="aiImageVideoModelAliasesInput"/);
    assert.match(adminHtml, /id="aiImageDetectedVideoModelsInput"/);
    assert.match(adminHtml, /id="aiImageDetectedUnknownModelsInput"/);
    assert.match(adminHtml, /id="aiImageVisionModelsInput"/);
    assert.match(adminHtml, /前台可见模型/);
    assert.match(adminHtml, /保存前台可见模型/);
    assert.match(adminHtml, /data-admin-action="settings-create-ai-image-model-provider"/);
    assert.match(adminHtml, /id="aiImageChatModelAliasesInput"/);
    assert.match(adminHtml, /data-admin-action="settings-prompt-ai-image-model-key"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-model-config"/);
    assert.doesNotMatch(adminHtml, /data-admin-action="settings-test-ai-image-model-config"/);
    assert.doesNotMatch(adminHtml, /data-admin-action="settings-discover-ai-image-model-config"/);
    assert.doesNotMatch(adminHtml, /id="aiImageModelProbeStatus"/);
    assert.doesNotMatch(adminHtml, /id="aiImageModelProbeGrid"/);
    assert.match(adminHtml, /class="[^"]*ai-image-admin-model-provider-list[^"]*" id="aiImageModelProviderList"/);
    assert.match(adminHtml, /id="aiImageApiBaseUrlInput"/);
    assert.match(adminHtml, /id="aiImageApiBaseList"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-api-base"/);
    assert.match(adminHtml, /id="aiImageGuardSubmitUserInput"/);
    assert.match(adminHtml, /id="aiImageGuardActiveInput"/);
    assert.match(adminHtml, /class="ai-image-admin-info"[\s\S]*data-ai-image-tooltip="单个登录用户每分钟最多可提交的 AI 图片任务数。"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-guardrails"/);
    assert.match(adminHtml, /id="aiImageStorageUsage"/);
    assert.match(adminHtml, /id="aiImageStoragePreviewRetentionInput"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-storage-policy"/);
    assert.match(adminHtml, /class="[^"]*ai-image-admin-pricing-list[^"]*" id="aiImagePricingList"/);
    assert.match(adminHtml, /id="aiImageAgentList"/);
    assert.match(adminHtml, /data-admin-action="settings-run-ai-image-worker-once"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-pricing"/);
    assert.match(adminHtml, /data-admin-action="settings-save-ai-image-agent"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImagePricingModeInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImagePricingResolutionInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImagePricingRatioInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImageApiBaseSiteInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImageModelVendorInput"/);
    assert.doesNotMatch(adminHtml, /<select class="config-input" id="aiImageModelProtocolInput"/);
    assert.doesNotMatch(adminHtml, /id="aiImageModelGroupDropdown"/);
    assert.doesNotMatch(adminHtml, />默认模型</);
    assert.doesNotMatch(adminHtml, />模型组\s*</);
    assert.doesNotMatch(adminHtml, /生图模型 \/ 别名/);
    assert.match(adminHtml, /id="aiImagePricingModeDropdown"[\s\S]*<input type="hidden" id="aiImagePricingModeInput"/);
    assert.match(adminHtml, /id="aiImageApiBaseSiteDropdown"[\s\S]*<input type="hidden" id="aiImageApiBaseSiteInput"/);
});

test('admin studio loads and mutates AI image config through admin scoped APIs', () => {
    assert.match(adminJs, /route:\s*'ai-image\/config'/);
    assert.match(adminJs, /route=ai-image\/model-config/);
    assert.match(adminJs, /fetchAiImageAdminConfig/);
    assert.match(adminJs, /fetchAiImageModelConfig/);
    assert.match(adminJs, /promptForAiImageModelKey/);
    assert.match(adminJs, /saveAiImageModelConfig/);
    assert.match(adminJs, /testAiImageModelConfig/);
    assert.match(adminJs, /discoverAiImageModelConfig/);
    assert.match(adminJs, /createAiImageModelProviderDraft/);
    assert.match(adminJs, /toggleAiImageVisibleModel/);
    assert.doesNotMatch(adminJs, /renderAiImageVisibleModelPicker/);
    assert.match(adminJs, /renderAiImageProviderVisibleModelSection/);
    assert.match(adminJs, /settings-toggle-ai-image-provider-models/);
    assert.match(adminJs, /toggleAiImageModelProviderModels/);
    assert.match(adminJs, /const hasExpandedState = Object\.prototype\.hasOwnProperty\.call\(adminAiImageState\.modelProviderPanelState, item\.providerId\)/);
    assert.match(adminJs, /const isExpanded = hasExpandedState[\s\S]*\? Boolean\(adminAiImageState\.modelProviderPanelState\[item\.providerId\]\)[\s\S]*: active;/);
    assert.match(adminJs, /modelProbes: Object\.create\(null\)/);
    assert.match(adminJs, /function setAiImageModelProbe\(probe = null\)/);
    assert.match(adminJs, /adminAiImageState\.modelProbes\[providerId\] = normalizedProbe/);
    assert.match(adminJs, /function renderAiImageProviderProbePanel\(provider = \{\}\)/);
    assert.match(adminJs, /data-provider-probe="\$\{escapeHtml\(provider\.providerId \|\| ''\)\}"/);
    assert.match(adminJs, /settings-discover-ai-image-model-provider/);
    assert.doesNotMatch(adminJs, /settings-discover-ai-image-model-config/);
    assert.match(adminJs, /settings-toggle-ai-image-visible-model/);
    assert.match(adminJs, /action:\s*'discover-models'/);
    assert.match(adminJs, /detectedImageModels: nextImageModels/);
    assert.match(adminJs, /detectedChatModels: nextChatModels/);
    assert.match(adminJs, /detectedVideoModels: nextVideoModels/);
    assert.match(adminJs, /生成视频/);
    assert.match(adminJs, /action:\s*'test-model'/);
    assert.match(adminJs, /matrix:\s*true/);
    assert.match(adminJs, /discoverModels:\s*true/);
    assert.match(adminJs, /const probeModes = draft\.modelGroup === 'chat'[\s\S]*\['chat', 'vision'\]/);
    assert.match(adminJs, /const nextVisionModels = mergeAiImageModelCandidates\(/);
    assert.match(adminJs, /setAiImageModelsInputValue\(document\.getElementById\('aiImageVisionModelsInput'\)/);
    assert.match(adminJs, /payload\?\.matrix === true && data\?\.check/);
    assert.match(adminJs, /resolutions:\s*\['1k', '2k', '4k'\]/);
    assert.match(adminJs, /ai-image-admin-probe-item/);
    assert.match(adminJs, /ai-image-admin-probe-discovery/);
    assert.match(adminJs, /settings-apply-ai-image-discovered-model/);
    assert.match(adminJs, /settings-classify-ai-image-unknown-model/);
    assert.match(adminJs, /function applyAiImageDiscoveredModel\(model = '', group = 'unknown', providerId = ''\)/);
    assert.match(adminJs, /function classifyAiImageUnknownModel\(model = '', group = 'image', providerId = ''\)/);
    assert.match(adminJs, /removeAiImageModelCandidate\(provider\.detectedUnknownModels \|\| provider\.detected_unknown_models, normalizedModel\)/);
    assert.match(adminJs, /renderAiImageUnknownModelClassifier\(label, providerId\)/);
    assert.match(adminJs, /设为文本/);
    assert.match(adminJs, /设为生图/);
    assert.match(adminJs, /设为视频/);
    assert.match(adminJs, /function renderAiImageVisibleModelPill\(model = '', group = 'image', selectedModels = \[\], providerId = ''\) \{[\s\S]*data-provider-id="\$\{escapeHtml\(providerId \|\| ''\)\}"/);
    assert.match(adminJs, /function renderAiImageDiscoveredModelButton\(model = '', group = 'unknown', providerId = ''\) \{[\s\S]*data-provider-id="\$\{escapeHtml\(providerId \|\| ''\)\}"/);
    assert.match(adminJs, /renderAiImageDiscoveredModelButton\(model, group\.group, provider\.providerId \|\| ''\)/);
    assert.match(adminJs, /function getAiImageProbeUpstreamText\(upstream = \{\}\)/);
    assert.match(adminJs, /通道 ID/);
    assert.match(adminJs, /请求 ID/);
    assert.match(adminJs, /function inferAiImageModelGroup\(value, imageModels = \[\], chatModels = \[\], videoModels = \[\], fallback = 'image'\)/);
    assert.match(adminJs, /function scopeAiImageModelsByGroup\(modelGroup = 'image', imageModels = \[\], chatModels = \[\], videoModels = \[\]\)/);
    assert.match(adminJs, /chatModels: group === 'image' \|\| group === 'video' \? \[\] : normalizeAiImageModelsList\(chatModels, ''\)/);
    assert.match(adminJs, /hiddenInput\.dataset\.adminDropdownDirty = '1'/);
    assert.match(adminJs, /hiddenInput\.dispatchEvent\(new Event\('change', \{ bubbles: true \}\)\)/);
    assert.match(adminJs, /inferAiImageModelGroupFromLists\(draftImageModels, draftChatModels, draftVideoModels\)/);
    assert.match(adminJs, /function buildAiImageProviderIdSuggestion\(providerId = 'default', modelGroup = 'image', existingProviders = \[\]\)/);
    assert.match(adminJs, /function ensureAiImageProviderIdForDraft\(draft = \{\}, provider = null, config = getAiImageModelConfig\(\)\)/);
    assert.match(adminJs, /deleteAiImageModelConfig/);
    assert.match(adminJs, /settings-delete-ai-image-model-config/);
    assert.match(adminJs, /window\.deleteAiImageModelConfig\?\.\(actionEl\.dataset\.providerId \|\| actionEl\.dataset\.provider_id \|\| ''\)/);
    assert.match(adminJs, /adminAiImageState\.apiBaseUrls/);
    assert.match(adminJs, /saveAiImageApiBaseUrl/);
    assert.match(adminJs, /disableAiImageApiBaseUrl/);
    assert.match(adminJs, /save-api-base-url/);
    assert.match(adminJs, /disable-api-base-url/);
    assert.match(adminJs, /adminAiImageState\.guardrails/);
    assert.match(adminJs, /DEFAULT_AI_IMAGE_GUARDRAILS/);
    assert.match(adminJs, /saveAiImageGuardrails/);
    assert.match(adminJs, /action:\s*'save-guardrails'/);
    assert.match(adminJs, /adminAiImageState\.storageUsage/);
    assert.match(adminJs, /saveAiImageStoragePolicy/);
    assert.match(adminJs, /action:\s*'save-storage-policy'/);
    assert.match(adminJs, /adminAiImageState\.runtime/);
    assert.match(adminJs, /function renderAiImageAdminPanel\(\) \{[\s\S]*initCustomDropdown\?\.\(\);[\s\S]*bindAiImageAdminTooltips\(\);/);
    assert.match(adminJs, /getAiImageRuntimeHealth/);
    assert.match(adminJs, /getAiImageRuntimeText\('queue'\)/);
    assert.match(adminJs, /postAiImageAdminConfig/);
    assert.match(adminJs, /saveAiImagePricingRule/);
    assert.match(adminJs, /saveAiImageAgent/);
    assert.match(adminJs, /deleteAiImagePricingRule/);
    assert.match(adminJs, /settings-delete-ai-image-pricing/);
    assert.doesNotMatch(adminJs, /<i class="fas fa-clone"><\/i> 复制新建/);
    assert.match(adminJs, /settings-test-ai-image-model-provider-full/);
    assert.match(adminJs, /<i class="fas fa-stethoscope"><\/i> 模型自检/);
    assert.match(adminJs, /<i class="fas fa-magnifying-glass"><\/i> 检测上游支持模型/);
    assert.doesNotMatch(adminJs, /data-admin-action="settings-test-ai-image-model-provider"/);
    assert.doesNotMatch(adminJs, /<i class="fas fa-plug"><\/i> 连通性/);
    assert.match(adminJs, /打开这一行到上方编辑器/);
    assert.match(adminJs, /<i class="fas fa-pen"><\/i> 编辑/);
    assert.match(adminJs, /const canDelete = item\.source === 'stored'/);
    assert.match(adminJs, /const canProbe = Boolean\(item\.configured\)/);
    assert.match(adminJs, /data-admin-action="settings-delete-ai-image-model-config"[\s\S]*data-provider-id="\$\{escapeHtml\(item\.providerId\)\}"/);
    assert.match(adminJs, /环境变量配置不可在这里删除/);
    assert.match(adminJs, /const activePricing = adminAiImageState\.pricing\.filter\(\(rule\) => rule\.is_active !== false\)/);
    assert.match(adminJs, /data-admin-action="settings-delete-ai-image-pricing"/);
    assert.match(adminJs, /window\.deleteAiImagePricingRule = deleteAiImagePricingRule/);
    assert.doesNotMatch(adminJs, /testAiImageModelProviderConnectivity/);
    assert.match(adminJs, /disableAiImagePricingRule/);
    assert.match(adminJs, /disableAiImageAgent/);
    assert.match(adminJs, /\/api\/admin\?route=ai-image\/run/);
    assert.match(adminJs, /normalizedViewName === 'ai-image'/);
    assert.match(adminApi, /aiImageModelConfigHandler/);
    assert.match(adminApi, /'ai-image\/model-config': aiImageModelConfigHandler/);
});

test('settings view normalization preserves AI image tab instead of falling back to pricing', () => {
    assert.match(adminConfigJs, /const SETTINGS_VIEW_DOMAIN_MAP = Object\.freeze\(\{[\s\S]*'ai-image': \[\],[\s\S]*\}\);/);
    assert.match(adminConfigJs, /function normalizeSettingsViewName\(viewName = ''\) \{[\s\S]*SETTINGS_VIEW_DOMAIN_MAP\[normalizedView\][\s\S]*return normalizedView;[\s\S]*return 'pricing';[\s\S]*\}/);
    assert.match(adminJs, /case 'switch-settings-view':[\s\S]*window\.switchSettingsView\?\.\(actionEl\.dataset\.settingsView\);[\s\S]*break;/);
    assert.match(adminJs, /if \(normalizedViewName === 'ai-image'\) \{[\s\S]*renderAiImageAdminPanel\(\);[\s\S]*fetchAiImageAdminConfig/);
});

test('AI image real executor dispatches image, reverse, and chat modes', () => {
    const modelSource = fs.readFileSync(path.join(root, 'server/api-handlers/_ai-image-models.js'), 'utf8');
    const runHandlerSource = fs.readFileSync(path.join(root, 'server/api-handlers/admin/ai-image/run.js'), 'utf8');
    const workerSource = fs.readFileSync(path.join(root, 'scripts/ai-image-worker.js'), 'utf8');

    assert.match(modelSource, /TEXT_VISION_MODES = Object\.freeze\(new Set\(\['reverse', 'chat'\]\)\)/);
    assert.match(modelSource, /executeOpenAiCompatibleTextVision/);
    assert.match(modelSource, /chat\/completions/);
    assert.match(modelSource, /executeOpenAiCompatibleAiImageTask/);
    assert.match(runHandlerSource, /createOpenAiCompatibleImageExecutor/);
    assert.match(workerSource, /createOpenAiCompatibleImageExecutor/);
});

test('AI image admin settings keep scoped styling and worker command contract', () => {
    assert.equal(packageJson.scripts['ai-image:worker'], 'node scripts/ai-image-worker.js');
    assert.match(adminCss, /20260621_AI_IMAGE_ADMIN_SETTINGS_1/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-grid/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-card,\s*#module-settings #settings-view-ai-image \.ai-image-admin-card \.config-card-body \{[\s\S]*max-height: none;[\s\S]*overflow: visible;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-form--api-base/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-row/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-card\[data-config="ai-image-guardrails"\]/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-guardrail-grid/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-card\[data-config="ai-image-storage"\]/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-storage-usage/);
    assert.match(adminCss, /\.ai-image-admin-floating-tooltip/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-select \.select-options/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-probe-grid/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-probe-item\.is-error/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-probe-discovery/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-visible-models/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card__header/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card__body/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card__body\[hidden\] \{[\s\S]*display: none !important;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-visible-model-pill\.is-selected/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-visible-model-classifier/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-visible-model-empty/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-model-chip/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-scroll-list \{[\s\S]*overflow-y: auto;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-model-provider-list \{[\s\S]*max-height: clamp\(120px, 24vh, 240px\);/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-row--model-provider \{[\s\S]*grid-template-columns: 1fr;[\s\S]*padding: 0;[\s\S]*overflow: hidden;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-row--model-provider:is\(:hover, :focus-within\),[\s\S]*background: rgba\(239, 246, 255, 0\.9\) !important;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card__header:is\(:hover, :focus-visible\) \{[\s\S]*background: transparent !important;[\s\S]*box-shadow: none !important;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card__header \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(150px, auto\) minmax\(34px, auto\);/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-card__body \{[\s\S]*padding: 0 12px 12px;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-provider-meta/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-row--model-provider \.btn-add-config--compact \{[\s\S]*min-width: 86px;/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-pricing-list \{[\s\S]*max-height: clamp\(260px, 42vh, 520px\);/);
    assert.match(adminCss, /#module-settings #settings-view-ai-image \.ai-image-admin-delete-button/);
});
