const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const workbenchPath = path.resolve(__dirname, '../js/ai-image-workbench.js');
const source = fs.readFileSync(workbenchPath, 'utf8');

function getCssRuleBlock(cssSource, selector) {
    const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const match = cssSource.match(new RegExp(`${escaped}\\s*\\{[\\s\\S]*?\\n\\}`));
    return match ? match[0] : '';
}

test('ai image workbench calls public ai-image APIs for config, records, and submit', () => {
    assert.match(source, /scope:\s*'ai-image'/);
    assert.doesNotMatch(source, /requestAiImage\('agents'/);
    assert.match(source, /requestAiImage\('pricing'/);
    assert.match(source, /requestAiImage\('tasks'/);
    assert.match(source, /requestAiImage\('upload'/);
    assert.match(source, /requestAiImage\('download'/);
    assert.match(source, /requestAiImage\('usage'/);
    assert.match(source, /requestAiImage\('submit'/);
    assert.match(source, /requestAiImage\('cancel'/);
    assert.match(source, /requestAiImage\('models'/);
});

test('ai image workbench removes toolbox and agent shortcuts from the user flow', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.doesNotMatch(source, /data-aiw-action="toggle-toolbox"/);
    assert.doesNotMatch(source, /data-aiw-agent/);
    assert.doesNotMatch(source, /function renderToolboxPanel/);
    assert.doesNotMatch(source, /function renderAgentPanel/);
    assert.doesNotMatch(source, /data-aiw-action="clear-agent"/);
    assert.doesNotMatch(source, /function getActiveAgent/);
    assert.doesNotMatch(source, /function getAgents/);
    assert.doesNotMatch(source, /agentSlug:/);
    assert.doesNotMatch(source, /activeAgent/);
    assert.match(source, /referenceImages:\s*task\.referenceImages/);
    assert.match(source, /state\.referenceImages = extraReferenceImages;/);
    assert.doesNotMatch(cssSource, /ai-image-toolbox/);
    assert.doesNotMatch(cssSource, /ai-image-agent/);
    assert.doesNotMatch(cssSource, /aiw-toolbox/);
});

test('ai image workbench does not persist user API key to localStorage snapshot', () => {
    const persistStateMatch = source.match(/function persistState\(\) \{[\s\S]*?global\.localStorage\?\.setItem\(STORAGE_KEY, JSON\.stringify\(serializable\)\);[\s\S]*?\n    \}/);
    assert.ok(persistStateMatch, 'persistState function should be present');
    assert.equal(/apiKey\s*:/.test(persistStateMatch[0]), false);
    assert.equal(/chatAttachments\s*:/.test(persistStateMatch[0]), false);
    assert.match(persistStateMatch[0], /runtimeApiModelCacheByBaseUrl: serializeRuntimeModelCache\(\)/);
    assert.match(source, /const apiKey = String\(state\.apiKey \|\| ''\)\.trim\(\);/);
    assert.match(source, /if \(task\.billingMode === 'api' && apiKey\) \{[\s\S]*?payload\.apiKey = apiKey;/);
    assert.match(source, /updateStoredApiKeyStatuses\(pricingPayload\?\.storedApiKeys \|\| pricingPayload\?\.stored_api_keys \|\| \[\]\)/);
});

test('ai image workbench waits for server results instead of locally fabricating completed images', () => {
    assert.doesNotMatch(source, /buildTaskResultImages/);
    assert.doesNotMatch(source, /estimateMockTokenUsage/);
    assert.doesNotMatch(source, /continuing with preview task/);
    assert.doesNotMatch(source, /Math\.min\(92,/);
    assert.match(source, /scheduleRemoteRecordsPoll/);
    assert.match(source, /progressKnown/);
    assert.match(source, /is-indeterminate/);
});

test('ai image workbench renders partial images while a task is still running', () => {
    assert.match(source, /function buildTaskImageEntries\(task = \{\}/);
    assert.match(source, /const partialImageEntries = buildTaskImageEntries\(task\)/);
    assert.match(source, /const hasPartialImages = partialImageEntries\.length > 0/);
    assert.match(source, /const pendingPreviewCount = Math\.max\(0, total - partialImageEntries\.length\)/);
    assert.match(source, /const showPendingPreview = !isStopped && task\.status !== 'succeeded' && pendingPreviewCount > 0/);
    assert.match(source, /ai-image-result-grid--partial/);
    assert.match(source, /partialImageEntries\.map\(\(entry, index\) => renderTaskImageEntry\(entry, index/);
    assert.match(source, /showPendingPreview \? renderInlineTaskPreview\(task, '生成中', \{ showPrompt: false \}\) : ''/);
    assert.match(source, /\.\.\.imageEntriesForTask,/);
});

test('ai image workbench uploads reference images before storing them on task state', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /async function uploadReferenceImageFile\(file\)/);
    assert.match(source, /async function uploadReferenceImageDataUrl\(imageData, title = '续作图片'\)/);
    assert.match(source, /async function resolveSubmittableReferenceItem\(item = null\)/);
    assert.match(source, /reference\.role === 'base' && \(reference\.resultId \|\| reference\.taskId\)/);
    assert.match(source, /canResolveContinuationOnServer/);
    assert.match(source, /isTransientImageUrl\(imageContext\.image\)/);
    assert.match(source, /referenceResultId:\s*serverUuidOrEmpty\(task\.referenceResultId\)/);
    assert.match(source, /referenceTaskId:\s*serverUuidOrEmpty\(task\.referenceTaskId\)/);
    assert.match(source, /state\.referenceImages = extraReferenceImages;/);
    assert.match(source, /input\.multiple = true;/);
    assert.match(source, /const uploaded = await uploadReferenceImageFile\(file\);/);
    assert.match(source, /state\.referenceImage = first\.image;/);
    assert.match(source, /referenceImageUrl:\s*task\.referenceImage/);
    assert.match(source, /referenceImages:\s*task\.referenceImages/);
    assert.match(source, /ai-image-main-error/);
    assert.match(cssSource, /\.ai-image-main-error/);
    assert.doesNotMatch(source, /alert\(/);
    assert.doesNotMatch(source, /URL\.createObjectURL/);
});

test('ai image workbench sends memory-only document and PDF chat attachments', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /const CHAT_DOCUMENT_ACCEPT = '\.txt,\.md,\.csv,\.json,\.html,\.htm,\.xml,\.log,\.pdf/);
    assert.match(source, /const CHAT_ATTACHMENT_ACCEPT = `image\/\*,\$\{CHAT_DOCUMENT_ACCEPT\}`/);
    assert.match(source, /const PDFJS_CDN_URL = 'https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/pdf\.js\/4\.10\.38\/pdf\.min\.mjs'/);
    assert.match(source, /async function readChatAttachmentFile\(file\)/);
    assert.match(source, /async function extractPdfText\(file\)/);
    assert.match(source, /state\.chatAttachments = normalizeChatAttachmentList\(\[/);
    assert.match(source, /data-aiw-action="remove-chat-attachment"/);
    assert.match(source, /payload\.chatAttachments = normalizedChatAttachments\.map/);
    assert.match(source, /submitChatStreamTask\(task, threadRoot, chatThreadMessages, draftChatAttachments\)/);
    assert.match(source, /clearChatAttachments\(\);/);
    assert.match(source, /上传图片或文档\/PDF/);
    assert.match(source, /上传文档\/PDF/);
    assert.doesNotMatch(source, /图片输入：当前模型暂未接通/);
    assert.doesNotMatch(source, /文档\/PDF：提取文本后随本轮对话发送/);
    assert.match(cssSource, /\.ai-image-main-file-list/);
    assert.match(cssSource, /\.ai-image-main-file-chip/);
});

test('ai image workbench API key copy uses backend encrypted storage status', () => {
    assert.match(source, /留空使用已保存 Key，输入新 Key 以更换/);
    assert.match(source, /后端已加密保存/);
    assert.match(source, /前端只显示尾号，不返回明文/);
    assert.match(source, /前端不持久化明文 Key/);
    assert.match(source, /hasUsableApiKey\(\)/);
    assert.doesNotMatch(source, /仅当前会话使用，提交时随请求发送/);
});

test('ai image workbench can discover upstream API models and refresh runtime options', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /function discoverRuntimeApiModels\(\)/);
    assert.match(source, /data-aiw-action="discover-api-models"/);
    assert.match(source, /检测上游支持模型/);
    assert.match(source, /读取当前上游模型列表/);
    assert.match(source, /requestAiImage\('models'/);
    assert.match(source, /updateRuntimeApiModels\(payload \|\| \{\}, \{ cache: true, apiBaseUrl: normalizedBaseUrl \}\)/);
    assert.match(source, /function applyRuntimeModelCache\(apiBaseUrl = state\.apiBaseUrl\)/);
    assert.match(source, /已使用上次检测到的 \$\{cachedCount\} 个上游模型/);
    assert.match(source, /const detected = entry\.detected === true \|\| entry\.discovered === true \|\| entry\.source === 'upstream_discovery'/);
    assert.match(source, /if \(!detected && !chatModels\.length && !imageModels\.length && !videoModels\.length\) return null;/);
    assert.match(source, /runtimeApiTextModels = cached\.chatModels\.slice\(\);/);
    assert.match(source, /runtimeApiImageModels = cached\.imageModels\.slice\(\);/);
    assert.match(source, /runtimeAdminTextModels = \[\];/);
    assert.match(source, /runtimeAdminImageModels = \[\];/);
    assert.match(source, /runtimeAdminModelProviders = \[\];/);
    assert.match(source, /function getRuntimeProviderFallbackLabel\(apiBaseUrl = state\.apiBaseUrl\)/);
    assert.match(source, /function normalizeRuntimeProviderLabel\(label = '', fallbackLabel = '当前上游'\)/);
    assert.match(source, /if \(!normalized \|\| \/\^检测到的上游模型\$\/i\.test\(normalized\)\) return fallbackLabel;/);
    assert.match(source, /label: getRuntimeProviderFallbackLabel\(apiBaseUrl\)/);
    assert.match(source, /function applyRuntimeModelSelectionDefaults\(/);
    assert.match(source, /target === 'admin'/);
    assert.match(source, /state\.pointsTextModel = textModels\[0\]\?\.id \|\| '';/);
    assert.match(source, /const hasExplicitProviders = Array\.isArray\(payload\?\.model_providers \|\| payload\?\.image_model_providers\);/);
    assert.match(source, /const hasExplicitDiscoveryResult = cache === true \|\| payload\?\.discovery \|\| payload\?\.source === 'upstream_discovery' \|\| hasExplicitProviders;/);
    assert.match(source, /runtimeApiImageModels = hasExplicitDiscoveryResult \? imageModels : \(imageModels\.length \? imageModels : API_IMAGE_MODELS\.slice\(\)\);/);
    assert.match(source, /runtimeApiTextModels = hasExplicitDiscoveryResult \? chatModels : \(chatModels\.length \? chatModels : API_TEXT_MODELS\.slice\(\)\);/);
    assert.match(source, /const fallbackProviderLabel = getRuntimeProviderFallbackLabel\(apiBaseUrl \|\| payload\.apiBaseUrl \|\| payload\.api_base_url\);/);
    assert.match(source, /normalizeRuntimeModelProvider\(provider, index, \{ fallbackLabel: fallbackProviderLabel \}\)/);
    assert.match(source, /visionModelSet\.has\(String\(option\.id \|\| ''\)\.trim\(\)\.toLowerCase\(\)\)/);
    assert.match(source, /option\.supportsImageInput = true;/);
    assert.doesNotMatch(source, /option\.supportsImageInput = visionModelSet\.has/);
    assert.match(source, /function inferModelFamilyLabel\(modelId = '', fallbackLabel = ''\)/);
    assert.match(source, /return 'Gemini';/);
    assert.match(source, /return 'ChatGPT';/);
    assert.match(source, /function groupRuntimeModelsByFamily\(providers = \[\], mode = inferWorkbenchMode\(\)\)/);
    assert.match(source, /function getRuntimeModelProvidersForBillingMode\(\)/);
    assert.match(source, /return state\.billingMode === 'api' \? runtimeApiModelProviders : runtimeAdminModelProviders;/);
    assert.match(source, /function getRuntimeModelGroups\(mode = inferWorkbenchMode\(\), providers = getRuntimeModelProvidersForBillingMode\(\)\)/);
    assert.match(source, /function getRuntimeModelGroupOptions\(mode = inferWorkbenchMode\(\)\)/);
    assert.match(source, /\[normalizedBaseUrl\]: \{\s*detected: true,\s*chatModels,\s*imageModels,\s*videoModels\s*\}/);
    assert.match(source, /function renderModelProviderSelect\(\{ field, label, icon, value, mode = inferWorkbenchMode\(\), disabled = false, wide = false \}\)/);
    assert.match(source, /const options = getRuntimeModelGroupOptions\(mode\);/);
    assert.match(source, /function isModelOptionsLoading\(mode = inferWorkbenchMode\(\)\)/);
    assert.match(source, /const isLoading = isModelOptionsLoading\(mode\);/);
    assert.match(source, /const emptyModelLabel = isLoading \? '模型加载中' : '模型未配置';/);
    assert.match(source, /fa-circle-notch fa-spin/);
    assert.doesNotMatch(source, /无可用模型/);
    assert.match(source, /<strong>\$\{escapeHtml\(selected\.label \|\| selected\.id \|\| label\)\}<\/strong>/);
    assert.match(source, /ai-image-model-provider/);
    assert.match(source, /ai-image-model-submenu/);
    assert.match(source, /disabled: !modelOptions\.length/);
    assert.match(source, /function filterRuntimeModelsByGroup\(options = \[\], group = 'image'\)/);
    assert.match(source, /updateRuntimeApiModels\(pricingPayload \|\| \{\}, \{ target: 'admin' \}\)/);
    assert.match(source, /applyRuntimeModelCache\(state\.apiBaseUrl\);/);
    assert.match(source, /已检测到 \$\{detectedCount\} 个上游模型/);
    assert.match(source, /\/v\\d\+\(\?:alpha\|beta\)\?/);
    assert.match(source, /modelDiscoveryState\.loading/);
    assert.match(source, /if \(group === 'image'\) return looksLikeImageModelId\(id\) \|\| !looksLikeTextModelId\(id\);/);
    assert.match(source, /return !looksLikeImageModelId\(id\);/);
    assert.match(source, /const toolChatCopy = state\.billingMode === 'api'/);
    assert.match(source, /使用后台对话模型，按积分规则计费。/);
    assert.match(source, /使用后台生图模型，按积分规则计费。/);
    assert.match(source, /使用后台视频模型，按积分规则计费。/);
    assert.match(source, /data-aiw-chip="apiTool:\$\{escapeHtml\(item\.id\)\}"/);
    assert.match(source, /id: 'chat',\s*icon: 'fa-comments',\s*label: '文本对话'/);
    assert.match(source, /id: 'image',\s*icon: 'fa-image',\s*label: '生成图片'/);
    assert.match(source, /id: 'video',\s*icon: 'fa-film',\s*label: '生成视频'/);
    assert.match(source, /visible: getActiveModelOptions\('video'\)\.length > 0/);
    assert.match(source, /if \(field === 'apiTool'\) setWorkbenchToolMode\(value\);/);
    assert.match(cssSource, /\.ai-image-api-model-discovery/);
    assert.match(cssSource, /\.ai-image-api-model-discovery-btn/);
    assert.match(cssSource, /\.ai-image-model-cascade/);
    assert.match(cssSource, /\.ai-image-model-provider::after\s*\{[\s\S]*left: 100%;[\s\S]*width: 10px;[\s\S]*content: "";/);
    assert.match(cssSource, /\.ai-image-model-provider:hover > \.ai-image-model-submenu\s*\{[\s\S]*pointer-events: auto;/);
    assert.doesNotMatch(cssSource, /\.ai-image-model-provider:focus-within > \.ai-image-model-submenu/);
    assert.match(cssSource, /\.ai-image-model-provider:hover > \.ai-image-model-provider-trigger,\s*\.ai-image-model-provider:focus-within > \.ai-image-model-provider-trigger\s*\{[\s\S]*background: rgba\(95, 143, 188, 0\.12\);/);
    assert.match(cssSource, /\.ai-image-model-provider\.is-active > \.ai-image-model-provider-trigger\s*\{[\s\S]*font-weight: 900;/);
    assert.match(cssSource, /\.ai-image-model-provider\.is-active > \.ai-image-model-provider-trigger::before\s*\{[\s\S]*content: "";/);
    assert.doesNotMatch(cssSource, /\.ai-image-model-provider:hover > \.ai-image-model-provider-trigger,\s*\.ai-image-model-provider:focus-within > \.ai-image-model-provider-trigger,\s*\.ai-image-model-provider\.is-active > \.ai-image-model-provider-trigger/);
    assert.match(cssSource, /\.ai-image-main-tools \.ai-image-model-submenu/);
});

test('ai image prompt detail generate action opens image generation mode', () => {
    assert.match(source, /function resetConversationDraft\(\)/);
    assert.match(source, /state\.activeTaskId = '';/);
    assert.match(source, /state\.referenceImage = '';\s*state\.referenceTitle = '';\s*state\.referenceIntent = '';\s*state\.referenceImages = \[\];\s*state\.continuationImage = null;/);
    assert.match(source, /function openPromptForImageGeneration\(payload = \{\}\)/);
    assert.match(source, /state\.apiImageTool = true;/);
    assert.match(source, /const requestedMode = String\(payload\.mode \|\| ''\)\.trim\(\);/);
    assert.match(source, /const generationMode = \['text', 'image', 'reverse'\]\.includes\(requestedMode\) \? requestedMode : 'text';/);
    assert.match(source, /openPromptForImageGeneration\(getCurrentPromptModalPayload\(mode\)\)/);
    assert.match(source, /applyPrompt: \(payload\) => openPromptForImageGeneration\(payload\)/);
    assert.doesNotMatch(source, /openPromptAsNewConversation\(getCurrentPromptModalPayload\(mode\)\)/);
    assert.doesNotMatch(source, /applyPrompt: \(payload\) => openPromptAsNewConversation\(payload\)/);
});

test('ai image variation from prompt detail uses image as variation base without copying the original prompt', () => {
    assert.match(source, /const isImageVariation = mode === 'image'/);
    assert.match(source, /const isReversePrompt = mode === 'reverse'/);
    assert.match(source, /prompt: isImageVariation \|\| isReversePrompt \? '' : \(promptText \|\| title\)/);
    assert.match(source, /referenceIntent: isImageVariation \? 'variation' : ''/);
    assert.match(source, /if \(state\.referenceIntent === 'variation'\) return 'image';/);
    assert.match(source, /const isVariationReference = Boolean\(state\.referenceIntent === 'variation' && state\.referenceImage && !isImplicitContinuation\)/);
    assert.match(source, /isVariationReference \? '图像发散' : \(imageContext\.title \|\| '参考图片'\)/);
    assert.match(source, /isVariationReference \? '描述你希望基于这张图发散出的方向'/);
});

test('ai image workbench records original image downloads without blocking direct download', () => {
    assert.match(source, /async function recordImageDownload\(element\)/);
    assert.match(source, /data-aiw-download="original"/);
    assert.match(source, /data-result-id=/);
    assert.match(source, /data-task-id=/);
    assert.match(source, /download target="_blank"/);
});

test('ai image workbench handles expired result images without breaking the result card', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /function getImagePreviewUrl\(image\)/);
    assert.match(source, /root\.addEventListener\('error', handleRootError, true\)/);
    assert.match(source, /root\.addEventListener\('load', handleRootLoad, true\)/);
    assert.match(source, /const loadedImageUrls = new Set\(\)/);
    assert.match(source, /const failedImageUrls = new Set\(\)/);
    assert.match(source, /const stableImageUrlsByIdentity = new Map\(\)/);
    assert.match(source, /function getImageLoadKey\(value = ''\)/);
    assert.match(source, /new URL\(raw, global\.location\?\.href \|\| document\.baseURI \|\| ''\)\.href/);
    assert.match(source, /function rememberImageLoaded\(value = ''\)/);
    assert.match(source, /function rememberImageFailed\(value = ''\)/);
    assert.match(source, /function getImageIdentityKey\(/);
    assert.match(source, /function rememberStableImageUrl\(identityKey = '', src = ''\)/);
    assert.match(source, /function getStableImageUrl\(identityKey = '', fallbackSrc = ''\)/);
    assert.match(source, /if \(loadedImageUrls\.has\(key\)\) return;/);
    assert.match(source, /function hasLoadedImage\(value = ''\)/);
    assert.match(source, /function hasFailedImage\(value = ''\)/);
    assert.match(source, /src:\s*imageUrl \|\| original/);
    assert.match(source, /original,\n\s*preview:/);
    assert.match(source, /originalReady/);
    assert.match(source, /originalStatus/);
    assert.match(source, /src:\s*getImagePreviewUrl\(image\) \|\| getImageUrl\(image\)/);
    assert.match(source, /originalSrc:\s*getImageUrl\(image\)/);
    assert.match(source, /data-aiw-preview-thumb/);
    assert.match(source, /image\.dataset\.aiwFallbackTried/);
    assert.match(source, /rememberImageLoaded\(imageSrc\)/);
    assert.match(source, /rememberImageFailed\(imageSrc\)/);
    assert.match(source, /classList\.add\('is-image-broken'\)/);
    assert.match(source, /function handleRootLoad\(event\)/);
    assert.match(source, /taskThumb\.classList\.add\('is-image-loaded'\)/);
    assert.match(source, /media\.classList\.add\('is-image-loaded'\)/);
    assert.match(source, /function syncRenderedImageLoadStates\(\)/);
    assert.match(source, /root\.querySelectorAll\('\.ai-image-task-thumb img, \.ai-image-result-media img'\)/);
    assert.match(source, /const loaded = image\.complete && image\.naturalWidth > 0/);
    assert.doesNotMatch(source, /const broken = image\.complete && !image\.naturalWidth/);
    assert.match(source, /syncRenderedImageLoadStates\(\);[\s\S]*syncMainPromptHeight\(\)/);
    assert.match(source, /aria-disabled', 'true'/);
    assert.match(source, /ai-image-result-broken/);
    assert.match(source, /const mediaStateClass = \[/);
    assert.match(source, /const previewSrc = isVideo \? entry\.src : getStableImageUrl\(imageIdentityKey, entry\.src\)/);
    assert.match(source, /hasLoadedImage\(previewSrc\) \? 'is-image-loaded' : ''/);
    assert.match(source, /hasFailedImage\(previewSrc\) \? 'is-image-broken' : ''/);
    assert.match(source, /data-aiw-image-key="\$\{escapeHtml\(imageIdentityKey\)\}"/);
    assert.match(cssSource, /\.ai-image-result-media\.is-image-broken img/);
    assert.match(cssSource, /\.ai-image-result-media::before/);
    const resultImageRule = getCssRuleBlock(cssSource, '.ai-image-result-media img');
    assert.match(resultImageRule, /object-fit: cover;/);
    assert.match(resultImageRule, /transform: scale\(1\);/);
    assert.doesNotMatch(resultImageRule, /opacity: 0;/);
    assert.match(cssSource, /\.ai-image-result-broken/);
    assert.match(cssSource, /\.ai-image-result-action\.is-disabled/);
});

test('ai image workbench treats preview and original readiness as separate states', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /ORIGINAL_READY_POLL_LIMIT/);
    assert.match(source, /function taskHasPendingOriginal\(task = \{\}\)/);
    assert.match(source, /function getPendingOriginalTasks\(\)/);
    assert.match(source, /function shouldPollRemoteRecords\(\)/);
    assert.match(source, /original_image_pending/);
    assert.match(source, /data-aiw-original-ready/);
    assert.match(source, /原图转存中/);
    assert.match(cssSource, /\.ai-image-result-original-status/);
    assert.match(cssSource, /\.ai-image-full-preview__pending/);
});

test('ai image workbench exposes preflight timing in task summaries', () => {
    assert.match(source, /const preflightMs = normalizeDurationMs\(timing\.preflight_ms \|\| timing\.preflightMs\)/);
    assert.match(source, /configResolveMs/);
    assert.match(source, /referenceFetchMs/);
    assert.match(source, /预检/);
});

test('ai image full preview keeps preview visible while original is preparing', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /const ORIGINAL_READY_POLL_LIMIT = 80/);
    assert.match(source, /function syncImagePreviewFromTasks\(\)/);
    assert.match(source, /function getPreviewOriginalProgress/);
    assert.match(source, /let imagePreviewLoadTimer = null/);
    assert.match(source, /function preloadImagePreviewOriginal\(\)/);
    assert.match(source, /new Image\(\)/);
    assert.match(source, /loadRemoteRecords\(\{ force: true \}\)\.finally\(scheduleRemoteRecordsPoll\)/);
    assert.match(source, /\$\{originalAvailable \? '高清原图加载中' : '高清原图准备中'\} \$\{originalProgress\}%/);
    assert.match(source, /加载完成后自动切换/);
    assert.match(source, /const originalLoaded = originalAvailable && Boolean\(imagePreview\.originalLoaded\)/);
    assert.match(source, /<img class="\$\{originalLoaded \? 'is-original-ready' : 'is-preview-only'\}"/);
    assert.match(source, /is-preview-only/);
    assert.match(source, /ai-image-full-preview__pending-bar/);
    assert.match(source, /data-aiw-preview-original-src/);
    assert.match(source, /originalLoaded/);
    assert.match(source, /src: imagePreview\.originalLoaded && originalReady \? originalSrc : \(previewSrc \|\| imagePreview\.src\)/);
    assert.match(cssSource, /\.ai-image-full-preview__body img\.is-preview-only/);
    assert.match(cssSource, /\.ai-image-full-preview__pending-bar span/);
});

test('ai image result cards always render compressed preview instead of original source', () => {
    assert.match(source, /const previewSrc = isVideo \? entry\.src : getStableImageUrl\(imageIdentityKey, entry\.src\)/);
    assert.match(source, /<img src="\$\{escapeHtml\(previewSrc\)\}" alt="生成结果 \$\{index \+ 1\}" loading="eager" decoding="async">/);
    assert.match(source, /data-aiw-preview-src="\$\{escapeHtml\(previewSrc\)\}"/);
    assert.match(source, /data-aiw-preview-thumb="\$\{escapeHtml\(previewSrc\)\}"/);
    assert.match(source, /data-aiw-preview-original-src="\$\{escapeHtml\(entry\.originalSrc \|\| ''\)\}"/);
    assert.doesNotMatch(source, /const displaySrc = originalReady \? entry\.originalSrc : entry\.src/);
});

test('ai image workbench renders lightweight activity summary in history sidebar', () => {
    assert.match(source, /function updateActivitySummary\(payload = \{\}\)/);
    assert.match(source, /ai-image-activity-summary/);
    assert.match(source, /activitySummary\.apiTokens/);
    assert.match(source, /activitySummary\.downloads/);
});

test('ai image workbench groups continuations into one history conversation row', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /function getHistoryThreadRows\(\)/);
    assert.match(source, /const rootMap = new Map\(\)/);
    assert.match(source, /const rootTask = getTaskThreadRoot\(task\) \|\| task/);
    assert.match(source, /while \(current\?\.parentTaskId\)/);
    assert.match(source, /getTaskThreadRoot\(task\)\?\.id === rootTask\.id/);
    assert.match(source, /function renderHistoryListPanel\(statusText, historyRows = getHistoryThreadRows\(\)\)/);
    assert.match(source, /filteredRows\.length \? filteredRows\.map\(renderTaskRow\)\.join\(''\)/);
    assert.match(source, /formatCompactNumber\(hasSearch \? filteredRows\.length : totalRows\.length\)/);
    assert.match(source, /ai-image-task-thread-count/);
    assert.match(cssSource, /\.ai-image-task-meta/);
    assert.match(cssSource, /\.ai-image-task-thread-count/);
    assert.match(cssSource, /\.ai-image-task-row\s*\{[\s\S]*transition: color 0\.15s ease, background-color 0\.15s ease, border-color 0\.15s ease, box-shadow 0\.15s ease, transform 0\.15s ease;/);
    assert.match(cssSource, /\.ai-image-task-row:hover,\s*\.ai-image-task-row:focus-visible\s*\{[\s\S]*background-color: rgba\(15, 23, 42, 0\.08\);[\s\S]*transform: translateY\(1px\);/);
    assert.match(cssSource, /html\[data-theme="dark"\] \.ai-image-task-row:hover,\s*html\[data-theme="dark"\] \.ai-image-task-row:focus-visible\s*\{[\s\S]*background-color: rgba\(255, 255, 255, 0\.08\);/);
});

test('ai image workbench filters history conversations by prompt and dialogue content', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /let historySearchQuery = ''/);
    assert.match(source, /function getFilteredHistoryRows\(historyRows = getHistoryThreadRows\(\)\)/);
    assert.match(source, /function compactHistorySearchText\(value = ''\)/);
    assert.match(source, /replace\(\s*\/\[\^\\p\{L\}\\p\{N\}\]\+\/gu,\s*''\s*\)/);
    assert.match(source, /const terms = query\.split\(' '\)\.filter\(Boolean\)/);
    assert.match(source, /compactSearchable\.includes\(compactHistorySearchText\(term\)\)/);
    assert.match(source, /\.\.\.\(row\.tasks \|\| \[\]\)\.map\(getTaskSearchText\)/);
    assert.match(source, /data-aiw-history-search/);
    assert.match(source, /placeholder="搜索"/);
    assert.match(source, /data-aiw-action="clear-history-search"/);
    assert.match(source, /data-aiw-history-results/);
    assert.match(source, /function renderHistoryResultsOnly\(\)/);
    assert.match(source, /renderHistoryResultsOnly\(\)/);
    assert.doesNotMatch(source, /if \(event\.isComposing\) return;/);
    assert.match(cssSource, /\.ai-image-history-search/);
});

test('ai image workbench hides records on sign out but restores the user cache on sign in', () => {
    assert.match(source, /const USER_STORAGE_PREFIX = `\$\{STORAGE_KEY\}:user:`/);
    assert.match(source, /function hasPersistedAuthSession\(\)/);
    assert.match(source, /function getSessionUserId\(session = null\)/);
    assert.match(source, /function getAuthUserStorageKey\(session = null\)/);
    assert.match(source, /function readUserScopedStorage\(session = currentAuthSession \|\| readPersistedSupabaseSession\(\)\)/);
    assert.match(source, /function persistUserScopedState\(\)/);
    assert.match(source, /global\.localStorage\?\.setItem\(key, JSON\.stringify\(serializable\)\)/);
    assert.match(source, /seenTaskIds: normalizeStringList\(Array\.from\(seenTaskIds\), 500\)/);
    assert.match(source, /function restoreUserScopedState\(session = currentAuthSession \|\| readPersistedSupabaseSession\(\)\)/);
    assert.match(source, /seenTaskIds = new Set\(normalizeStringList\(stored\.seenTaskIds \|\| stored\.seen_task_ids, 500\)\)/);
    assert.match(source, /restoreUserScopedState\(persistedSession\)/);
    assert.match(source, /function resetUserScopedWorkbenchData\(\{ renderAfter = true, persistAfter = false \} = \{\}\)/);
    assert.match(source, /state\.tasks = \[\]/);
    assert.match(source, /state\.activeTaskId = ''/);
    assert.match(source, /historySearchQuery = ''/);
    assert.match(source, /remoteRecordsLoaded = false/);
    assert.match(source, /remoteHistoryPrefsLoaded = false/);
    assert.match(source, /resetUserScopedWorkbenchData\(\);\s*return;/);
    assert.match(source, /if \(persistAfter\) persistState\(\)/);
    assert.match(source, /onAuthStateChange\?\.\(\(event, session\) => \{/);
    assert.match(source, /event === 'SIGNED_OUT'[\s\S]*resetUserScopedWorkbenchData\(\{ persistAfter: false \}\)/);
    assert.match(source, /event === 'SIGNED_IN' \|\| event === 'TOKEN_REFRESHED'[\s\S]*restoreUserScopedState\(currentAuthSession\)[\s\S]*render\(\)/);
});

test('ai image history rows show unread and failed states inline', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /const badgeValue = busyCount \|\| ''/);
    assert.match(source, /let seenTaskIds = new Set\(\)/);
    assert.match(source, /function isTaskSeen\(task = \{\}\)/);
    assert.match(source, /function markTaskSeen\(task = \{\}\)/);
    assert.match(source, /function markTaskThreadSeen\(taskOrId = ''\)/);
    assert.match(source, /getTaskThread\(getTaskThreadRoot\(task\) \|\| task\)\.forEach\(markTaskSeen\)/);
    assert.match(source, /const hasUnreadSuccess = threadTasks\.some\(\(item\) => item\?\.status === 'succeeded' && !isTaskSeen\(item\)\)/);
    assert.match(source, /return state\.tasks\.filter\(\(task\) => task\.status === 'succeeded' && !isTaskSeen\(task\)\)/);
    assert.match(source, /markTaskThreadSeen\(taskId\);/);
    assert.match(source, /const isHydratedRemoteHistory = !localTask\.id && remoteTask\.source === 'remote' && remoteTask\.status === 'succeeded'/);
    assert.match(source, /if \(isHydratedRemoteHistory\) markTaskSeen\(remoteTask\)/);
    assert.match(source, /if \(seenTaskIds\.has\(fromId\)\) \{[\s\S]*seenTaskIds\.add\(toId\)/);
    assert.match(source, /const latestTask = row\?\.latestTask \|\| threadTasks\.slice\(\)\.sort\(\(a, b\) => \(b\.createdAt \|\| 0\) - \(a\.createdAt \|\| 0\)\)\[0\] \|\| task;/);
    assert.match(source, /const hasFailedTask = latestTask\?\.status === 'failed'/);
    assert.match(source, /const thumbFallbackIcon = isVideoThumb \? 'fa-film' : \(MODE_META\[thumbTask\.mode\]\?\.icon \|\| MODE_META\[task\.mode\]\?\.icon \|\| 'fa-image'\)/);
    assert.match(source, /const thumbIdentityKey = thumb[\s\S]*getImageIdentityKey/);
    assert.match(source, /const thumbSrc = thumb \? getStableImageUrl\(thumbIdentityKey, thumb\) : ''/);
    assert.match(source, /const thumbStateClass = thumbSrc[\s\S]*hasLoadedImage\(thumbSrc\) \? 'is-image-loaded' : ''[\s\S]*hasFailedImage\(thumbSrc\) \? 'is-image-broken' : ''/);
    assert.match(source, /data-aiw-image-key="\$\{escapeHtml\(thumbIdentityKey\)\}"/);
    assert.match(source, /loading="eager" decoding="async"/);
    assert.match(source, /hasUnreadSuccess \? 'is-unread' : ''/);
    assert.match(source, /hasFailedTask \? 'is-failed-thread' : ''/);
    assert.match(source, /ai-image-task-unread-dot/);
    assert.doesNotMatch(source, /ai-image-task-status/);
    assert.doesNotMatch(cssSource, /\.ai-image-task-status/);
    assert.match(cssSource, /\.ai-image-task-unread-dot::after[\s\S]*animation: aiw-unread-pulse/);
    assert.match(cssSource, /\.ai-image-task-row\.is-failed-thread \.ai-image-task-thumb/);
    const thumbImageRule = getCssRuleBlock(cssSource, '.ai-image-task-thumb img');
    assert.match(thumbImageRule, /object-fit: cover;/);
    assert.match(thumbImageRule, /transform: scale\(1\);/);
    assert.doesNotMatch(thumbImageRule, /opacity: 0;/);
    assert.match(cssSource, /\.ai-image-task-thumb\.is-image-broken img/);
});

test('ai image workbench exposes video generation only from configured video models', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /video:\s*\{\s*label: '生成视频'/);
    assert.match(source, /let runtimeApiVideoModels = \[\]/);
    assert.match(source, /let runtimeAdminVideoModels = \[\]/);
    assert.match(source, /pointsVideoModel: ''/);
    assert.match(source, /apiVideoModel: ''/);
    assert.match(source, /const visibleModes = Object\.entries\(MODE_META\)\.filter\(\(\[id\]\) => id !== 'video' \|\| getActiveModelOptions\('video'\)\.length\)/);
    assert.match(source, /if \(isVideoMode\(mode\)\) return runtimeApiVideoModels;/);
    assert.match(source, /runtimeApiVideoModels = cached\.videoModels\.slice\(\);/);
    assert.match(source, /runtimeAdminVideoModels = videoModels;/);
    assert.match(source, /videoModels:\s*uniqueModelOptions\(videoModels\.map/);
    assert.match(source, /videoModels\s*$/m);
    assert.doesNotMatch(source, /videoModels: filterRuntimeModelsByGroup\(videoModels, 'video'\)/);
    assert.match(source, /output: isTextVisionMode\(task\.mode\) \? 'text' : \(isVideoMode\(task\.mode\) \? 'video' : 'image'\)/);
    assert.match(source, /const activeModelGroup = isTextVisionMode\(inferredMode\) \? 'chat' : \(isVideoMode\(inferredMode\) \? 'video' : \(state\.billingMode === 'api' \? 'image' : ''\)\)/);
    assert.match(source, /apiModelGroup: activeModelGroup/);
    assert.match(source, /quantity: inferredMode === 'reverse' \|\| isVideoMode\(inferredMode\) \? 1 : state\.quantity/);
    assert.match(source, /videoRatio: 'adaptive'/);
    assert.match(source, /videoResolution: '720p'/);
    assert.match(source, /const VIDEO_RATIO_META = Object\.freeze/);
    assert.match(source, /const VIDEO_RESOLUTION_META = Object\.freeze/);
    assert.match(source, /const VIDEO_DURATION_META = Object\.freeze/);
    assert.match(source, /adaptive: \{ label: 'adaptive'/);
    assert.match(source, /'480p': \{ label: '480p'/);
    assert.match(source, /'720p': \{ label: '720p'/);
    assert.match(source, /'1080p': \{ label: '1080p'/);
    assert.match(source, /'4k': \{ label: '4k'/);
    assert.doesNotMatch(source, /'9:21': \{ label: '9:21'/);
    assert.match(source, /function looksLikeVideoModelId\(value = ''\) \{/);
    assert.match(source, /seedance\|jimeng\|dreamina/);
    assert.match(source, /function supportsVideoCameraFixed\(modelId = ''\) \{/);
    assert.match(source, /if \(state\.mode === 'video'\) return 'video';/);
    assert.doesNotMatch(source, /if \(state\.mode === 'video' && getActiveModelOptions\('video'\)\.length\) return 'video';/);
    assert.match(source, /function renderVideoComposerControls/);
    assert.match(source, /field: 'videoRatio'/);
    assert.match(source, /field: 'videoResolution'/);
    assert.match(source, /field: 'videoDuration'/);
    assert.match(source, /field: 'videoAudio'/);
    assert.match(source, /field: 'videoWatermark'/);
    assert.match(source, /field: 'videoCameraFixed'/);
    assert.match(source, /showCameraFixed \? renderCustomSelect/);
    assert.match(source, /videoSettings: isVideoMode\(task\.mode\) \? \{/);
    assert.match(source, /ratio: getActiveRatio\(inferredMode\)/);
    assert.match(source, /resolution: getActiveResolution\(inferredMode\)/);
    assert.doesNotMatch(source, /if \(isVideoMode\(inferredMode\)\) return '';/);
    assert.match(source, /<video src="\$\{escapeHtml\(previewSrc\)\}" controls playsinline preload="metadata"><\/video>/);
    assert.match(source, /isVideoThumb \? '<i class="fas fa-film"><\/i><em>视频<\/em>'/);
    assert.match(source, /isVideoThumb \? 'is-video-thread' : ''/);
    assert.match(cssSource, /\.ai-image-result-media video/);
    assert.match(cssSource, /\.ai-image-result-media\.is-video-result/);
    assert.match(cssSource, /\.ai-image-task-row\.is-video-thread \.ai-image-task-thumb/);
});

test('ai image workbench keeps progress stable across polling and exposes cancel controls', () => {
    assert.match(source, /const progressVisualCache = new Map\(\)/);
    assert.match(source, /let liveElapsedTimer = null/);
    assert.match(source, /function mergeTaskSnapshots\(localTask = \{\}, remoteTask = \{\}\)/);
    assert.match(source, /keepLocalProcessing\s*=\s*localStatus === 'processing' && remoteStatus === 'queued'/);
    assert.match(source, /const keepLocalRuntimeClock = Boolean\(localTask\.id && remoteTask\.id && localTask\.id !== remoteTask\.id && localTask\.clientTaskId\)/);
    assert.match(source, /createdAt: keepLocalRuntimeClock \? \(localTask\.createdAt \|\| remoteTask\.createdAt \|\| 0\)/);
    assert.match(source, /startedAt: keepLocalRuntimeClock \? \(localTask\.startedAt \|\| localTask\.createdAt \|\| remoteTask\.startedAt \|\| remoteTask\.createdAt \|\| 0\)/);
    assert.match(source, /Math\.max\(localProgress, remoteProgress\)/);
    assert.match(source, /function getTasksSnapshotSignature\(tasks = state\.tasks\)/);
    assert.match(source, /const tasksChanged = mergeRemoteTasks\(payload\.tasks \|\| payload\.records \|\| \[\]\)/);
    assert.match(source, /const previewChanged = syncImagePreviewFromTasks\(\)/);
    assert.match(source, /if \(tasksChanged \|\| activityChanged \|\| previewChanged\)/);
    assert.match(source, /function syncRenderedProgressBars\(\)/);
    assert.match(source, /function syncLiveElapsedLabels\(\)/);
    assert.match(source, /function syncLiveElapsedTimer\(\)/);
    assert.match(source, /global\.setInterval\(\(\) => \{/);
    assert.match(source, /syncLiveElapsedLabels\(\);[\s\S]*syncLiveElapsedTimer\(\);[\s\S]*\}, 1000\)/);
    const timerStart = source.indexOf('function syncLiveElapsedTimer()');
    const timerEnd = source.indexOf('function syncRenderedProgressBars()', timerStart);
    assert.notEqual(timerStart, -1, 'syncLiveElapsedTimer should be present');
    assert.notEqual(timerEnd, -1, 'syncLiveElapsedTimer should end before syncRenderedProgressBars');
    assert.doesNotMatch(source.slice(timerStart, timerEnd), /render\(\)/);
    assert.match(source, /getTaskElapsedLabel\(task\)/);
    assert.match(source, /data-aiw-live-status-task-id=/);
    assert.match(source, /data-progress-key=/);
    assert.match(source, /data-aiw-action="\$\{canCancel \? 'cancel-task' : 'generate'\}"/);
    assert.match(source, /function refreshBusyTasksNow\(\)/);
    assert.match(source, /visibilitychange/);
    assert.match(source, /global\.addEventListener\?\.\('focus', refreshBusyTasksNow\)/);
    assert.match(source, /function cancelRemoteTask\(task, clientTaskId = ''\)/);
    assert.match(source, /task\.status = 'cancelled'/);
    assert.doesNotMatch(source, /MOCK_JOB_TICK_MS/);
    assert.doesNotMatch(source, /setInterval\(\(\) => \{[\s\S]*?render\(\);[\s\S]*?\}, 260\)/);
});

test('ai image workbench streams api chat in the current conversation thread', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /const MAX_LOCAL_TASKS = 40/);
    assert.match(source, /tasks: state\.tasks\.slice\(0, MAX_LOCAL_TASKS\)/);
    assert.match(source, /limit: MAX_LOCAL_TASKS/);
    assert.match(source, /async function requestAiImageStream\(route/);
	    assert.match(source, /requestAiImageStream\('chat-stream'/);
	    assert.match(source, /chatReasoningEffort/);
	    assert.match(source, /chatGeminiThinkingLevel/);
	    assert.match(source, /chatClaudeThinkingBudget/);
	    assert.match(source, /chatServiceTier/);
	    assert.match(source, /chatThinkingMode/);
	    assert.match(source, /chatThinkingMode: 'disabled'/);
	    assert.match(source, /chatFastDefaultsVersion: 1/);
	    assert.match(source, /storedFastDefaultsVersion < 1 && state\.chatThinkingMode === 'enabled'/);
	    assert.match(source, /chatImageInput/);
	    assert.match(source, /payload\.supportsImageInput = Boolean\(chatModelOption\.supportsImageInput\);/);
	    assert.match(source, /Gemini 思考等级/);
	    assert.match(source, /payload\.geminiThinkingLevel = geminiThinkingLevel/);
	    assert.match(source, /Claude Extended Thinking/);
	    assert.match(source, /Claude thinking budget_tokens/);
	    assert.match(source, /payload\.claudeThinkingBudget = claudeThinkingBudget/);
	    assert.match(source, /function modelLikelySupportsChatImageInput/);
	    assert.match(source, /function shouldExposeChatImageInput/);
	    assert.match(source, /function renderComposerUploadButton/);
	    assert.match(source, /shouldExposeChatImageInput\(\) \? '上传图片或文档\/PDF' : '上传文档\/PDF'/);
	    assert.match(source, /围绕已上传图片提问，或继续输入你的问题/);
	    assert.match(source, /if \(!state\.apiImageTool && shouldExposeChatImageInput\(\)\) return 'chat'/);
	    assert.doesNotMatch(source, /图片输入：当前模型暂未接通/);
	    assert.doesNotMatch(source, /文档\/PDF：提取文本后随本轮对话发送/);
	    assert.doesNotMatch(source, /图片\/文档\/PDF：暂未接通时不显示入口/);
	    assert.match(source, /const getCapabilityValue = \(id, storedValue\) =>/);
	    assert.match(source, /if \(reasoningEffort\) payload\.reasoningEffort = reasoningEffort/);
	    assert.match(source, /if \(serviceTier\) payload\.serviceTier = serviceTier/);
	    assert.match(source, /if \(thinkingMode\) payload\.thinkingMode = thinkingMode/);
	    assert.match(source, /if \(imageInputMode\) payload\.imageInputMode = imageInputMode/);
	    assert.match(source, /function getActiveChatThreadRoot\(\)/);
    assert.match(source, /function shouldKeepChatStagePinnedToBottom\(\)/);
    assert.match(source, /return getTaskThread\(rootTask\)\.some\(\(task\) => task\.mode === 'chat' && isBusyTask\(task\)\)/);
    assert.match(source, /function getLastChatThreadTask/);
	    assert.match(source, /function getChatThreadMessages/);
	    assert.match(source, /role: 'user',\s*content: task\.prompt/);
	    assert.match(source, /role: 'assistant',\s*content: task\.resultPrompt/);
	    const chatMessagesStart = source.indexOf('function getChatThreadMessages');
	    const chatMessagesEnd = source.indexOf('function getHistoryThreadRows()', chatMessagesStart);
	    assert.notEqual(chatMessagesStart, -1, 'getChatThreadMessages should be present');
	    assert.notEqual(chatMessagesEnd, -1, 'getChatThreadMessages should end before history rows');
	    assert.doesNotMatch(source.slice(chatMessagesStart, chatMessagesEnd), /reasoning_content|reasoningContent/);
	    assert.match(source, /const chatThreadMessages = inferredMode === 'chat' \? getChatThreadMessages\(threadRoot\) : \[\]/);
    assert.match(source, /const submittedAt = Date\.now\(\)/);
    assert.match(source, /createdAt: submittedAt/);
    assert.match(source, /startedAt: inferredMode === 'chat' \? submittedAt : 0/);
    assert.match(source, /parentTaskId: inferredMode === 'chat'\s*\?\s*\(chatParentTask\?\.id \|\| threadRoot\?\.id \|\| ''\)/);
    assert.match(source, /function serverUuidOrEmpty\(value = ''\)/);
    assert.match(source, /parentTaskId: serverUuidOrEmpty\(task\.parentTaskId\)/);
    assert.match(source, /referenceTaskId: serverUuidOrEmpty\(task\.referenceTaskId\)/);
    assert.match(source, /referenceResultId: serverUuidOrEmpty\(task\.referenceResultId\)/);
    assert.match(source, /status: inferredMode === 'chat' \? 'streaming' : 'queued'/);
    assert.match(source, /submitChatStreamTask\(task, threadRoot, chatThreadMessages, draftChatAttachments\)/);
    assert.match(source, /messages/);
	    assert.match(source, /eventName === 'delta'/);
	    assert.match(source, /eventName === 'reasoning'/);
	    assert.match(source, /function shouldRecoverChatStreamError\(error\)/);
	    assert.match(source, /async function recoverRemoteTaskByClientId\(localTask = \{\}\)/);
	    assert.match(source, /async function recoverChatStreamTask\(localTask = \{\}\)/);
	    assert.match(source, /requestAiImage\('task', \{[\s\S]*clientTaskId/);
	    assert.match(source, /const recoveredTask = await recoverChatStreamTask\(task\)/);
	    assert.match(source, /if \(recoveredTask && recoveredTask\.status !== 'failed'\)/);
	    assert.match(source, /if \(isBusyTask\(recoveredTask\)\) scheduleRemoteRecordsPoll\(\);/);
	    assert.match(source, /currentTask\.reasoningText = `\$\{currentTask\.reasoningText \|\| ''\}\$\{delta\}`/);
	    assert.match(source, /reasoning_content: currentTask\.reasoningText/);
	    assert.match(source, /currentTask\.status = 'streaming'/);
    assert.match(source, /if \(shouldKeepChatStagePinnedToBottom\(\)\) \{[\s\S]*?scrollChatStageToBottom\(\);[\s\S]*?\}/);
    assert.match(source, /if \(shouldKeepChatStagePinnedToBottom\(\)\) return;[\s\S]*?if \(!scrollTop && !scrollLeft\) return;/);
    assert.match(source, /const pinToBottom = \(\) => \{[\s\S]*?nextStage\.scrollTop = Math\.max\(0, nextStage\.scrollHeight - nextStage\.clientHeight\);[\s\S]*?\};/);
    assert.match(source, /pinToBottom\(\);[\s\S]*?window\.requestAnimationFrame\(\(\) => \{[\s\S]*?pinToBottom\(\);[\s\S]*?window\.requestAnimationFrame\(pinToBottom\);[\s\S]*?\}\);/);
    assert.match(source, /renderChatThread\(task\)/);
    assert.match(source, /function renderChatTurn\(task, index = 0, \{ showDuration = false \} = \{\}\)/);
    assert.match(source, /if \(task\.status === 'processing' \|\| task\.status === 'streaming'\) \{/);
    assert.match(source, /if \(task\.mode === 'chat'\) return getTaskProgressDetail\(task\)/);
    assert.match(source, /function getTaskTokenStats\(task = \{\}\)/);
    assert.match(source, /function getTaskModelStats\(task = \{\}\)/);
    assert.match(source, /function getTaskModelLabel\(task = \{\}\)/);
    assert.match(source, /function normalizeRuntimeModelLabel\(label = ''\)/);
    assert.ok(source.includes("replace(/^Default\\s*[·•]\\s*/i, '')"));
    assert.match(source, /function normalizeRuntimeProviderLabel\(label = '', fallbackLabel = '当前上游'\)/);
    assert.match(source, /if \(!normalized \|\| \/\^检测到的上游模型\$\/i\.test\(normalized\)\) return fallbackLabel;/);
    assert.match(source, /function getTaskDurationMetaLabel\(task = \{\}\)/);
    assert.match(source, /function getChatTaskQuestionText\(task = \{\}\)/);
	    assert.match(source, /function getChatTaskAnswerText\(task = \{\}\)/);
	    assert.match(source, /function renderChatReasoningBlock\(task = \{\}\)/);
	    assert.match(source, /ai-image-chat-reasoning/);
	    assert.match(source, /思考过程/);
	    assert.match(source, /function getChatModelCapabilities/);
	    assert.match(source, /function renderChatModelCapabilityControls/);
	    assert.match(source, /verifiedKimiThinkingModels: \[\]/);
	    assert.match(source, /verifiedKimiThinkingModels: normalizeStringList\(state\.verifiedKimiThinkingModels, 100\)/);
	    assert.match(source, /state\.verifiedKimiThinkingModels = normalizeStringList\(stored\.verifiedKimiThinkingModels \|\| stored\.verified_kimi_thinking_models, 100\)/);
	    assert.match(source, /function maybeRememberKimiThinkingCapability\(task = \{\}\)/);
	    assert.match(source, /function taskHasReasoningCapability\(task = \{\}\)/);
	    assert.match(source, /reasoning_payloads \?\? diagnostic\.reasoningPayloads/);
	    assert.match(source, /state\.verifiedKimiThinkingModels = normalizeStringList\(\[key, \.\.\.existing\], 100\)/);
	    assert.match(source, /const kimiThinkingVerified = isKimi[\s\S]*isKimiThinkingCapabilityVerified\(\{ model: modelId \}\)[\s\S]*!isKimiThinkingVerificationInFlight\(\{ model: modelId \}\)/);
	    assert.match(source, /\} else if \(isKimi && kimiThinkingVerified\) \{/);
	    assert.doesNotMatch(source, /\} else if \(isKimi\) \{\s*controls\.push\(\{\s*id: 'thinking'/);
	    assert.match(source, /DeepSeek 思考模式/);
	    assert.match(source, /DeepSeek 推理强度/);
	    assert.match(source, /Kimi 思考模式/);
	    assert.match(source, /Qwen 思考模式/);
	    assert.match(source, /xAI 推理强度/);
	    assert.match(source, /OpenAI 推理强度/);
	    assert.match(source, /OpenAI 服务档位/);
	    assert.match(source, /OpenAI 图片输入/);
	    assert.doesNotMatch(source, /当前模型暂无可调选项/);
	    assert.match(source, /label: 'minimal'/);
	    assert.match(source, /label: 'low'/);
	    assert.match(source, /label: 'medium'/);
	    assert.match(source, /label: 'high'/);
	    assert.match(source, /label: '展示思考'/);
	    assert.match(source, /label: '直接回答'/);
	    assert.match(source, /label: '模型默认'/);
	    assert.match(source, /label: '思考'/);
	    assert.match(source, /label: '关闭'/);
	    assert.match(source, /label: '默认'/);
	    assert.match(source, /hint: 'Claude 官方最低思考预算，1024 tokens'/);
	    assert.match(source, /hint: 'Claude 官方思考预算，4096 tokens'/);
	    assert.match(source, /hint: 'Claude 官方较高思考预算，16000 tokens，等待和成本都会增加'/);
	    assert.doesNotMatch(source, /label: '(?:1024|4096|16000)'/);
	    assert.doesNotMatch(source, /shortLabel: '(?:1024|4096|16000)'/);
	    assert.doesNotMatch(source, /label: '[^']*(?:极简|低强度|中等强度|高强度|最高强度|标准思考|扩展思考|开启思考|关闭思考|跟随默认|不推理|自动选择|标准档|弹性档|优先档)[^']*'/);
	    assert.doesNotMatch(source, /label: '[^']*(?:enabled|disabled|unset|true|false|reasoning_effort|service_tier|image_url|thinking\.type|enable_thinking|not set)[^']*'/);
	    assert.doesNotMatch(source, /shortLabel: '[^']*(?:enabled|disabled|unset|true|false)[^']*'/);
	    assert.doesNotMatch(source, /hint: '[^']*(?:true|false)[^']*'/);
	    assert.doesNotMatch(source, /hint: '[^']*(?:thinking\.type|enable_thinking|budget_tokens)[^']*'/);
	    assert.doesNotMatch(source, /选择推理强度|选择响应速度档位|选择思考过程展示|选择图片输入能力/);
    assert.match(source, /if \(task\?\.status === 'failed' \|\| task\?\.status === 'cancelled'\) return getTaskFailureReason\(task\)/);
    assert.match(source, /function getComposerBusyLabel\(task\)/);
    assert.match(source, /function renderChatLoadingDots\(\)/);
    assert.match(source, /return '';[\s\S]*function renderChatLoadingDots/);
    assert.match(source, /const explicitReason = getFriendlyTaskError\(task\.errorMessage \|\| task\.error_message \|\| task\.remoteError \|\| '', '', task\.mode\)/);
    assert.match(source, /if \(task\.mode === 'chat'\) return '这次没有扣积分。可以稍后重试，或切换更稳定的对话模型后再试。'/);
    assert.match(source, /if \(isVideoMode\(task\.mode\)\) return '这次没有扣积分。可以稍后重试，或切换更稳定的视频模型后再试。'/);
    assert.match(source, /function getChatTaskStatsItems\(task = \{\}, \{ showDuration = false \} = \{\}\)/);
    assert.match(source, /function getFriendlyTaskError\(value, fallback = '生成过程遇到异常，请稍后重试。', mode = ''\)/);
    assert.match(source, /if \(normalizedMode === 'chat'\) return '上游对话超时，未扣积分。请稍后重试，或切换更稳定的对话模型后再试。'/);
    assert.match(source, /normalizedMode === 'chat' && \/降低分辨率\|减少参考图\|分辨率、张数\|张数后再试\/i\.test\(raw\)/);
    assert.match(source, /getFriendlyTaskError\(task\.errorMessage \|\| task\.error_message \|\| task\.remoteError \|\| '', '', mode\)/);
    assert.match(source, /getFriendlyTaskError\(error\?\.message \|\| error \|\| '', '', currentTask\.mode\)/);
    assert.match(source, /if \(generatedDateTime\) items\.push\(\{ text: generatedDateTime \}\)/);
    assert.match(source, /durationLabel = showDuration \? getTaskDurationMetaLabel\(task\) : ''/);
    assert.match(source, /生成耗时 \$\{formatDuration\(preferredMs\)\}/);
    assert.match(source, /模型 \$\{modelLabel\}/);
    assert.match(source, /输出 Token \$\{formatTokenCount\(tokenStats\.outputTokens\)\}/);
    assert.match(source, /输入 Token \$\{formatTokenCount\(tokenStats\.inputTokens\)\}/);
    assert.doesNotMatch(source, /请求模型 \$\{modelStats\.requestedModel\}/);
    assert.doesNotMatch(source, /上游模型 \$\{modelStats\.upstreamModel\}/);
    assert.match(source, /tokenUsageRaw/);
    assert.match(source, /input_tokens_details/);
    assert.doesNotMatch(source, /const outputLiveAttrs = isBusyTask\(task\) && !String\(task\?\.resultPrompt \|\| ''\)\.trim\(\)/);
    assert.match(source, /getComposerBusyLabel\(busyTask\)/);
    assert.match(source, /if \(task\?\.mode === 'chat'\) \{/);
    assert.match(source, /return parts\.filter\(Boolean\)\.join\(' · '\)/);
    const chatProgressBranchMatch = source.match(/function getTaskProgressDetail\(task\) \{\s*if \(task\?\.mode === 'chat'\) \{([\s\S]*?)\n        \}\n        if \(task\?\.status === 'queued'\)/);
    assert.ok(chatProgressBranchMatch, 'chat progress detail branch should be present');
    assert.doesNotMatch(chatProgressBranchMatch[1], /getTaskCurrentImageLabel|输出文本/);
    assert.doesNotMatch(source, /return `\$\{getTaskCurrentStepLabel\(task\)\} · 输出文本 · \$\{getTaskElapsedLabel\(task\)\}`/);
    assert.match(source, /const questionText = getChatTaskQuestionText\(task\)/);
    assert.match(source, /data-aiw-action="copy-chat-text"/);
    assert.match(source, /data-copy-kind="question"/);
    assert.match(source, /data-copy-kind="answer"/);
    assert.match(source, /function copyChatText\(element\)/);
    assert.match(source, /if \(action === 'copy-chat-text'\)/);
    assert.match(source, /<div class="ai-image-chat-question">/);
    assert.match(source, /<div class="ai-image-chat-answer-head">/);
    assert.match(source, /chat-loading-dots chat-loading-dots--inline/);
    assert.doesNotMatch(source, /<span>提问<\/span>/);
    assert.doesNotMatch(source, /<span>回答<\/span>/);
    const renderChatTurnStart = source.indexOf('function renderChatTurn(task, index = 0, { showDuration = false } = {})');
    const renderChatTurnEnd = source.indexOf('function buildTaskImageEntries(task = {}, {', renderChatTurnStart);
    assert.notEqual(renderChatTurnStart, -1, 'renderChatTurn should be present');
    assert.notEqual(renderChatTurnEnd, -1, 'renderChatTurn should end before buildTaskImageEntries');
    const renderChatTurnSource = source.slice(renderChatTurnStart, renderChatTurnEnd);
    assert.match(renderChatTurnSource, /renderChatLoadingDots\(\)/);
    assert.doesNotMatch(renderChatTurnSource, /data-aiw-live-status-kind="detail"/);
    const renderChatThreadStart = source.indexOf('function renderChatThread(rootTask)');
    const renderChatThreadEnd = source.indexOf('function renderChatTurn(task, index = 0, { showDuration = false } = {})', renderChatThreadStart);
    assert.notEqual(renderChatThreadStart, -1, 'renderChatThread should be present');
    assert.notEqual(renderChatThreadEnd, -1, 'renderChatThread should end before renderChatTurn');
    const renderChatThreadSource = source.slice(renderChatThreadStart, renderChatThreadEnd);
    assert.match(renderChatThreadSource, /renderChatTurn\(task, index, \{ showDuration: index === chatTasks\.length - 1 \}\)/);
    assert.match(renderChatThreadSource, /ai-image-result-view--image ai-image-result-view--chat/);
    assert.match(renderChatThreadSource, /ai-image-result-grid--thread ai-image-result-grid--chat/);
    assert.doesNotMatch(renderChatThreadSource, /latestTask && isBusyTask/);
    assert.doesNotMatch(renderChatThreadSource, /ai-image-chat-turn--assistant is-streaming/);
    assert.match(cssSource, /\.ai-image-result-view--chat/);
    assert.match(cssSource, /\.ai-image-result-content--chat\s*\{[\s\S]*min-height: calc\(100vh - 220px\)/);
    assert.match(cssSource, /\.ai-image-result-grid--chat\s*\{[\s\S]*min-height: 100%;[\s\S]*align-content: end/);
    assert.match(cssSource, /\.ai-image-result-grid--chat/);
    assert.match(cssSource, /\.ai-image-result-grid--chat \.ai-image-thread-step \+ \.ai-image-thread-step\s*\{[\s\S]*margin-top: 30px/);
    assert.match(cssSource, /\.ai-image-chat-spacer\s*\{[\s\S]*min-height: 120px/);
    const questionRule = getCssRuleBlock(cssSource, '.ai-image-chat-question');
    const answerRule = getCssRuleBlock(cssSource, '.ai-image-chat-output');
    const copyRule = getCssRuleBlock(cssSource, '.ai-image-chat-copy');
    const questionCopyRule = getCssRuleBlock(cssSource, '.ai-image-chat-copy--question');
    const answerCopyRule = getCssRuleBlock(cssSource, '.ai-image-chat-copy--answer');
    assert.match(questionRule, /justify-self: end/);
    assert.match(questionRule, /text-align: right/);
    assert.doesNotMatch(questionRule, /border:/);
    assert.doesNotMatch(questionRule, /background:/);
    assert.doesNotMatch(questionRule, /padding:/);
    assert.match(cssSource, /\.ai-image-chat-question p/);
    assert.match(cssSource, /\.ai-image-chat-answer-head/);
    assert.match(cssSource, /\.ai-image-chat-answer-head \.ai-image-chat-meta/);
    assert.match(cssSource, /\.ai-image-chat-answer-head \.ai-image-chat-meta\s*\{[\s\S]*justify-content: flex-start/);
    assert.match(cssSource, /\.ai-image-chat-meta/);
    assert.match(cssSource, /\.ai-image-chat-meta em/);
    assert.doesNotMatch(answerRule, /border:/);
    assert.doesNotMatch(answerRule, /background:/);
    assert.doesNotMatch(answerRule, /padding:/);
    assert.match(answerRule, /padding-bottom: 40px/);
	    assert.match(cssSource, /\.ai-image-chat-output p/);
	    assert.match(cssSource, /\.ai-image-chat-reasoning/);
	    assert.match(cssSource, /\.ai-image-chat-reasoning-head/);
	    assert.match(cssSource, /\.ai-image-capability-control/);
	    assert.match(cssSource, /\.ai-image-capability-menu/);
    const memoryMenuRule = getCssRuleBlock(cssSource, '.ai-image-memory-menu,\n.ai-image-capability-menu');
    assert.match(memoryMenuRule, /left: 0/);
    assert.match(memoryMenuRule, /right: auto/);
    assert.match(memoryMenuRule, /bottom: calc\(100% \+ 5px\)/);
    assert.match(memoryMenuRule, /box-shadow: 0 4px 12px/);
    assert.doesNotMatch(memoryMenuRule, /right: 0/);
    assert.doesNotMatch(memoryMenuRule, /0 18px 50px/);
    const selectMenuRule = getCssRuleBlock(cssSource, '.ai-image-select-menu');
    const modelSubmenuRule = getCssRuleBlock(cssSource, '.ai-image-model-submenu');
    assert.match(selectMenuRule, /box-shadow: 0 4px 12px/);
    assert.match(modelSubmenuRule, /box-shadow: 0 4px 10px/);
    assert.doesNotMatch(selectMenuRule, /0 18px 48px/);
    assert.doesNotMatch(modelSubmenuRule, /0 12px 30px/);
	    assert.match(cssSource, /\.ai-image-main-composer-input\.has-no-upload/);
	    assert.match(cssSource, /\.ai-image-chat-step\s*\{[\s\S]*gap: 22px/);
    assert.match(cssSource, /\.chat-loading-dots\s*\{[\s\S]*animation/);
    assert.match(cssSource, /@keyframes chat-widget-loading-dots/);
    assert.match(copyRule, /box-shadow: 0 1px 3px rgba\(15, 23, 42, 0\.06\)/);
    assert.match(questionCopyRule, /right: 0/);
    assert.match(questionCopyRule, /bottom: 0/);
    assert.match(questionCopyRule, /opacity: 0/);
    assert.match(answerCopyRule, /position: absolute/);
    assert.match(answerCopyRule, /opacity: 0/);
    assert.match(cssSource, /\.ai-image-chat-actions--answer\s*\{[\s\S]*justify-content: flex-start/);
    assert.match(cssSource, /\.ai-image-chat-question\s*\{[\s\S]*padding-bottom: 40px/);
    assert.match(answerRule, /padding-bottom: 40px/);
    assert.match(cssSource, /\.ai-image-chat-question:hover \.ai-image-chat-copy--question/);
    assert.match(cssSource, /\.ai-image-chat-output:hover \.ai-image-chat-copy--answer/);
    assert.doesNotMatch(cssSource, /\.ai-image-text-result/);
    assert.doesNotMatch(cssSource, /\.ai-image-text-stats/);
    assert.doesNotMatch(cssSource, /\.ai-image-chat-bubble/);
});

test('ai image workbench minimizes without rebuilding loaded image DOM', () => {
    const closeMatch = source.match(/function closeWorkbench\(\) \{[\s\S]*?\n    \}/);
    assert.ok(closeMatch, 'closeWorkbench should be present');
    assert.match(closeMatch[0], /syncOverlayOpenState\(\)/);
    assert.match(closeMatch[0], /renderDock\(\)/);
    assert.doesNotMatch(closeMatch[0], /render\(\)/);
    assert.doesNotMatch(closeMatch[0], /renderOverlay\(\)/);
    assert.match(source, /function collectReusableRenderedImages\(\)/);
    assert.match(source, /function restoreReusableRenderedImages\(reusableImages\)/);
    assert.match(source, /image\.replaceWith\(reusableImage\)/);
    const renderOverlayMatch = source.match(/function renderOverlay\(\) \{[\s\S]*?\n    \}/);
    assert.ok(renderOverlayMatch, 'renderOverlay should be present');
    assert.doesNotMatch(renderOverlayMatch[0], /overlay\.innerHTML = ''/);
});

test('ai image workbench shows accepted state with queue ETA after submit', () => {
    assert.match(source, /queuePosition/);
    assert.match(source, /estimatedWaitSeconds/);
    assert.match(source, /function getTaskQueueEstimateLabel\(task = \{\}\)/);
    assert.match(source, /已受理 ·/);
    assert.match(source, /预计等待 \$\{formatSecondsDuration\(waitSeconds\)\}/);
    assert.match(source, /estimated_wait_seconds/);
    assert.match(source, /queue_eta_seconds/);
    assert.match(source, /function estimateLocalQueueSeconds/);
});

test('ai image pending overlay uses simple live status instead of repeating title', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    const renderInlineMatch = source.match(/function renderInlineTaskPreview\(task, label = '继续生成', \{ showPrompt = true \} = \{\}\) \{[\s\S]*?\n    \}/);
    assert.ok(renderInlineMatch, 'renderInlineTaskPreview should be present');
    assert.match(renderInlineMatch[0], /getTaskCurrentStepLabel\(task\)/);
    assert.match(renderInlineMatch[0], /getTaskCurrentImageLabel\(task\)/);
    assert.match(renderInlineMatch[0], /getTaskElapsedLabel\(task\)/);
    assert.doesNotMatch(renderInlineMatch[0], /getTaskTitle\(task\)/);
    assert.doesNotMatch(renderInlineMatch[0], /getTaskSubtitle\(task\)/);
    assert.match(source, /renderInlineTaskPreview\(task, '生成中', \{ showPrompt: false \}\)/);
    assert.match(source, /getTaskProgressBadge\(task\)/);
    assert.match(cssSource, /\.ai-image-result-pending-meta\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto auto/);
    assert.match(cssSource, /\.ai-image-result-pending-copy\s*\{[\s\S]*display: none/);
});

test('ai image result thread does not repeat original prompt above the first image', () => {
    const startIndex = source.indexOf('function renderTaskResult(task) {');
    const endIndex = source.indexOf('function renderHistoryPanel()', startIndex);
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.notEqual(startIndex, -1, 'renderTaskResult should be present');
    assert.notEqual(endIndex, -1, 'renderTaskResult should end before renderShell');
    const resultSource = source.slice(startIndex, endIndex);
    assert.doesNotMatch(resultSource, /原始提示词/);
    assert.match(resultSource, /基于序列 \$\{entry\.baseSequence\} 续作/);
    assert.match(source, /function renderTaskImageEntry\(entry, index = 0, aspect = '1 \/ 1'\)/);
    assert.match(source, /ai-image-result-sequence/);
    assert.match(cssSource, /\.ai-image-result-grid--single\s*\{[\s\S]*min\(240px, 100%\)/);
    assert.match(cssSource, /\.ai-image-result-grid--thread\s*\{[\s\S]*min\(240px, 100%\)/);
});

test('ai image result track matches composer visible width', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(cssSource, /--aiw-stage-track-width:\s*min\(980px, 100%\)/);
    assert.match(cssSource, /\.ai-image-live-task,\s*\n\.ai-image-result-view\s*\{[\s\S]*width: var\(--aiw-stage-track-width\)/);
    assert.match(cssSource, /\.ai-image-live-task,\s*\n\.ai-image-result-view\s*\{[\s\S]*margin-right: auto;[\s\S]*margin-left: auto;/);
    assert.match(cssSource, /\.ai-image-result-view--image\s*\{[\s\S]*width: var\(--aiw-stage-track-width\)/);
    assert.match(cssSource, /\.ai-image-result-content\s*\{[\s\S]*width: 100%;/);
    assert.match(cssSource, /\.ai-image-main-composer\s*\{[\s\S]*width: var\(--aiw-composer-width\)/);
});

test('ai image multi-result previews stay at skeleton preview size', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(cssSource, /\.ai-image-result-grid\s*\{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(min\(240px, 100%\), min\(240px, 100%\)\)\)/);
    assert.match(cssSource, /\.ai-image-result-grid\s*\{[\s\S]*justify-content: start/);
});

test('ai image workbench avoids duplicate completion and download notices', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.doesNotMatch(source, /高清原图可下载/);
    assert.doesNotMatch(source, /图片已生成完成/);
    assert.doesNotMatch(source, /ai-image-mini-card/);
    assert.doesNotMatch(source, /ai-image-done-pop/);
    assert.doesNotMatch(cssSource, /ai-image-mini-card/);
    assert.doesNotMatch(cssSource, /ai-image-done-pop/);
});

test('ai image workbench shows partial delivered image counts instead of treating quantity as decorative', () => {
    assert.match(source, /metadata\.delivery/);
    assert.match(source, /requested_image_count/);
    assert.match(source, /delivered_image_count/);
    assert.match(source, /deliveredImageCount/);
    assert.match(source, /return completed < total \? `已生成 \$\{completed\}\/\$\{total\} 张` : '已完成';/);
    assert.match(source, /Number\.isFinite\(deliveredCount\) && deliveredCount > 0 \? deliveredCount : imageCount/);
});

test('ai image workbench supports explicit image continuation and extra reference images', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /MAX_REFERENCE_IMAGE_INPUTS = 16/);
    assert.match(source, /continuationImage/);
    assert.match(source, /data-aiw-action="continue-image"/);
    assert.match(source, /ai-image-result-continue/);
    assert.match(source, /data-reference-image=/);
    assert.match(source, /state\.continuationImage = continuationImage;/);
    assert.match(source, /state\.referenceImages = normalizeReferenceList/);
    assert.match(source, /const appendUploadsAsExtraReferences = Boolean\(imageFiles\.length && uploadImageContext\?\.isContinuation && uploadImageContext\?\.image\);/);
    assert.match(source, /if \(appendUploadsAsExtraReferences && !state\.continuationImage\)/);
    assert.match(source, /const promoteFirstUploadToPrimary = !appendUploadsAsExtraReferences && !state\.referenceImage && !state\.referenceImages\.length;/);
    assert.match(source, /data-aiw-reference-preview="\$\{isImplicitContinuation \? 'continuation' : 'reference'\}"/);
    assert.match(source, /function scrollToResultImage\(taskId = '', resultId = '', resultIndex = ''\)/);
    assert.match(source, /target\.scrollIntoView\?\.\(\{ behavior: 'smooth', block: 'center', inline: 'nearest' \}\)/);
    assert.match(source, /function renderPreservingStageScroll\(\)/);
    assert.match(source, /const scrollTop = Number\(stage\?\.scrollTop \|\| 0\)/);
    assert.match(source, /renderPreservingStageScroll\(\);[\s\S]*persistState\(\);[\s\S]*return;/);
    assert.match(source, /openImagePreview\(\{\s*previewSrc:/);
    assert.match(source, /ai-image-main-reference-list/);
    assert.doesNotMatch(source, /基于：/);
    assert.match(cssSource, /\.ai-image-result-continue/);
    assert.match(cssSource, /\.ai-image-main-reference-chip/);
    assert.match(cssSource, /\.ai-image-result-media\.is-located/);
});

test('ai image workbench clears composer references after a referenced task succeeds', () => {
    assert.match(source, /function clearComposerReferences\(\)/);
    assert.match(source, /state\.referenceImage = '';\s*state\.referenceTitle = '';\s*state\.referenceIntent = '';\s*state\.referenceImages = \[\];\s*state\.continuationImage = null;/);
    assert.match(source, /function maybeClearComposerReferencesAfterTaskSuccess\(task = \{\}, previousTask = \{\}\)/);
    assert.match(source, /if \(!task \|\| task\.status !== 'succeeded'\) return false;/);
    assert.match(source, /maybeClearComposerReferencesAfterTaskSuccess\(nextTask, previous \|\| \{\}\)/);
});

test('ai image result prompt only applies fade mask when text is likely overflowing', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /const promptOverflowClass = promptText\.length > 72 \? ' is-overflowing' : '';/);
    assert.match(source, /<div class="ai-image-result-prompt\$\{promptOverflowClass\}">/);
    assert.match(cssSource, /\.ai-image-result-prompt::after\s*\{[\s\S]*display: none;/);
    assert.match(cssSource, /\.ai-image-result-prompt\.is-overflowing::after\s*\{[\s\S]*display: block;/);
    assert.match(cssSource, /\.ai-image-result-prompt-copy\s*\{[\s\S]*border: 0;/);
    assert.match(cssSource, /\.ai-image-result-prompt-copy\s*\{[\s\S]*background: transparent;/);
    assert.match(cssSource, /\.ai-image-result-prompt-copy:hover,\s*\.ai-image-result-prompt-copy:focus-visible,\s*\.ai-image-result-prompt-copy\.is-copied\s*\{[\s\S]*transform: translateY\(-2px\);/);
});

test('ai image workbench keeps cancel action in the composer instead of duplicate preview controls', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /data-aiw-action="\$\{canCancel \? 'cancel-task' : 'generate'\}"/);
    assert.doesNotMatch(source, /ai-image-live-cancel/);
    assert.doesNotMatch(source, /ai-image-inline-cancel/);
    assert.doesNotMatch(cssSource, /ai-image-live-cancel/);
    assert.doesNotMatch(cssSource, /ai-image-inline-cancel/);
});

test('ai image workbench stops inline progress visuals after task failure', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /const isBusy = \['queued', 'processing'\]\.includes\(task\.status\)/);
    assert.match(source, /const isStopped = \['failed', 'cancelled'\]\.includes\(task\.status\)/);
    assert.match(source, /\$\{isBusy \? `<div class="ai-image-result-pending-overlay">/);
    assert.match(source, /<div class="ai-image-progress\$\{progressClass\}"/);
    assert.match(source, /ai-image-failure-dot/);
    assert.match(source, /\(task\.status === 'cancelled' \|\| task\.status === 'failed'\) && isTextVisionTask\(task\)/);
    assert.match(source, /const showStoppedPreview = isStopped && pendingPreviewCount > 0/);
    assert.match(source, /showStoppedPreview \? renderInlineTaskPreview\(task, task\.status === 'cancelled' \? '生成已取消' : '生成失败', \{ showPrompt: false \}\) : ''/);
    assert.match(source, /<button class="ai-image-result-prompt-copy" type="button" data-aiw-action="copy-task-prompt" data-task-id="\$\{escapeHtml\(task\.id\)\}"/);
    assert.doesNotMatch(source, /ai-image-result-pending-overlay--stopped/);
    assert.doesNotMatch(source, /ai-image-inline-failure/);
    assert.match(source, /data-aiw-tip=/);
    assert.match(source, /这次没有扣积分。可以稍后重试，或降低分辨率、减少参考图后再生成。/);
    assert.match(source, /切换更稳定的视频模型后再试/);
    assert.doesNotMatch(source, /task\.remoteError \|\| task\.resultPrompt \|\| '生成过程遇到异常/);
    assert.match(source, /task\.errorCode = String\(error\?\.code \|\| ''\)\.slice\(0, 120\)/);
    assert.match(source, /task\.errorStatus = Number\(error\?\.status \|\| 0\)/);
    assert.match(source, /payload: error\?\.payload \|\| null/);
    assert.match(cssSource, /\.ai-image-result--stopped/);
    assert.doesNotMatch(cssSource, /\.ai-image-inline-failure/);
    assert.match(cssSource, /\.ai-image-failure-dot/);
    assert.match(cssSource, /\.ai-image-inline-stopped-visual\s*\{[\s\S]*color: #e11d48;/);
    assert.match(cssSource, /\.ai-image-result-sequence/);
    assert.match(cssSource, /\.ai-image-result-media:hover \.ai-image-result-sequence/);
    assert.match(cssSource, /\.ai-image-thread-prompt::before/);
    assert.match(cssSource, /\.ai-image-result-grid--thread \.ai-image-thread-step \+ \.ai-image-thread-step/);
});

test('ai image result aspect uses video ratio metadata for video tasks', () => {
    assert.match(source, /const aspect = isVideoMode\(task\.mode\)\s*\?\s*\(VIDEO_RATIO_META\[task\.ratio\]\?\.aspect \|\| '16 \/ 9'\)\s*:\s*\(RATIO_META\[task\.ratio\]\?\.aspect \|\| '1 \/ 1'\)/);
});

test('ai image workbench renders persisted task timing beside result image meta', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /function getTaskTiming\(task = \{\}\)/);
    assert.match(source, /function getTaskTimingLabel\(task = \{\}\)/);
    assert.match(source, /function getTaskTimingSummary\(task = \{\}\)/);
    assert.match(source, /const metadata = task\.metadata && typeof task\.metadata === 'object'/);
    assert.match(source, /const startedAt = task\.startedAt \|\| task\.started_at/);
    assert.match(source, /const updatedAt = task\.updatedAt \|\| task\.updated_at/);
    assert.match(source, /metadata,\n\s*errorCode/);
    assert.match(source, /timing:\s*getTaskTiming\(task\)/);
    assert.match(source, /metadata\.timing/);
    assert.match(source, /const preferredMs = timing\.upstreamMs \|\| timing\.firstTokenMs \|\| timing\.runMs \|\| timing\.totalMs/);
    assert.match(source, /return `生成 \$\{formatDuration\(timing\.upstreamMs\)\}`/);
    assert.match(source, /return `首字 \$\{formatDuration\(timing\.firstTokenMs\)\}`/);
    assert.match(source, /总耗时 \$\{formatDuration\(timing\.totalMs\)\}/);
    assert.match(source, /排队 \$\{formatDuration\(timing\.queueMs\)\}/);
    assert.match(source, /接口等待 \$\{formatDuration\(timing\.upstreamMs\)\}/);
    assert.match(source, /首字 \$\{formatDuration\(timing\.firstTokenMs\)\}/);
    assert.match(source, /上游耗时 \$\{formatDuration\(timing\.upstreamResponseMs\)\}/);
    assert.match(source, /\[getTaskSubtitle\(task\), generatedTime\]/);
    assert.doesNotMatch(source, /const taskTimingLabel = getTaskTimingLabel\(task\)/);
    assert.doesNotMatch(source, /const taskTimingSummary = getTaskTimingSummary\(task\)/);
    assert.doesNotMatch(source, /getTaskTimingSummary\(task\)/);
    assert.match(source, /ai-image-thread-meta/);
    assert.doesNotMatch(source, /ai-image-thread-timing/);
    assert.doesNotMatch(source, /ai-image-progress-caption--summary/);
    assert.match(cssSource, /\.ai-image-thread-meta/);
    assert.doesNotMatch(cssSource, /\.ai-image-thread-timing/);
    assert.doesNotMatch(cssSource, /\.ai-image-progress-caption--summary/);
});

test('ai image workbench shows failed point tasks as not charged', () => {
    assert.match(source, /const chargedPoints = Number\(task\.chargedPoints \?\? task\.charged_points \?\? 0\)/);
    assert.match(source, /\['failed', 'cancelled', 'refunded'\]\.includes\(status\)\s*\?\s*0/);
    assert.match(source, /return '未扣积分'/);
    assert.match(source, /return `已扣 \$\{formatPoints\(task\.chargedPoints \|\| task\.cost \|\| 0\)\} 积分`/);
    assert.match(source, /return `预计 \$\{formatPoints\(task\.estimatedPoints \|\| task\.cost \|\| 0\)\} 积分`/);
});

test('ai image workbench routes reverse prompt through text vision model group', () => {
    assert.match(source, /function isTextVisionMode\(mode = ''\) \{\s*return mode === 'chat' \|\| mode === 'reverse';\s*\}/);
    assert.match(source, /const groupedOptions = getRuntimeModelGroupOptions\(mode\);/);
    assert.match(source, /if \(groupedOptions\.length \|\| getRuntimeModelProvidersForBillingMode\(\)\.length \|\| isRuntimeModelSourceLockedForBillingMode\(\)\) return groupedOptions;/);
    assert.match(source, /const preferredValue = isTextVisionMode\(mode\)/);
    assert.match(source, /state\.billingMode === 'api' \? state\.apiTextModel : state\.pointsTextModel/);
    assert.match(source, /if \(field === 'model'\) \{[\s\S]*const activeModelOptions = getRuntimeModelGroupOptions\(activeMode\);[\s\S]*state\.pointsTextModel = value;/);
    assert.match(source, /output: isTextVisionMode\(task\.mode\) \? 'text' : \(isVideoMode\(task\.mode\) \? 'video' : 'image'\)/);
    assert.match(source, /const activeModelGroup = isTextVisionMode\(inferredMode\) \? 'chat' : \(isVideoMode\(inferredMode\) \? 'video' : \(state\.billingMode === 'api' \? 'image' : ''\)\)/);
    assert.match(source, /apiModelGroup: activeModelGroup/);
    assert.match(source, /isImageVariation \|\| isReversePrompt \? '' : \(promptText \|\| title\)/);
    assert.match(source, /updateRuntimeApiModels\(pricingPayload \|\| \{\}, \{ target: 'admin' \}\)/);
    assert.match(source, /runtimeApiTextModels/);
    assert.match(source, /runtimeApiImageModels/);
});

test('ai image workbench uses admin provider models in points mode dropdowns', () => {
    assert.match(source, /const groupedOptions = getRuntimeModelGroupOptions\(mode\);/);
    assert.match(source, /if \(groupedOptions\.length \|\| getRuntimeModelProvidersForBillingMode\(\)\.length \|\| isRuntimeModelSourceLockedForBillingMode\(\)\) return groupedOptions;/);
    assert.match(source, /if \(group === 'image'\) return looksLikeImageModelId\(id\) \|\| !looksLikeTextModelId\(id\);/);
    assert.doesNotMatch(source, /group === 'image' \? !looksLikeTextModelId\(id\) : !looksLikeImageModelId\(id\)/);
    assert.match(source, /if \(isTextMode\) \{\s*if \(state\.billingMode !== 'api'\) return \[\];[\s\S]*chatModels: runtimeApiTextModels\.length \? runtimeApiTextModels : API_TEXT_MODELS/);
    assert.doesNotMatch(source, /providerId: 'default-image-points'/);
    assert.match(source, /if \(state\.billingMode !== 'api'\) return \[\];/);
    assert.match(source, /state\.billingMode === 'api' \? state\.apiImageModel : state\.model/);
    assert.match(source, /const activeModelOptions = getRuntimeModelGroupOptions\(activeMode\);/);
    assert.match(source, /else if \(activeModelOptions\.some\(\(model\) => model\.id === value\)\) \{[\s\S]*state\.model = value;/);
    assert.match(source, /state\.model = getActiveModelOptions\('text'\)\.some\(\(model\) => model\.id === stored\.model\)/);
});

test('ai image workbench logs submit intent before remote enqueue', () => {
    assert.match(source, /console\.info\('\[AIImageWorkbench\] Submit intent:', \{/);
    assert.match(source, /inferredMode,\s*stateMode: state\.mode,\s*billingMode: state\.billingMode,/);
    assert.match(source, /model: activeModelValue,\s*apiModelGroup: activeModelGroup,\s*clientTaskId: task\.clientTaskId,/);
    assert.match(source, /activeTool,\s*promptLen: prompt\.length,\s*videoModelsCount: getActiveModelOptions\('video'\)\.length,/);
    assert.match(source, /textModelsCount: getActiveModelOptions\('chat'\)\.length,\s*imageModelsCount: getActiveModelOptions\('text'\)\.length,/);
});

test('ai image workbench renders reverse prompt results as a left-aligned image thread', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /function getTaskReferencePreviewImage\(task = \{\}\)/);
    assert.match(source, /const firstReference = normalizeReferenceItem\(task\.referenceImages\?\.\[0\]\)/);
    assert.match(source, /return String\(task\.referenceImage \|\| firstReference\?\.image \|\| ''\)\.trim\(\)/);
    assert.match(source, /if \(task\.mode === 'reverse'\) \{[\s\S]*const referenceImage = getTaskReferencePreviewImage\(task\)/);
    assert.match(source, /ai-image-result-view ai-image-result-view--reverse/);
    assert.match(source, /<figure class="ai-image-reverse-reference">/);
    assert.match(source, /<img src="\$\{escapeHtml\(referenceImage\)\}" alt="\$\{escapeHtml\(referenceTitle\)\}">/);
    assert.match(source, /function formatGeneratedDateTime\(timestamp\)/);
    assert.match(source, /const generatedDateTime = formatGeneratedDateTime\(task\.completedAt \|\| task\.createdAt\)/);
    assert.match(source, /const reverseMeta = \[getTaskSubtitle\(task\), generatedDateTime \? `生成时间 \$\{generatedDateTime\}` : ''\]/);
    assert.match(source, /<span class="ai-image-reverse-meta">\$\{escapeHtml\(reverseMeta\)\}<\/span>/);
    assert.match(source, /<div class="ai-image-reverse-output">[\s\S]*task\.resultPrompt \|\| buildReversePrompt\(task\)/);
    assert.match(cssSource, /\.ai-image-result-view--reverse\s*\{[\s\S]*justify-items: start/);
    assert.match(cssSource, /\.ai-image-reverse-result\s*\{[\s\S]*justify-items: start/);
    assert.match(cssSource, /\.ai-image-reverse-result\s*\{[\s\S]*width: min\(920px, 100%\)/);
    assert.match(cssSource, /\.ai-image-reverse-reference\s*\{[\s\S]*width: min\(240px, 100%\)/);
    assert.match(cssSource, /\.ai-image-reverse-output\s*\{[\s\S]*width: min\(760px, 100%\)/);
    assert.match(cssSource, /\.ai-image-reverse-meta/);
    assert.match(cssSource, /\.ai-image-reverse-output p\s*\{[\s\S]*text-align: left/);
    assert.doesNotMatch(source, /<h2>提示词已反推<\/h2>/);
});

test('ai image workbench applies admin pricing rules to point estimates', () => {
    assert.match(source, /function findRuntimePricingRule\(/);
    assert.match(source, /normalizePricingModel\(model\)/);
    assert.match(source, /ruleModel === '\*' \|\| ruleModel === request\.model/);
    assert.match(source, /return normalizePoints\(\(Number\(matchedRule\.points\) \|\| 0\) \* quantity, 0\)/);
    assert.match(source, /formatPoints\(getCostEstimate\(mode\)\)/);
    assert.match(source, /estimatedPoints: estimatedCost/);
});

test('ai image history supports multi-select delete pin and accent controls', () => {
    const cssSource = fs.readFileSync(path.resolve(__dirname, '../css/ai-image-workbench.css'), 'utf8');
    assert.match(source, /historyPrefs:\s*\{/);
    assert.match(source, /deletedTaskIds:\s*\[\]/);
    assert.match(source, /pinnedTaskIds:\s*\[\]/);
    assert.match(source, /taskAccentById:\s*\{\}/);
    assert.match(source, /const HISTORY_ACCENTS = Object\.freeze/);
    assert.match(source, /let historySelectionMode = false/);
    assert.match(source, /let selectedHistoryTaskIds = new Set\(\)/);
    assert.match(source, /function deleteSelectedHistoryTasks\(\)/);
    assert.match(source, /function pinSelectedHistoryTasks\(\)/);
    assert.match(source, /function unpinSelectedHistoryTasks\(\)/);
    assert.match(source, /function setSelectedHistoryAccent/);
    assert.match(source, /let remoteHistoryPrefsLoaded = false/);
    assert.match(source, /function loadRemoteHistoryPrefs/);
    assert.match(source, /requestAiImage\('task-prefs'/);
    assert.match(source, /function syncHistoryPrefs\(/);
    assert.match(source, /syncHistoryPrefs\('hide', ids\)/);
    assert.match(source, /syncHistoryPrefs\('pin', ids\)/);
    assert.match(source, /syncHistoryPrefs\('unpin', ids\)/);
    assert.match(source, /syncHistoryPrefs\(allowed\.has\(normalizedAccent\) \? 'accent' : 'clear-accent', ids, normalizedAccent\)/);
    assert.match(source, /function migrateHistoryPrefsTaskId/);
    assert.match(source, /syncHistoryPrefsForIds\(migratedIds\)/);
    assert.match(source, /data-aiw-action="toggle-history-selection"/);
    assert.match(source, /data-aiw-action="delete-history-selection"/);
    assert.match(source, /data-aiw-action="pin-history-selection"/);
    assert.match(source, /data-aiw-action="set-history-accent"/);
    assert.match(source, /data-aiw-history-select/);
    assert.match(source, /<span class="ai-image-task-meta">[\s\S]*data-aiw-history-select/);
    assert.doesNotMatch(source, /data-aiw-history-select[\s\S]{0,260}fa-plus/);
    assert.match(source, /function renderPreservingHistoryScroll\(renderFn = render\)/);
    assert.match(source, /const scroller = overlay\?\.querySelector\?\.\('\.ai-image-history-scroll'\)/);
    assert.match(source, /nextScroller\.scrollTop = scrollTop/);
    assert.match(source, /toggleHistorySelection\(taskId\);\s*renderPreservingHistoryScroll\(renderHistoryPanelOnly\);/);
    assert.match(source, /toggleAllHistorySelections\(\);\s*renderPreservingHistoryScroll\(renderHistoryPanelOnly\);/);
    assert.match(source, /setHistorySelectionMode\(!historySelectionMode\);\s*renderPreservingHistoryScroll\(renderHistoryPanelOnly\);/);
    assert.match(source, /isHistoryTaskDeleted\(task\)/);
    assert.match(source, /left\.isPinned !== right\.isPinned/);
    assert.match(cssSource, /\.ai-image-history-bulkbar/);
    assert.match(cssSource, /\.ai-image-task-select/);
    assert.match(cssSource, /\.ai-image-task-select i[\s\S]*opacity: 0/);
    assert.match(cssSource, /\.ai-image-task-row\.is-selected \.ai-image-task-select i[\s\S]*opacity: 1/);
    assert.match(cssSource, /\.ai-image-task-row\.is-selected/);
    assert.match(cssSource, /\.ai-image-task-row\.is-pinned::before/);
    assert.match(cssSource, /\.ai-image-task-row\.has-accent-blue/);
    assert.match(cssSource, /\.ai-image-task-row\.has-accent-green/);
    assert.match(cssSource, /\.ai-image-task-row\.has-accent-gold/);
    assert.match(cssSource, /\.ai-image-task-row\.has-accent-rose/);
});
