const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const ROOT = path.resolve(__dirname, '..');

function readRepoFile(relativePath) {
    return fs.readFileSync(path.join(ROOT, relativePath), 'utf8');
}

const ENGAGEMENT_PUBLIC_PAGES = ['home', 'prompts', 'gongyi', 'shop', 'verify', 'guestbook'];

test('admin studio exposes the customer engagement module shell', () => {
    const html = readRepoFile('admin-studio.html');
    const bootstrap = readRepoFile('js/admin-studio-bootstrap.js');
    const shell = readRepoFile('js/admin-shell.js');
    const adminApi = readRepoFile('api/admin.js');

    assert.match(html, /data-module="engagement"/);
    assert.match(html, /id="module-engagement"/);
    assert.match(html, /js\/admin-engagement\.js\?v=20260505_ENGAGEMENT_RULE_BATCH_AUDIT_1/);
    assert.match(html, /css\/admin-engagement\.css\?v=20260505_ENGAGEMENT_RULE_BATCH_AUDIT_1/);
    assert.match(bootstrap, /engagement:\s*\{\s*label:\s*'客服系统'/);
    assert.match(bootstrap, /modules:\s*\['chat', 'engagement'\]/);
    assert.match(shell, /handleAdminEngagementSiteChange/);
    assert.match(adminApi, /'engagement\/rules': engagementRulesHandler/);
    assert.match(adminApi, /'engagement\/assets': engagementAssetsHandler/);
    assert.match(adminApi, /'engagement\/entry': engagementEntryHandler/);
    assert.match(adminApi, /'engagement\/templates': engagementTemplatesHandler/);
    assert.match(adminApi, /'engagement\/segments': engagementSegmentsHandler/);
    assert.match(adminApi, /'engagement\/scenes': engagementScenesHandler/);
});

test('engagement commercial workspace keeps phase 7 and 8 interaction contracts', () => {
    const engagementJs = readRepoFile('js/admin-engagement.js');
    const engagementCss = readRepoFile('css/admin-engagement.css');
    const engagementRulesHandler = readRepoFile('server/api-handlers/admin/engagement/rules.js');

    ['触达看板', '触达规则', '消息模板', '页面场景', '用户分群', '自动化流程', '客服入口', '效果分析', '素材与样式', '审计记录', '全局设置'].forEach((label) => {
        assert.match(engagementJs, new RegExp(label));
    });
    ['points', 'community', 'commerce', 'account', 'operations'].forEach((capabilityId) => {
        assert.match(engagementJs, new RegExp(`id:\\s*'${capabilityId}'`));
    });
    ENGAGEMENT_PUBLIC_PAGES.forEach((pageId) => {
        assert.match(engagementJs, new RegExp(`'${pageId}'`));
    });

    assert.match(engagementJs, /renderRulesWorkspace\(payload = \{\}\) \{[\s\S]*engagement-rule-workbench[\s\S]*renderRuleComposer\(\)[\s\S]*renderRulePreviewPanel\(\)/);
    assert.match(engagementJs, /renderRuleManagementToolbar\(totalRules\.length, visibleRules\.length\)/);
    assert.match(engagementJs, /copyRuleToDraft\(ruleId = ''\) \{[\s\S]*status:\s*'draft'[\s\S]*enabled:\s*false/);
    assert.match(engagementJs, /handleRuleManagementSelectChange\(input\)\) return;[\s\S]*handleRulePreviewSelectChange\(input\)\) return;[\s\S]*updateRulePreviewFromForm\(\)/);
    assert.match(engagementJs, /data-engagement-preview-action[\s\S]*event\.preventDefault\(\)/);
    assert.match(engagementJs, /data-engagement-rule-search[\s\S]*scheduleRuleSearchRender/);
    assert.match(engagementJs, /#engagementRuleForm input, #engagementRuleForm textarea[\s\S]*updateRulePreviewFromForm/);
    assert.match(engagementJs, /AUDIENCE_SCOPE_OPTIONS/);
    assert.match(engagementJs, /AUDIENCE_SEGMENTS/);
    assert.match(engagementJs, /name:\s*'audience_scope'/);
    assert.match(engagementJs, /audience:\s*\{\s*scope:\s*audienceScope\s*\}/);
    assert.match(engagementJs, /renderSegmentsWorkspace/);
    assert.match(engagementJs, /data-engagement-audience-card/);
    assert.match(engagementJs, /focusAudienceSegment/);
    assert.match(engagementJs, /TRIGGER_TYPE_OPTIONS/);
    assert.match(engagementJs, /AUTOMATION_BLUEPRINTS/);
    assert.match(engagementJs, /name:\s*'trigger_type'/);
    assert.match(engagementJs, /trigger_type:\s*triggerType/);
    assert.match(engagementJs, /renderAutomationWorkspace/);
    assert.match(engagementJs, /getAutomationFlowRows/);
    assert.match(engagementJs, /getAutomationFlowSummary/);
    assert.match(engagementJs, /renderAutomationCommandCenter/);
    assert.match(engagementJs, /renderAutomationFlowMatrix/);
    assert.match(engagementJs, /data-engagement-automation-card/);
    assert.match(engagementJs, /focusAutomationBlueprint/);
    assert.match(engagementJs, /buildAutomationRulePayload/);
    assert.match(engagementJs, /getAutomationBlueprintRules/);
    assert.match(engagementJs, /getAutomationBlueprintStatus/);
    assert.match(engagementJs, /getAutomationBlueprintMetrics/);
    assert.match(engagementJs, /getRuleAnalyticsMetrics/);
    assert.match(engagementJs, /getRuleHealth/);
    assert.match(engagementJs, /RULE_HEALTH_FILTER_OPTIONS/);
    assert.match(engagementJs, /RULE_BATCH_LIMIT/);
    assert.match(engagementJs, /ruleHealthFilter/);
    assert.match(engagementJs, /isRuleVisibleForHealth/);
    assert.match(engagementJs, /getRuleBatchSummary/);
    assert.match(engagementJs, /ruleBatchResult/);
    assert.match(engagementJs, /renderRuleBatchResult/);
    assert.match(engagementJs, /createRuleBatchContext/);
    assert.match(engagementJs, /buildRuleBatchResult/);
    assert.match(engagementJs, /finishRuleBatchAction/);
    assert.match(engagementJs, /batchPauseFilteredRules/);
    assert.match(engagementJs, /batchCopyFilteredRulesToDraft/);
    assert.match(engagementJs, /batchArchiveAttentionRules/);
    assert.match(engagementJs, /batchArchiveHighRiskRules/);
    assert.match(engagementJs, /focusRuleHealthFilter/);
    assert.match(engagementJs, /getAuditBatchGroups/);
    assert.match(engagementJs, /renderAuditBatchGroups/);
    assert.match(engagementJs, /getAuditBatchRollbackLabel/);
    assert.match(engagementJs, /rollbackAuditBatch/);
    assert.match(engagementJs, /batch_previous_status/);
    assert.match(engagementJs, /batch_previous_enabled/);
    assert.match(engagementJs, /rollback_batch_id/);
    assert.match(engagementJs, /getAutomationBlueprintHealth/);
    assert.match(engagementJs, /getMetricRate/);
    assert.match(engagementJs, /focusExistingAutomationRule/);
    assert.match(engagementJs, /toggleAutomationRuleFromBlueprint/);
    assert.match(engagementJs, /copyAutomationRuleFromBlueprint/);
    assert.match(engagementJs, /createAutomationRuleFromBlueprint/);
    assert.match(engagementJs, /createMissingAutomationRules/);
    assert.match(engagementJs, /publishAutomationDraftRules/);
    assert.match(engagementJs, /pauseRunningAutomationRules/);
    assert.match(engagementJs, /data-engagement-action="create-automation-rule"/);
    assert.match(engagementJs, /focus-automation-rule/);
    assert.match(engagementJs, /data-engagement-action="create-missing-automation-rules"/);
    assert.match(engagementJs, /data-engagement-action="publish-automation-drafts"/);
    assert.match(engagementJs, /data-engagement-action="pause-running-automation-rules"/);
    assert.match(engagementJs, /data-engagement-action="toggle-automation-rule"/);
    assert.match(engagementJs, /data-engagement-action="copy-automation-rule"/);
    assert.match(engagementJs, /data-created-count/);
    assert.match(engagementJs, /data-health/);
    assert.match(engagementJs, /编辑规则/);
    assert.match(engagementJs, /payment_failed_recovery/);
    assert.match(engagementJs, /inactive_user_return/);
    assert.match(engagementJs, /renderAnalyticsFunnel/);
    assert.match(engagementJs, /renderAttributionSummary/);
    assert.match(engagementJs, /renderAnalyticsCommandCenter/);
    assert.match(engagementJs, /renderAnalyticsRecommendations/);
    assert.match(engagementJs, /getAnalyticsInsightRows/);
    assert.match(engagementJs, /renderPlacementPerformance/);
    assert.match(engagementJs, /renderActionPerformance/);
    assert.match(engagementJs, /renderSourcePerformance/);
    assert.match(engagementJs, /renderTriggerPerformance/);
    assert.match(engagementJs, /renderAudiencePerformance/);
    assert.match(engagementJs, /renderDevicePerformance/);
    assert.match(engagementJs, /renderFrontendExperienceQA/);
    assert.match(engagementJs, /getDeviceLabel/);
    assert.match(engagementJs, /getThemeLabel/);
    assert.match(engagementJs, /getViewportBucketLabel/);
    assert.match(engagementJs, /experience_quality/);
    assert.match(engagementJs, /theme_breakdown/);
    assert.match(engagementJs, /viewport_breakdown/);
    assert.match(engagementJs, /前台体验验收/);
    assert.match(engagementJs, /renderAuditWorkspace/);
    assert.match(engagementJs, /renderSettingsWorkspace/);
    assert.match(engagementJs, /pauseAllRules/);
    assert.match(engagementJs, /restoreLatestPauseAllRules/);
    assert.match(engagementJs, /getLatestPauseAllAudit/);
    assert.match(engagementJs, /needsGovernancePublishAck/);
    assert.match(engagementJs, /buildGovernancePublishAck/);
    assert.match(engagementJs, /confirmHighRiskPublish/);
    assert.match(engagementJs, /renderGovernanceReviewQueue/);
    assert.match(engagementJs, /renderPermissionGuardrails/);
    assert.match(engagementJs, /governance_acknowledged/);
    assert.match(engagementJs, /governance_ack_reason/);
    assert.match(engagementJs, /data-engagement-action="restore-latest-pause-all-rules"/);
    assert.match(engagementJs, /renderLifecycleDiagnostics/);
    assert.match(engagementJs, /buildLaunchReadiness/);
    assert.match(engagementJs, /renderLaunchReadinessPanel/);
    assert.match(engagementJs, /上线验收/);
    assert.match(engagementJs, /体验闭环诊断/);
    assert.match(engagementJs, /getRuleGovernance/);
    assert.match(engagementJs, /renderRuleGovernanceNotice/);
    assert.match(engagementJs, /engagement-risk-badge/);
    assert.match(engagementJs, /engagement-rule-item__insights/);
    assert.match(engagementJs, /engagement-rule-health/);
    assert.match(engagementJs, /data-rule-health/);
    assert.match(engagementJs, /name:\s*'rule_health_filter'/);
    assert.match(engagementJs, /data-engagement-action="batch-pause-filtered-rules"/);
    assert.match(engagementJs, /data-engagement-action="batch-copy-filtered-rules"/);
    assert.match(engagementJs, /data-engagement-action="batch-archive-attention-rules"/);
    assert.match(engagementJs, /data-engagement-action="batch-archive-high-risk-rules"/);
    assert.match(engagementJs, /data-engagement-action="focus-rule-health-filter"/);
    assert.match(engagementJs, /data-engagement-action="rollback-audit-batch"/);
    assert.match(engagementJs, /engagement-risk-list/);
    assert.match(engagementJs, /DISPLAY_PLACEMENT_OPTIONS/);
    assert.match(engagementJs, /name:\s*'placement'/);
    assert.match(engagementJs, /const placement = normalizeToken\(formData\.get\('placement'\)[\s\S]*\n\s*placement,/);
    assert.match(engagementJs, /data-engagement-preview-placement/);

    assert.match(engagementCss, /\.engagement-rule-workbench\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) minmax\(320px, 380px\)/);
    assert.match(engagementCss, /\.engagement-rule-preview-panel\s*\{[\s\S]*position:\s*sticky/);
    assert.match(engagementCss, /\.engagement-preview-bubble\s*\{[\s\S]*width:\s*fit-content[\s\S]*overflow-wrap:\s*anywhere/);
    assert.match(engagementCss, /\.engagement-preview-bubble\[data-placement="top_banner"\]/);
    assert.match(engagementCss, /\.engagement-preview-bubble\[data-placement="inline_card"\]/);
    assert.match(engagementCss, /\.engagement-preview-bubble\[data-placement="modal"\]/);
    assert.match(engagementCss, /\.engagement-preview-bubble\[data-placement="floating_badge"\]/);
    assert.match(engagementCss, /\.engagement-segment-grid/);
    assert.match(engagementCss, /\.engagement-segment-card/);
    assert.match(engagementCss, /\.engagement-automation-command/);
    assert.match(engagementCss, /\.engagement-automation-command__metrics/);
    assert.match(engagementCss, /\.engagement-automation-command__actions/);
    assert.match(engagementCss, /\.engagement-automation-flow__grid/);
    assert.match(engagementCss, /\.engagement-automation-flow__row/);
    assert.match(engagementCss, /\.engagement-automation-flow__health/);
    assert.match(engagementCss, /\.engagement-automation-grid/);
    assert.match(engagementCss, /\.engagement-automation-card/);
    assert.match(engagementCss, /\.engagement-funnel-grid/);
    assert.match(engagementCss, /\.engagement-attribution-grid/);
    assert.match(engagementCss, /\.engagement-attribution-card/);
    assert.match(engagementCss, /\.engagement-analytics-command/);
    assert.match(engagementCss, /\.engagement-analytics-command__grid/);
    assert.match(engagementCss, /\.engagement-analytics-insight-grid/);
    assert.match(engagementCss, /\.engagement-analytics-insight/);
    assert.match(engagementCss, /\.engagement-governance-grid/);
    assert.match(engagementCss, /\.engagement-governance-actions/);
    assert.match(engagementCss, /\.engagement-review-list/);
    assert.match(engagementCss, /\.engagement-review-row/);
    assert.match(engagementCss, /\.engagement-permission-grid/);
    assert.match(engagementCss, /\.engagement-audit-list/);
    assert.match(engagementCss, /\.engagement-audit-batch-list/);
    assert.match(engagementCss, /\.engagement-audit-batch/);
    assert.match(engagementCss, /\.engagement-audit-batch__head/);
    assert.match(engagementCss, /\.engagement-audit-batch__rows/);
    assert.match(engagementCss, /\.engagement-diagnostics-grid/);
    assert.match(engagementCss, /\.engagement-diagnostic-card/);
    assert.match(engagementCss, /\.engagement-diagnostic-tips/);
    assert.match(engagementCss, /\.engagement-launch-readiness/);
    assert.match(engagementCss, /\.engagement-launch-grid/);
    assert.match(engagementCss, /\.engagement-launch-page-grid/);
    assert.match(engagementCss, /\.engagement-launch-page-row/);
    assert.match(engagementCss, /\.engagement-frontend-qa__grid/);
    assert.match(engagementCss, /\.engagement-frontend-qa-card/);
    assert.match(engagementCss, /\.engagement-frontend-breakdown-row/);
    assert.match(engagementCss, /\.engagement-section\s*\{[\s\S]*min-width:\s*0/);
    assert.match(engagementCss, /\.engagement-workspace-view--entry \.engagement-management-grid,\s*[\s\S]*\.engagement-workspace-view--assets \.engagement-management-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
    assert.match(engagementCss, /\.engagement-governance-notice/);
    assert.match(engagementCss, /\.engagement-rule-actions \.engagement-risk-badge/);
    assert.match(engagementCss, /\.engagement-risk-row/);
    assert.match(engagementCss, /@media \(max-width: 1100px\)[\s\S]*\.engagement-rule-workbench\s*\{[\s\S]*grid-template-columns:\s*1fr/);
});

test('engagement page taxonomy stays aligned across admin, API, and public runtime', () => {
    const engagementJs = readRepoFile('js/admin-engagement.js');
    const adminOverview = readRepoFile('server/api-handlers/admin/engagement/overview.js');
    const adminRules = readRepoFile('server/api-handlers/admin/engagement/rules.js');
    const publicHandler = readRepoFile('server/api-handlers/public/engagement.js');
    const chatWidget = readRepoFile('js/components/ChatWidget.js');

    ENGAGEMENT_PUBLIC_PAGES.forEach((pageId) => {
        assert.match(engagementJs, new RegExp(`'${pageId}'`));
        assert.match(adminOverview, new RegExp(`id:\\s*'${pageId}'`));
        assert.match(adminRules, new RegExp(`'${pageId}'`));
        assert.match(publicHandler, new RegExp(`'${pageId}'`));
    });
    assert.match(chatWidget, /getEngagementPageId\(\) \{/);
    assert.match(chatWidget, /page_id:\s*String\(normalized\.page_id \|\| this\.getEngagementPageId\(\)\)/);
    assert.match(publicHandler, /PAGE_ALIASES/);
    assert.match(publicHandler, /gallery:\s*'prompts'/);
    assert.match(publicHandler, /homepage:\s*'home'/);
});

test('engagement audience targeting is persisted and respected by the public feed', () => {
    const engagementJs = readRepoFile('js/admin-engagement.js');
    const adminOverview = readRepoFile('server/api-handlers/admin/engagement/overview.js');
    const adminRules = readRepoFile('server/api-handlers/admin/engagement/rules.js');
    const adminSegments = readRepoFile('server/api-handlers/admin/engagement/segments.js');
    const publicHandler = readRepoFile('server/api-handlers/public/engagement.js');

    assert.match(adminOverview, /trigger_type,audience,title/);
    assert.match(adminOverview, /audience:\s*row\.audience/);
    assert.match(adminOverview, /engagement_segments/);
    assert.match(adminOverview, /ASSET_STYLE_CONFIG_KEY = 'engagement_asset_style_center'/);
    assert.match(adminOverview, /fetchAssetStyleConfig/);
    assert.match(adminOverview, /asset_center/);
    assert.match(adminOverview, /SUPPORT_ENTRY_CONFIG_KEY = 'engagement_support_entry_center'/);
    assert.match(adminOverview, /fetchSupportEntryConfig/);
    assert.match(adminOverview, /support_entry/);
    assert.match(adminOverview, /TAG_CENTER_CONFIG_KEY = 'engagement_user_tag_center'/);
    assert.match(adminOverview, /fetchTagCenterConfig/);
    assert.match(adminOverview, /normalizeTagAutomation/);
    assert.match(adminOverview, /automation:\s*normalizeTagAutomation/);
    assert.match(adminOverview, /tag_center:\s*tagCenter/);
    assert.match(adminOverview, /PAGE_SCENE_CONFIG_KEY = 'engagement_page_scenes'/);
    assert.match(adminOverview, /fetchPageSceneConfig/);
    assert.match(adminOverview, /mergePageSceneConfig/);
    assert.match(adminOverview, /segments/);
    assert.match(adminOverview, /buildEngagementAnalytics/);
    assert.match(adminOverview, /buildAttributionSummary/);
    assert.match(adminOverview, /placement_breakdown/);
    assert.match(adminOverview, /action_breakdown/);
    assert.match(adminOverview, /source_breakdown/);
    assert.match(adminOverview, /trigger_breakdown/);
    assert.match(adminOverview, /audience_breakdown/);
    assert.match(adminOverview, /device_breakdown/);
    assert.match(adminOverview, /getEventDevice/);
    assert.match(adminOverview, /theme_breakdown/);
    assert.match(adminOverview, /viewport_breakdown/);
    assert.match(adminOverview, /experience_quality/);
    assert.match(adminOverview, /getEventTheme/);
    assert.match(adminOverview, /getEventViewportBucket/);
    assert.match(adminOverview, /getEventExperienceMetrics/);
    assert.match(adminOverview, /getEventAudienceScope/);
    assert.match(adminOverview, /attribution/);
    assert.match(adminOverview, /metadata,created_at/);
    assert.match(adminOverview, /fetchEngagementAuditLogs/);
    assert.match(adminOverview, /buildGovernanceSummary/);
    assert.match(adminOverview, /buildRuleGovernance/);
    assert.match(adminOverview, /review_required_rules/);
    assert.match(adminOverview, /risk_rules/);
    assert.match(adminOverview, /buildLifecycleDiagnostics/);
    assert.match(adminOverview, /audit_logs/);
    assert.match(adminOverview, /governance/);
    assert.match(adminOverview, /diagnostics/);
    assert.match(adminOverview, /running_page_view_rules/);
    assert.match(adminOverview, /\.order\('created_at', \{ ascending: false \}\)/);
    assert.match(adminOverview, /normalizeEmailArray/);
    assert.match(adminOverview, /emails:\s*normalizeEmailArray/);
    assert.match(adminOverview, /tags:\s*normalizeStringArray/);
    assert.match(adminRules, /audience:\s*normalizeMetadata\(body\.audience\)/);
    assert.match(adminRules, /trigger_type,audience,title/);
    assert.match(adminRules, /audience:\s*normalizeMetadata\(row\.audience\)/);
    assert.match(adminRules, /VALID_RULE_PLACEMENTS/);
    assert.match(adminRules, /buildRuleGovernance/);
    assert.match(adminRules, /requires_review/);
    assert.match(adminRules, /governance:\s*buildRuleGovernance\(payload\)/);
    assert.match(adminRules, /assertPublishGovernanceAcknowledged/);
    assert.match(adminRules, /isGovernanceAcknowledged/);
    assert.match(adminRules, /governance_acknowledged/);
    assert.match(adminRules, /governance_review/);
    assert.match(adminRules, /ENGAGEMENT_GOVERNANCE_ACK_REQUIRED/);
    assert.match(adminRules, /statusCode = 428/);
    assert.match(adminRules, /loadRuleById/);
    assert.match(adminRules, /placement:\s*normalizePlacement\(body\.placement \|\| body\.display_type \|\| body\.displayType\)/);
    assert.match(adminRules, /pauseAllRules/);
    assert.match(adminRules, /action === 'pause_all'/);
    assert.match(adminRules, /engagement\.rule\.pause_all/);
    assert.match(adminSegments, /email_targets/);
    assert.match(adminSegments, /tag_targets/);
    assert.match(adminSegments, /emails:\s*normalizeEmailArray/);
    assert.match(adminSegments, /tags:\s*normalizeStringArray/);
    assert.match(adminSegments, /TAG_CENTER_CONFIG_KEY = 'engagement_user_tag_center'/);
    assert.match(adminSegments, /saveTagCenter/);
    assert.match(adminSegments, /normalizeTagAutomation/);
    assert.match(adminSegments, /automation:\s*normalizeTagAutomation/);
    assert.match(adminSegments, /action === 'save_tag'/);
    assert.match(adminSegments, /action === 'delete_tag'/);
    assert.match(publicHandler, /normalizeAudienceScope/);
    assert.match(publicHandler, /normalizeEmailArray/);
    assert.match(publicHandler, /normalizeTagArray/);
    assert.match(publicHandler, /getUserEngagementProfile/);
    assert.match(publicHandler, /fetchUserTags/);
    assert.match(publicHandler, /\.from\('user_tags'\)/);
    assert.match(publicHandler, /fetchAudienceSegments/);
    assert.match(publicHandler, /normalizeTriggerType/);
    assert.match(publicHandler, /VALID_PLACEMENTS/);
    assert.match(publicHandler, /normalizePlacement/);
    assert.match(publicHandler, /placement:\s*normalizePlacement/);
    assert.match(publicHandler, /ruleMatchesAudience/);
    assert.match(publicHandler, /ruleMatchesFeedTrigger/);
    assert.match(publicHandler, /context\.triggerType/);
    assert.match(publicHandler, /context\.triggerType === 'page_view' \? fetchNotificationBubbles/);
    assert.match(publicHandler, /scope === 'visitors'/);
    assert.match(publicHandler, /scope === 'authenticated'/);
    assert.match(publicHandler, /context = \{[\s\S]*userId[\s\S]*userEmail[\s\S]*userTags[\s\S]*audienceSegments/);
    assert.match(publicHandler, /targetEmails/);
    assert.match(publicHandler, /targetTags/);
    assert.match(engagementJs, /name="email_targets"/);
    assert.match(engagementJs, /name="tag_targets"/);
    assert.match(engagementJs, /USER_TAG_SOURCE_OPTIONS/);
    assert.match(engagementJs, /renderUserTagCenter/);
    assert.match(engagementJs, /engagementUserTagForm/);
    assert.match(engagementJs, /data-engagement-action="submit-user-tag"/);
    assert.match(engagementJs, /data-engagement-action="edit-user-tag"/);
    assert.match(engagementJs, /data-engagement-action="delete-user-tag"/);
    assert.match(engagementJs, /engagementTagAutomationForm/);
    assert.match(engagementJs, /data-engagement-action="submit-tag-automation"/);
    assert.match(engagementJs, /data-engagement-action="run-inactive-sweep"/);
    assert.match(engagementJs, /runInactiveUserSweep/);
    assert.match(engagementJs, /collectTagAutomationFormPayload/);
    assert.match(engagementJs, /saveTagAutomationFromForm/);
    assert.match(engagementJs, /high_value_min_paid_amount/);
    assert.match(engagementJs, /payment_failed_min_count/);
    assert.match(engagementJs, /verify_failed_min_count/);
    assert.match(engagementJs, /inactive_user/);
    assert.match(engagementJs, /登录用户/);
    assert.match(engagementJs, /游客/);
    assert.match(engagementJs, /高价值用户/);
});

test('engagement admin form uses custom studio controls instead of native selects and checkboxes', () => {
    const engagementJs = readRepoFile('js/admin-engagement.js');
    const engagementCss = readRepoFile('css/admin-engagement.css');
    const engagementRulesHandler = readRepoFile('server/api-handlers/admin/engagement/rules.js');

    assert.doesNotMatch(engagementJs, /<select\b/);
    assert.doesNotMatch(engagementJs, /type="checkbox"/);
    assert.doesNotMatch(engagementJs, /type="submit"/);
    assert.match(engagementJs, /renderCustomSelect/);
    assert.match(engagementJs, /renderPagePicker/);
    assert.match(engagementJs, /renderCustomSwitch/);
    assert.match(engagementJs, /engagementAdminFetch/);
    assert.match(engagementJs, /authMode:\s*'bearer'/);
    assert.match(engagementJs, /forceBearerToken:\s*true/);
    assert.match(engagementJs, /data-engagement-managed-form/);
    assert.match(engagementJs, /data-engagement-action="submit-rule"/);
    assert.match(engagementJs, /handleEngagementRuleFormSubmit/);
    assert.match(engagementJs, /getRuleFormValidationMessage/);
    assert.match(engagementJs, /setRuleFormError/);
    assert.match(engagementJs, /upsertRuleInPayload/);
    assert.match(engagementJs, /bindEngagementDirectHandlers/);
    assert.match(engagementJs, /submitRuleFromActionElement/);
    assert.match(engagementJs, /submitCurrentRule/);
    assert.match(engagementJs, /pointerup/);
    assert.match(engagementJs, /handleEngagementSubmitIntentEvent/);
    assert.match(engagementJs, /SAVE_LOCK_STALE_MS/);
    assert.match(engagementJs, /__adminEngagementRuntimeVersion/);
    assert.match(engagementJs, /form\.getAttribute\('id'\) !== 'engagementRuleForm'/);
    assert.doesNotMatch(engagementJs, /form\.id !== 'engagementRuleForm'/);
    assert.match(engagementJs, /if \(enabled && status !== 'published'\)/);
    assert.match(engagementRulesHandler, /if \(enabled && status !== 'published'\)/);
    assert.match(engagementRulesHandler, /status = 'published'/);
    assert.match(engagementJs, /stopImmediatePropagation/);
    assert.match(engagementJs, /data-engagement-select-trigger/);
    assert.match(engagementJs, /data-engagement-page-toggle/);
    assert.match(engagementJs, /data-engagement-switch/);
    assert.match(engagementJs, /engagement-hero-grid/);
    assert.match(engagementJs, /WORKSPACE_VIEWS/);
    assert.match(engagementJs, /activeView:\s*'dashboard'/);
    assert.match(engagementJs, /renderWorkspaceNav/);
    assert.match(engagementJs, /renderWorkspaceView/);
    assert.match(engagementJs, /data-engagement-workspace-view/);
    assert.match(engagementJs, /data-engagement-page-card/);
    assert.match(engagementJs, /focusPageScene/);
    assert.match(engagementJs, /getRulesForFocusedPage/);
    assert.match(engagementJs, /clear-page-filter/);
    assert.match(engagementJs, /data-engagement-template-card/);
    assert.match(engagementJs, /applyTemplateToRule/);
    assert.match(engagementJs, /renderTemplateComposer/);
    assert.match(engagementJs, /mutateTemplate/);
    assert.match(engagementJs, /data-engagement-action="submit-template"/);
    assert.match(engagementJs, /data-engagement-action="edit-template"/);
    assert.match(engagementJs, /clear-template-draft/);
    assert.match(engagementJs, /getTemplateDraft/);
    assert.match(engagementJs, /TEMPLATE_PRODUCT_CATEGORIES/);
    assert.match(engagementJs, /TEMPLATE_STARTERS/);
    assert.match(engagementJs, /renderTemplateProductShelf/);
    assert.match(engagementJs, /renderTemplatePerformanceInsights/);
    assert.match(engagementJs, /getTemplateUsageMetrics/);
    assert.match(engagementJs, /getTemplateLinkedRules/);
    assert.match(engagementJs, /createTemplateFromStarter/);
    assert.match(engagementJs, /focusTemplateCategory/);
    assert.match(engagementJs, /source_template_id/);
    assert.match(engagementJs, /data-engagement-action="create-template-starter"/);
    assert.match(engagementJs, /data-engagement-action="focus-template-category"/);
    assert.match(engagementJs, /CAPABILITY_GROUPS/);
    assert.match(engagementJs, /data-engagement-capability-card/);
    assert.match(engagementJs, /focusCapability/);
    assert.match(engagementJs, /clear-capability-filter/);
    assert.match(engagementJs, /getTemplatesForFocusedCapability/);
    assert.match(engagementJs, /RULE_FILTER_STATUS_OPTIONS/);
    assert.match(engagementJs, /RULE_SORT_OPTIONS/);
    assert.match(engagementJs, /data-engagement-rule-search/);
    assert.match(engagementJs, /getManagedRules/);
    assert.match(engagementJs, /copyRuleToDraft/);
    assert.match(engagementJs, /clear-rule-filters/);
    assert.match(engagementJs, /data-engagement-action="copy-rule"/);
    assert.match(engagementJs, /renderRulePreviewPanel/);
    assert.match(engagementJs, /data-engagement-rule-preview-shell/);
    assert.match(engagementJs, /updateRulePreviewFromForm/);
    assert.match(engagementJs, /setPreviewOption/);
    assert.match(engagementJs, /PREVIEW_PAGE_OPTIONS/);
    assert.match(engagementJs, /data-engagement-preview-bubble/);
    assert.match(engagementJs, /AUDIENCE_SCOPE_OPTIONS/);
    assert.match(engagementJs, /getAudienceScopeOptions/);
    assert.match(engagementJs, /renderSegmentComposer/);
    assert.match(engagementJs, /mutateSegment/);
    assert.match(engagementJs, /data-engagement-action="submit-segment"/);
    assert.match(engagementJs, /data-engagement-audience-card/);
    assert.match(engagementJs, /data-engagement-automation-card/);
    assert.match(engagementJs, /focusAutomationBlueprint/);
    assert.match(engagementJs, /createAutomationRuleFromBlueprint/);
    assert.match(engagementJs, /createMissingAutomationRules/);
    assert.match(engagementJs, /publishAutomationDraftRules/);
    assert.match(engagementJs, /pauseRunningAutomationRules/);
    assert.match(engagementJs, /getAutomationBlueprintStatus\(normalizedId\)\.total > 0/);
    assert.match(engagementJs, /return focusExistingAutomationRule\(normalizedId\)/);
    assert.match(engagementJs, /status\.metrics\.views/);
    assert.match(engagementJs, /status\.metrics\.clicks/);
    assert.match(engagementJs, /status\.metrics\.dismisses/);
    assert.match(engagementJs, /status\.health/);
    assert.match(engagementJs, /ruleMetrics\.ctr/);
    assert.match(engagementJs, /ruleMetrics\.dismiss_rate/);
    assert.match(engagementJs, /getRuleHealth\(rule\)/);
    assert.match(engagementJs, /isRuleVisibleForHealth\(rule, state\.ruleHealthFilter\)/);
    assert.match(engagementJs, /needs_attention/);
    assert.match(engagementJs, /paused_or_draft/);
    assert.match(engagementJs, /healthy/);
    assert.match(engagementJs, /buildBatchRuleCopyPayload/);
    assert.match(engagementJs, /confirmRuleBatchAction/);
    assert.match(engagementJs, /batch_id: `rule_batch_/);
    assert.match(engagementJs, /batch_action/);
    assert.match(engagementJs, /finishRuleBatchAction\(buildRuleBatchResult/);
    assert.match(engagementJs, /batch_copy_source_rule_id/);
    assert.match(engagementJs, /summary\.runningRows\.slice\(0, RULE_BATCH_LIMIT\)/);
    assert.match(engagementRulesHandler, /getBatchAuditDetails/);
    assert.match(engagementRulesHandler, /batch_id/);
    assert.match(engagementRulesHandler, /batch_action/);
    assert.match(engagementRulesHandler, /batch_source_rule_id/);
    assert.match(engagementRulesHandler, /batch_previous_status/);
    assert.match(engagementRulesHandler, /batch_previous_enabled/);
    assert.match(engagementRulesHandler, /rollback_batch_id/);
    assert.match(engagementRulesHandler, /\.\.\.getBatchAuditDetails\(body\)/);
    assert.match(engagementJs, /已发布无曝光/);
    assert.match(engagementJs, /关闭率偏高/);
    assert.match(engagementJs, /点击率偏低/);
    assert.match(engagementJs, /缺少跳转链接/);
    assert.match(engagementJs, /表现良好/);
    assert.match(engagementJs, /toggleRule\(ruleId, enabled\)/);
    assert.match(engagementJs, /copyRuleToDraft\(ruleId\)/);
    assert.match(engagementJs, /source_module:\s*'engagement\.automation_blueprint'/);
    assert.match(engagementJs, /automation_blueprint_id/);
    assert.match(engagementJs, /payment_failed_recovery/);
    assert.match(engagementJs, /inactive_user_return/);
    assert.match(engagementJs, /data-engagement-action="pause-all-rules"/);
    assert.match(engagementJs, /renderGovernanceSummary/);
    assert.match(engagementJs, /renderAuditLogs/);
    assert.match(engagementJs, /renderPagePerformance/);
    assert.match(engagementJs, /renderLifecycleDiagnostics/);
    assert.match(engagementJs, /data-status="\$\{escapeHtml\(item\.status \|\| 'idle'\)\}"/);
    assert.match(engagementJs, /state\.activeView = 'rules'/);
    assert.match(engagementJs, /触达看板/);
    assert.match(engagementJs, /用户分群/);
    assert.match(engagementJs, /自动化流程/);
    assert.match(engagementJs, /效果分析/);
    assert.match(engagementJs, /renderSceneComposer/);
    assert.match(engagementJs, /mutateScene/);
    assert.match(engagementJs, /data-engagement-action="submit-scene"/);
    assert.match(engagementJs, /editScene/);
    assert.match(engagementJs, /renderAssetsWorkspace/);
    assert.match(engagementJs, /renderAssetStyleComposer/);
    assert.match(engagementJs, /ASSET_STYLE_PRESET_PACKS/);
    assert.match(engagementJs, /renderAssetStylePresetGallery/);
    assert.match(engagementJs, /applyAssetStylePreset/);
    assert.match(engagementJs, /renderAssetUsageMatrix/);
    assert.match(engagementJs, /getAssetUsageByPage/);
    assert.match(engagementJs, /renderAssetLibrary/);
    assert.match(engagementJs, /mutateAssets/);
    assert.match(engagementJs, /case 'assets':\s*[\s\S]*return `\$\{formatNumber\(assets\.length\)\} 素材`/);
    assert.match(engagementJs, /COLOR_PRESET_OPTIONS/);
    assert.match(engagementJs, /data-engagement-color-value/);
    assert.match(engagementJs, /handleColorPresetSelectChange/);
    assert.match(engagementJs, /data-engagement-action="submit-asset-style"/);
    assert.match(engagementJs, /data-engagement-action="apply-asset-style-preset"/);
    assert.match(engagementJs, /data-engagement-action="submit-asset"/);
    assert.match(engagementJs, /renderEntryWorkspace/);
    assert.match(engagementJs, /renderEntrySettingsComposer/);
    assert.match(engagementJs, /renderEntryContextComposer/);
    assert.match(engagementJs, /renderEntryGuidePanel/);
    assert.match(engagementJs, /mutateEntry/);
    assert.match(engagementJs, /data-engagement-action="submit-entry-settings"/);
    assert.match(engagementJs, /data-engagement-action="submit-entry-context"/);
    assert.match(engagementJs, /data-engagement-support-action-toggle/);

    assert.match(engagementCss, /\.engagement-select__trigger/);
    assert.match(engagementCss, /\.engagement-select__chevron::before/);
    assert.match(engagementCss, /\.engagement-select__chevron\s*\{[\s\S]*font-size:\s*0/);
    assert.match(engagementCss, /\.engagement-page-choice/);
    assert.match(engagementCss, /\.engagement-switch/);
    assert.match(engagementCss, /\.engagement-rule-item__insights/);
    assert.match(engagementCss, /\.engagement-rule-health/);
    assert.match(engagementCss, /\.engagement-rule-health\[data-health="good"\]/);
    assert.match(engagementCss, /\.engagement-rule-health\[data-health="danger"\]/);
    assert.match(engagementCss, /\.engagement-workspace-nav/);
    assert.match(engagementCss, /\.engagement-rule-toolbar__selects\s*\{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(104px, 1fr\)\)/);
    assert.match(engagementCss, /\.engagement-rule-batch-actions/);
    assert.match(engagementCss, /\.engagement-rule-batch-actions button:disabled/);
    assert.match(engagementCss, /\.engagement-rule-batch-result/);
    assert.match(engagementCss, /\.engagement-rule-batch-result\[data-tone="warning"\]/);
    assert.match(engagementCss, /\.engagement-rule-batch-result\[data-tone="error"\]/);
    assert.match(engagementCss, /\.engagement-workspace-nav\s*\{[\s\S]*display:\s*grid[\s\S]*grid-template-columns:\s*repeat\(6, minmax\(0, 1fr\)\)[\s\S]*overflow:\s*visible/);
    assert.match(engagementCss, /\.engagement-workspace-tab__metric\s*\{[\s\S]*background:\s*transparent !important/);
    assert.match(engagementCss, /#module-engagement \.engagement-workspace-nav \.engagement-workspace-tab:is\(:hover, :focus, :focus-visible, :active, \.is-active\) :is\(\.engagement-workspace-tab__label, \.engagement-workspace-tab__metric\)\s*\{[\s\S]*background-color:\s*transparent !important[\s\S]*box-shadow:\s*none !important/);
    assert.match(engagementCss, /\.engagement-workspace-tab\.is-active/);
    assert.match(engagementCss, /\.engagement-workspace-placeholder/);
    assert.match(engagementCss, /\.engagement-tag-center__grid/);
    assert.match(engagementCss, /\.engagement-tag-card/);
    assert.match(engagementCss, /\.engagement-tag-automation/);
    assert.match(engagementCss, /\.engagement-tag-automation__actions/);
    assert.match(engagementCss, /\.engagement-tag-rule-card/);
    assert.match(engagementCss, /\.engagement-page-card__action/);
    assert.match(engagementCss, /\.engagement-page-focus-note/);
    assert.match(engagementCss, /\.engagement-filter-pill/);
    assert.match(engagementCss, /\.engagement-template-item/);
    assert.match(engagementCss, /\.engagement-template-product-shelf/);
    assert.match(engagementCss, /\.engagement-template-category-grid/);
    assert.match(engagementCss, /\.engagement-template-starter-card/);
    assert.match(engagementCss, /\.engagement-template-performance-row/);
    assert.match(engagementCss, /\.engagement-template-card__action/);
    assert.match(engagementCss, /\.engagement-template-apply-note/);
    assert.match(engagementCss, /\.engagement-management-composer/);
    assert.match(engagementCss, /\.engagement-card-action-row/);
    assert.match(engagementCss, /\.engagement-inline-actions/);
    assert.match(engagementCss, /\.engagement-asset-preview/);
    assert.match(engagementCss, /\.engagement-asset-preset-gallery/);
    assert.match(engagementCss, /\.engagement-asset-preset-card/);
    assert.match(engagementCss, /\.engagement-asset-scope-grid/);
    assert.match(engagementCss, /\.engagement-asset-scope-row/);
    assert.match(engagementCss, /\.engagement-color-input\s*\{[\s\S]*grid-template-columns:\s*24px minmax\(120px, 1fr\) minmax\(116px, 140px\)/);
    assert.match(engagementCss, /\.engagement-asset-grid/);
    assert.match(engagementCss, /\.engagement-asset-card/);
    assert.match(engagementCss, /\.engagement-entry-grid/);
    assert.match(engagementCss, /\.engagement-entry-card/);
    assert.match(engagementCss, /\.engagement-entry-guide/);
    assert.match(engagementCss, /\.engagement-support-action-picker/);
    assert.match(engagementCss, /\.engagement-capability-card/);
    assert.match(engagementCss, /\.engagement-capability-card__action/);
    assert.match(engagementCss, /\.engagement-capability-card\.is-focused/);
    assert.match(engagementCss, /\.engagement-rule-toolbar/);
    assert.match(engagementCss, /\.engagement-rule-search/);
    assert.match(engagementCss, /\.engagement-rule-copy-note/);
    assert.match(engagementCss, /\.engagement-rule-workbench/);
    assert.match(engagementCss, /\.engagement-rule-preview-panel/);
    assert.match(engagementCss, /\.engagement-preview-stage/);
    assert.match(engagementCss, /\.engagement-preview-bubble/);
    assert.match(engagementCss, /\[data-preview-device="mobile"\]/);
    assert.match(engagementCss, /\[data-preview-theme="dark"\]/);
    assert.match(engagementCss, /\.engagement-segment-grid/);
    assert.match(engagementCss, /\.engagement-segment-card/);
    assert.match(engagementCss, /\.engagement-automation-command/);
    assert.match(engagementCss, /\.engagement-automation-command__metrics/);
    assert.match(engagementCss, /\.engagement-automation-command__actions/);
    assert.match(engagementCss, /\.engagement-automation-flow__grid/);
    assert.match(engagementCss, /\.engagement-automation-flow__row/);
    assert.match(engagementCss, /\.engagement-automation-grid/);
    assert.match(engagementCss, /\.engagement-automation-card/);
    assert.match(engagementCss, /\.engagement-automation-card\.is-created/);
    assert.match(engagementCss, /\.engagement-automation-card__status/);
    assert.match(engagementCss, /\.engagement-automation-card__metrics/);
    assert.match(engagementCss, /\.engagement-automation-card__health/);
    assert.match(engagementCss, /\.engagement-automation-card__health\[data-health="good"\]/);
    assert.match(engagementCss, /\.engagement-automation-card__health\[data-health="danger"\]/);
    assert.match(engagementCss, /\.engagement-automation-card__quickops/);
    assert.match(engagementCss, /\.engagement-automation-card__actions/);
    assert.match(engagementCss, /\.engagement-automation-card__create/);
    assert.match(engagementCss, /\.engagement-analytics-command/);
    assert.match(engagementCss, /\.engagement-analytics-command__grid/);
    assert.match(engagementCss, /\.engagement-analytics-insight-grid/);
    assert.match(engagementCss, /\.engagement-analytics-insight/);
    assert.match(engagementCss, /\.engagement-frontend-qa__grid/);
    assert.match(engagementCss, /\.engagement-frontend-qa__breakdowns/);
    assert.match(engagementCss, /\.engagement-frontend-breakdown-row/);
    assert.match(engagementCss, /\.engagement-funnel-card/);
    assert.match(engagementCss, /\.engagement-performance-row/);
    assert.match(engagementCss, /\.engagement-audit-row/);
    assert.match(engagementCss, /\.engagement-guardrail-row/);
    assert.match(engagementCss, /\.engagement-diagnostic-card\[data-status="ok"\]/);
    assert.match(engagementCss, /\.engagement-diagnostic-tips article\[data-tone="warning"\]/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-launch-check/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-launch-page-row/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-tag-card/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-template-product-shelf/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-template-starter-card/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-asset-preset-card/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-asset-scope-row/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-asset-card/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-entry-card/);
    assert.match(engagementCss, /\.engagement-form-error/);
    assert.match(engagementCss, /\.engagement-form-error\[data-tone="info"\]/);
    assert.match(engagementCss, /\.engagement-form-error\[data-tone="success"\]/);
    assert.match(engagementCss, /\.engagement-hero-grid/);
    assert.match(engagementCss, /html\[data-theme="dark"\] \.engagement-select__menu/);
    assert.match(engagementCss, /--engagement-studio-blue:\s*var\(--admin-studio-ui-blue, #769dca\)/);
    assert.match(engagementCss, /--engagement-studio-blue-rgb:\s*var\(--admin-studio-ui-blue-rgb, 118, 157, 202\)/);
    assert.match(engagementCss, /background:\s*var\(--engagement-studio-blue\)/);
    assert.match(engagementCss, /rgba\(var\(--engagement-studio-blue-rgb\), 0\.46\)/);
    assert.doesNotMatch(engagementCss, /#2563eb|#1d4ed8|#3b82f6|#bfdbfe|rgba\(30,\s*64,\s*175|rgba\(37,\s*99,\s*235|rgba\(29,\s*78,\s*216|rgba\(59,\s*130,\s*246|rgba\(96,\s*165,\s*250/);
});

test('public robot engagement feed is routed and consumed by ChatWidget', () => {
    const publicApi = readRepoFile('api/public.js');
    const vercelConfig = readRepoFile('vercel.json');
    const chatWidget = readRepoFile('js/components/ChatWidget.js');
    const chatWidgetCss = readRepoFile('css/chat-widget.css');
    const chatWidgetLoader = readRepoFile('js/chat-widget-loader.js');
    const indexHtml = readRepoFile('index.html');
    const promptsHtml = readRepoFile('prompts.html');
    const publicHandler = readRepoFile('server/api-handlers/public/engagement.js');

    assert.match(publicApi, /case 'engagement'/);
    assert.match(vercelConfig, /"source": "\/api\/engagement\/:path\*"/);
    assert.match(chatWidget, /window\.ZaoyoeEngagement/);
    assert.match(chatWidget, /\/api\/engagement\/\$\{encodeURIComponent\(normalizedRoute\)\}/);
    assert.match(chatWidget, /getEngagementApiUrls\('feed', params\)/);
    assert.match(chatWidget, /getEngagementApiUrls\('event'\)/);
    assert.match(chatWidget, /getEngagementApiUrls/);
    assert.match(chatWidget, /\/api\/public\?\$\{fallbackParams\.toString\(\)\}/);
    assert.match(chatWidget, /normalizeEngagementDismissTtlHours/);
    assert.match(chatWidget, /isEngagementItemSessionQuiet/);
    assert.match(chatWidget, /quietEngagementItemForSession/);
    assert.match(chatWidget, /options\.passive === true[\s\S]*quietEngagementItemForSession/);
    assert.match(chatWidget, /this\.initEngagementRuntime\(\);\s*\n\s*\}/);
    assert.doesNotMatch(chatWidget, /initEngagementRuntime\(\) \{\s*if \(this\.isAdmin\) return;/);
    assert.doesNotMatch(chatWidget, /if \(this\.isAdmin \|\| this\.isOpen\) return;/);
    assert.match(chatWidgetLoader, /20260505_CHAT_USER_ACTIVITY_1/);
    assert.match(chatWidgetLoader, /ChatWidget\.js\?v=20260505_CHAT_USER_ACTIVITY_1/);
    assert.match(chatWidgetLoader, /scheduleEngagementRuntimeWarm/);
    assert.match(chatWidgetLoader, /ensureChatWidgetReady\(\{ open: false \}\)/);
    assert.match(indexHtml, /chat-widget-loader\.js\?v=20260505_CHAT_USER_ACTIVITY_1/);
    assert.match(promptsHtml, /chat-widget-loader\.js\?v=20260505_CHAT_USER_ACTIVITY_1/);
    assert.match(chatWidget, /renderEngagementContentHtml/);
    assert.match(chatWidget, /engagement-preview__path-link/);
    assert.match(chatWidget, /ZaoyoeWalletModalBootstrap\?\.open/);
    assert.match(chatWidget, /wallet:\/\/\$\{walletView\}/);
    assert.match(chatWidget, /normalizeEngagementPlacement/);
    assert.match(chatWidget, /applyEngagementAssetStyle/);
    assert.match(chatWidget, /payload\?\.asset_center\?\.style/);
    assert.match(chatWidget, /applyEngagementSupportEntry/);
    assert.match(chatWidget, /buildEngagementSupportBotConfig/);
    assert.match(chatWidget, /payload\?\.support_entry/);
    assert.match(chatWidget, /normalizeEngagementTriggerType/);
    assert.match(chatWidget, /triggerEngagementEvent/);
    assert.match(chatWidget, /scheduleEngagementAutomationTriggers/);
    assert.match(chatWidget, /time_on_page/);
    assert.match(chatWidget, /scroll_depth/);
    assert.match(chatWidget, /data-engagement-trigger/);
    assert.match(chatWidget, /showEngagementItem/);
    assert.match(chatWidget, /showEngagementSurface/);
    assert.match(chatWidget, /getEngagementExperienceContext/);
    assert.match(chatWidget, /getEngagementElementMetrics/);
    assert.match(chatWidget, /measureEngagementElement/);
    assert.match(chatWidget, /aria-live/);
    assert.match(chatWidget, /dataset\.engagementPlacement/);
    assert.match(chatWidget, /metadata:\s*\{[\s\S]*placement:\s*normalized\.placement/);
    assert.match(chatWidget, /device:\s*this\.getEngagementClientDevice\(\)/);
    assert.match(chatWidget, /theme:\s*this\.getEngagementClientTheme\(\)/);
    assert.match(chatWidget, /bubble_width/);
    assert.match(chatWidget, /overflows_viewport/);
    assert.match(chatWidget, /viewport_width/);
    assert.match(chatWidgetCss, /\.engagement-preview__path-link/);
    assert.match(chatWidgetCss, /\.engagement-surface--top_banner/);
    assert.match(chatWidgetCss, /\.engagement-surface--inline_card/);
    assert.match(chatWidgetCss, /\.engagement-surface--modal/);
    assert.match(chatWidgetCss, /\.engagement-surface--floating_badge/);
    assert.match(chatWidgetCss, /--engagement-accent-color/);
    assert.match(chatWidgetCss, /--engagement-accent-color-dark/);
    assert.match(chatWidgetCss, /--engagement-bubble-bg-dark/);
    assert.match(chatWidgetCss, /--engagement-bubble-max-width/);
    assert.match(chatWidgetCss, /max-height:\s*min\(70dvh/);
    assert.match(chatWidgetCss, /data-engagement-density/);
    assert.match(chatWidgetCss, /@media \(max-width: 720px\)/);
    assert.match(publicHandler, /ASSET_STYLE_CONFIG_KEY/);
    assert.match(publicHandler, /fetchAssetStyleConfig/);
    assert.match(publicHandler, /asset_center:\s*assetCenter/);
    assert.match(publicHandler, /SUPPORT_ENTRY_CONFIG_KEY/);
    assert.match(publicHandler, /fetchSupportEntryConfig/);
    assert.match(publicHandler, /support_entry:\s*supportEntry/);
    assert.match(publicHandler, /syncInactiveUserTagForUser/);
    assert.match(publicHandler, /markUserActive/);
    assert.match(publicHandler, /AUDIENCE_SCOPE_TAGS/);
    assert.match(publicHandler, /inactive_user/);
    assert.match(chatWidgetCss, /width:\s*fit-content/);
    assert.match(chatWidgetCss, /min-width:\s*min\(220px,\s*calc\(100vw - 48px\)\)/);
    assert.match(chatWidgetCss, /max-width:\s*min\(var\(--engagement-bubble-max-width, 420px\),\s*calc\(100vw - 48px\)\)/);
    assert.match(chatWidgetCss, /overflow-wrap:\s*anywhere/);
    assert.doesNotMatch(chatWidgetCss, /min-width:\s*min\(360px,\s*calc\(100vw - 48px\)\);\s*max-width:\s*min\(360px/s);
    assert.match(publicHandler, /VALID_PAGES.*home.*prompts.*gongyi.*shop.*verify.*guestbook/s);
    assert.match(publicHandler, /normalizeDismissTtlHours/);
    assert.match(publicHandler, /\.eq\('enabled', true\)/);
    assert.match(publicHandler, /\.eq\('status', 'published'\)/);
    assert.match(publicHandler, /'reply-notify': replyNotifyHandler/);
});

test('engagement migration creates commercial robot touchpoint primitives', () => {
    const migration = readRepoFile('supabase/migrations/20260504_engagement_robot_touchpoints.sql');
    const activityMigration = readRepoFile('supabase/migrations/20260505_engagement_user_activity.sql');

    assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.engagement_templates/);
    assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.engagement_segments/);
    assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.engagement_rules/);
    assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.engagement_events/);
    assert.match(migration, /ADD COLUMN IF NOT EXISTS action_url TEXT/);
    assert.match(migration, /'points_insufficient'/);
    assert.match(migration, /'comment_replied'/);
    assert.match(migration, /'coupon_available'/);
    assert.match(migration, /'permission_changed'/);
    assert.match(activityMigration, /CREATE TABLE IF NOT EXISTS public\.engagement_user_activity/);
    assert.match(activityMigration, /last_active_at TIMESTAMPTZ/);
    assert.match(activityMigration, /idx_engagement_user_activity_last_active/);
    assert.match(activityMigration, /trg_engagement_user_activity_updated_at/);
});

test('business notifications carry robot bubble routing metadata', () => {
    const notifications = readRepoFile('api/_lib/admin-notifications.js');
    const usersManage = readRepoFile('server/api-handlers/admin/users/manage.js');
    const discountsAssets = readRepoFile('server/api-handlers/admin/discounts/assets.js');
    const shopPublic = readRepoFile('server/api-handlers/public/shop.js');

    assert.match(notifications, /action_url/);
    assert.match(notifications, /source_event_id/);
    assert.match(usersManage, /category:\s*'points_adjusted'/);
    assert.match(usersManage, /category:\s*'permission_changed'/);
    assert.match(discountsAssets, /event_type:\s*'coupon_available'/);
    assert.match(discountsAssets, /action_path_label:\s*'我的钱包 > 卡券'/);
    assert.match(discountsAssets, /wallet_view:\s*'cards'/);
    assert.match(shopPublic, /event_type:\s*'coupon_available'/);
    assert.match(shopPublic, /action_path_url:\s*'wallet:\/\/cards'/);
    assert.match(shopPublic, /wallet_view:\s*'cards'/);
});

test('community replies create robot-readable personal notifications', () => {
    const publicHandler = readRepoFile('server/api-handlers/public/engagement.js');
    const prompts = readRepoFile('prompts-poetry.js');
    const guestbook = readRepoFile('supabase-guestbook-functions.js');
    const promptsHtml = readRepoFile('prompts.html');
    const guestbookHtml = readRepoFile('guestbook.html');

    assert.match(publicHandler, /source === 'prompt_comment'/);
    assert.match(publicHandler, /guestbook_message_reply:\$\{commentId\}/);
    assert.match(publicHandler, /guestbook_comment_reply:\$\{commentId\}/);
    assert.match(publicHandler, /category:\s*eventType/);
    assert.match(publicHandler, /page_id:\s*'guestbook'/);
    assert.match(publicHandler, /page_id:\s*'prompts'/);
    assert.match(publicHandler, /notifyUsers\(supabase/);

    assert.match(prompts, /\/api\/engagement\/reply-notify/);
    assert.match(prompts, /source:\s*'prompt_comment'/);
    assert.match(publicHandler, /comments:\s*'1'/);

    assert.match(guestbook, /\/api\/engagement\/reply-notify/);
    assert.match(guestbook, /source:\s*'guestbook_comment'/);
    assert.match(guestbook, /parentCommentId/);

    assert.match(promptsHtml, /20260504_ENGAGEMENT_REPLY_NOTIFY_1/);
    assert.match(guestbookHtml, /20260504_ENGAGEMENT_REPLY_NOTIFY_1/);
});

test('shop discount assets can surface as robot engagement bubbles', () => {
    const shopClient = readRepoFile('js/shop-client.js');
    const shopHtml = readRepoFile('shop.html');
    const publicShopHandler = readRepoFile('server/api-handlers/public/shop.js');

    assert.match(publicShopHandler, /'available-discounts': async function availableDiscountsHandler/);
    assert.match(shopClient, /maybeShowShopDiscountEngagement/);
    assert.match(shopClient, /selectShopDiscountEngagementOffer/);
    assert.match(shopClient, /window\.ZaoyoeEngagement\?\.show/);
    assert.match(shopClient, /window\.ZaoyoeEngagement\?\.trigger\?\.\('points_insufficient'/);
    assert.match(shopClient, /event_type:\s*offer\.type === 'claimable' \? 'coupon_available' : 'product_discount_available'/);
    assert.match(shopClient, /shop_product_discount_assets/);
    assert.match(shopClient, /\/shop\.html\?productId=/);
    assert.match(shopClient, /this\.maybeShowShopDiscountEngagement\(\)/);
    assert.match(shopHtml, /20260504_SHOP_DISCOUNT_ENGAGEMENT_1/);
});

test('business terminal events automatically maintain engagement user tags', () => {
    const userTags = readRepoFile('api/_lib/user-tags.js');
    const paymentOrders = readRepoFile('api/_lib/payments/orders.js');
    const zpayWebhook = readRepoFile('api/_lib/payments/zpay-webhook.js');
    const shopPublic = readRepoFile('server/api-handlers/public/shop.js');
    const verifyRuntime = readRepoFile('server/api-handlers/_verify-job-runtime.js');
    const commerceSuccess = readRepoFile('api/_lib/commerce-success-alerts.js');
    const serverRuntime = readRepoFile('server/index.js');

    assert.match(userTags, /PAID_USER:\s*'paid_user'/);
    assert.match(userTags, /PAYMENT_FAILED:\s*'payment_failed'/);
    assert.match(userTags, /VERIFY_FAILED:\s*'verify_failed'/);
    assert.match(userTags, /INACTIVE_USER:\s*'inactive_user'/);
    assert.match(userTags, /DEFAULT_USER_TAG_AUTOMATION/);
    assert.match(userTags, /loadUserTagAutomationConfig/);
    assert.match(userTags, /normalizeUserTagAutomationConfig/);
    assert.match(userTags, /maybeMarkHighValueUser/);
    assert.match(userTags, /countRecentPaymentFailures/);
    assert.match(userTags, /countRecentVerifyFailures/);
    assert.match(userTags, /recordUserActivity/);
    assert.match(userTags, /markUserActive/);
    assert.match(userTags, /syncInactiveUserTagForUser/);
    assert.match(userTags, /sweepInactiveUserTags/);
    assert.match(userTags, /getUserLastActivityAt/);
    assert.match(userTags, /high_value_threshold_not_met/);
    assert.match(userTags, /payment_failed_threshold_not_met/);
    assert.match(userTags, /verify_failed_threshold_not_met/);
    assert.match(userTags, /inactive_threshold_not_met/);
    assert.match(userTags, /upsert\(rows,\s*\{\s*onConflict:\s*'user_id,tag'/);

    assert.match(paymentOrders, /syncPaymentStatusUserTags/);
    assert.match(paymentOrders, /sourceModule:\s*'payments\.create'/);
    assert.match(paymentOrders, /sourceModule:\s*'payments\.mock'/);
    assert.match(zpayWebhook, /sourceModule:\s*'payments\.zpay_webhook'/);
    assert.match(shopPublic, /markUserAsPaid/);
    assert.match(shopPublic, /sourceModule:\s*'shop\.purchase'/);
    assert.match(verifyRuntime, /markVerifyFailed/);
    assert.match(verifyRuntime, /AUTO_USER_TAGS\.VERIFY_FAILED/);
    assert.match(commerceSuccess, /markUsersAsPaid/);
    assert.match(commerceSuccess, /\.in\('status', \['paid', 'redeemed'\]\)/);
    assert.match(serverRuntime, /sourceModule:\s*'payments\.hupijiao_webhook'/);
    assert.match(serverRuntime, /sourceModule:\s*'payments\.afdian_webhook'/);
});
