const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..');
const extensionRoot = path.join(repoRoot, 'integrations', 'meigen-gallery-collector');

function readExtensionFile(fileName) {
    return fs.readFileSync(path.join(extensionRoot, fileName), 'utf8');
}

test('Meigen collector Chrome extension declares the expected surfaces', () => {
    const manifest = JSON.parse(readExtensionFile('manifest.json'));

    assert.equal(manifest.manifest_version, 3);
    assert.equal(manifest.action.default_popup, 'popup.html');
    assert.equal(manifest.background.service_worker, 'background.js');
    assert.deepEqual(manifest.content_scripts[0].js, [
        'clipboard-bridge.js'
    ]);
    assert.equal(manifest.content_scripts[0].world, 'MAIN');
    assert.equal(manifest.content_scripts[0].run_at, 'document_start');
    assert.deepEqual(manifest.content_scripts[1].js, [
        'content-prelude.js',
        'meigen-gallery-collector.user.js',
        'content.js'
    ]);
    assert.deepEqual(manifest.content_scripts[2].js, [
        'admin-bridge.js'
    ]);
    assert.equal(manifest.permissions.includes('downloads'), true);
    assert.equal(manifest.permissions.includes('scripting'), true);
    assert.equal(manifest.permissions.includes('storage'), true);
    assert.equal(manifest.permissions.includes('clipboardRead'), true);
    assert.equal(manifest.permissions.includes('tabs'), true);
    assert.equal(manifest.host_permissions.includes('https://www.meigen.ai/*'), true);
    assert.equal(manifest.version, '0.1.23');
    const adminBridgeScript = manifest.content_scripts.find((entry) => entry.js.includes('admin-bridge.js'));
    assert.equal(adminBridgeScript.matches.every((pattern) => pattern.includes('/admin-studio')), true);
    assert.equal(manifest.host_permissions.includes('https://www.fatherkey.com/*'), true);
    assert.equal(manifest.host_permissions.includes('http://localhost:*/*'), true);
});

test('Meigen collector extension can collect, download, and stage import payloads', () => {
    const prelude = readExtensionFile('content-prelude.js');
    const content = readExtensionFile('content.js');
    const background = readExtensionFile('background.js');
    const popup = readExtensionFile('popup.js');
    const html = readExtensionFile('popup.html');
    const collector = readExtensionFile('meigen-gallery-collector.user.js');
    const bridge = readExtensionFile('clipboard-bridge.js');
    const adminBridge = readExtensionFile('admin-bridge.js');

    assert.match(prelude, /__FatherKeyMeigenCollectorNoAutoRun\s*=\s*true/);
    assert.match(content, /FATHER_KEY_MEIGEN_COLLECT/);
    assert.match(content, /FATHER_KEY_MEIGEN_DETAIL_PAUSE/);
    assert.match(content, /FATHER_KEY_MEIGEN_DETAIL_RESUME/);
    assert.match(content, /FATHER_KEY_MEIGEN_DETAIL_STATUS/);
    assert.match(content, /FATHER_KEY_MEIGEN_SCROLL_COLLECT/);
    assert.match(content, /FATHER_KEY_MEIGEN_SCROLL_STOP/);
    assert.match(content, /FATHER_KEY_MEIGEN_SCROLL_STATUS/);
    assert.match(content, /FATHER_KEY_MEIGEN_PAGE_BATCH_COLLECT/);
    assert.match(content, /FATHER_KEY_MEIGEN_PAGE_BATCH_STOP/);
    assert.match(content, /FATHER_KEY_MEIGEN_PAGE_BATCH_STATUS/);
    assert.match(content, /FATHER_KEY_MEIGEN_DIAGNOSTICS/);
    assert.match(content, /FATHER_KEY_MEIGEN_SESSION_STATE/);
    assert.match(content, /FATHER_KEY_STAGE_IMPORT/);
    assert.match(content, /function queueStreamStage/);
    assert.match(content, /\{ flush = false, force = false \}/);
    assert.match(content, /!force && !isStreamItemRevisionImproved/);
    assert.match(content, /queueStreamStage\(mergedItems, streamMessage, \{ flush: true, force: true \}\)/);
    assert.match(content, /function scrollAndWaitForGalleryBatch/);
    assert.match(content, /function stageStreamItemsToTarget/);
    assert.match(content, /Math\.max\(0, maxItems - streamStageState\.stagedCount\)/);
    assert.match(content, /stageStreamItemsToTarget\(duplicateCheck\.uniqueItems, message, maxItems, \{ pendingDetail: true \}\)/);
    assert.match(content, /stream_pending_detail: true/);
    assert.match(content, /function getMeigenIdentityConflictReason/);
    assert.match(content, /function isStreamItemRevisionImproved/);
    assert.match(content, /sentRevisions:\s*new Map\(\)/);
    assert.match(content, /streamStageState\.stagedCount >= maxItems/);
    assert.match(content, /bufferedItems\.length < 3/);
    assert.match(content, /batchId:\s*streamStageState\.batchId/);
    assert.match(content, /attemptedCount:\s*streamStageState\.attemptedCount/);
    assert.match(content, /stagedCount:\s*streamStageState\.stagedCount/);
    assert.match(content, /skippedDuplicateCount:\s*streamStageState\.skippedDuplicateCount/);
    assert.match(content, /rejectedCount:\s*streamStageState\.rejectedCount/);
    assert.match(content, /result\.stagedCount \?\? result\.items\?\.length/);
    assert.match(content, /await streamStageState\.promise/);
    assert.match(content, /FatherKeyMeigenCollector/);
    assert.match(content, /DETAIL_FETCH_DELAY_MS\s*=\s*900/);
    assert.match(content, /SCROLL_COLLECT_DELAY_MS\s*=\s*1200/);
    assert.match(content, /PAGE_BATCH_DELAY_MS\s*=\s*1500/);
    assert.match(content, /NEXT_PAGE_TEXT_PATTERN/);
    assert.match(content, /runScrollCollect/);
    assert.match(content, /runPageBatchCollect/);
    assert.match(content, /findNextPageTarget/);
    assert.match(content, /fetchDetailItems/);
    assert.match(content, /function getLatestPayload/);
    assert.match(content, /function revealHoverControls/);
    assert.match(content, /function getHoverChildTargets/);
    assert.match(content, /function cacheHoverAuthorIdentity/);
    assert.match(content, /__FatherKeyMeigenHoverAuthors/);
    assert.match(content, /logDiagnostic\('hover-author'/);
    assert.match(content, /author_identity_source:\s*item\.author_identity_source/);
    assert.match(content, /function collectDetailItemsFromFrame/);
    assert.match(content, /DETAIL_FRAME_MIN_SETTLE_MS\s*=\s*2500/);
    assert.match(content, /DETAIL_FRAME_STABLE_ROUNDS\s*=\s*3/);
    assert.match(content, /fetchedExpectedCount > 0/);
    assert.match(content, /width:min\(1024px, 100vw\)/);
    assert.match(content, /function collectDetailItemsFromCurrentCard/);
    assert.match(content, /SESSION_STORAGE_KEY/);
    assert.match(content, /chrome\.storage\.session/);
    assert.match(content, /detail-current-navigation-guarded/);
    assert.match(content, /preventNavigation:\s*true/);
    assert.match(content, /event\.preventDefault\(\)/);
    assert.match(content, /history\.replaceState/);
    assert.doesNotMatch(content, /element\.dispatchEvent\(new MouseEvent\('click', eventOptions\)\);\s*if \(typeof element\.click/);
    assert.match(background, /TRUSTED_AND_UNTRUSTED_CONTEXTS/);
    assert.match(background, /batch_id:\s*String\(batchId/);
    assert.match(html, /id="collectBtn"[^>]*>全自动采集并入队</);
    assert.match(popup, /async function runFullyAutomaticCollectionTask/);
    assert.match(popup, /type: MESSAGE_AUTOMATION_START/);
    assert.match(popup, /function startAutomationPolling/);
    assert.match(content, /async function runFullyAutomaticCollection/);
    assert.match(content, /function startFullyAutomaticCollection/);
    assert.match(content, /message\?\.type === MESSAGE_AUTOMATION_START/);
    assert.match(content, /message\?\.type === MESSAGE_AUTOMATION_STATUS/);
    assert.match(popup, /streamToQueue:\s*true/);
    assert.match(popup, /state\.streamedBatchId/);
    assert.match(popup, /已入队 \$\{status\.staged\}\/\$\{status\.target/);
    assert.match(popup, /重复 \$\{status\.duplicates\}/);
    assert.match(popup, /关闭插件不影响后台任务/);
    assert.match(html, /id="automationProgress"/);
    assert.match(html, /id="automationProgressBar"/);
    assert.match(popup, /void runFullyAutomaticCollectionTask\(\)/);
    assert.match(content, /function urlsLooselyMatch/);
    assert.match(content, /function currentDetailUrlMatchesTarget/);
    assert.match(content, /function filterStructuredEntriesForCurrentContext/);
    assert.match(content, /function removeResolvedDetailFailures/);
    assert.match(content, /未定位到当前作品卡片/);
    assert.match(content, /详情已打开，但还没有读到提示词/);
    assert.match(content, /function needsInteractiveDetail/);
    assert.match(content, /baseItems\.filter\(\(item\) => needsInteractiveDetail/);
    assert.match(content, /requireFavoriteCount: hasFavoriteRange/);
    assert.match(content, /function hasBetterDetailThanBase/);
    assert.match(content, /detail-current-not-ready/);
    assert.match(content, /const hasReliableDetail = hasUsefulDetailData/);
    assert.match(content, /const hasUsefulPromptDetail = hasUsefulDetailData/);
    assert.match(content, /detailItems\.push\(\.\.\.currentDetailItems\);/);
    assert.match(content, /reliable: hasReliableDetail/);
    assert.match(content, /function mergeDetailItemsIntoBase/);
    assert.match(content, /function mergeItemsPreservingSourceIds/);
    assert.match(content, /function applyDetailItemToTarget/);
    assert.match(content, /detailCountIsAuthoritative && Number\(detailItem\.favorite_count/);
    assert.match(content, /function chooseBetterAuthorName/);
    assert.match(content, /const shouldPreferCurrentExpectedCount = currentExpectedCount > detailExpectedCount/);
    assert.match(content, /function selectBestDetailItemsForTarget/);
    assert.match(content, /function scoreDetailCandidate/);
    assert.match(content, /function getDetailExpectedCountFromDocument/);
    assert.match(content, /function getTweetStatusIdFromImageUrl/);
    assert.match(content, /function getTargetStatusIds/);
    assert.match(content, /hasConflictingImageStatus/);
    assert.match(content, /function isDetailImageCountAuthoritative/);
    assert.match(content, /function isDetailExpectedCountAuthoritative/);
    assert.match(content, /function hasExpectedDetailImages/);
    assert.match(content, /detail_expected_count_authoritative/);
    assert.match(content, /detail_image_count_authoritative/);
    assert.match(content, /detail-merge-applied/);
    assert.match(content, /detailCountAuthoritative/);
    assert.match(content, /detail-identity-merge-finish/);
    assert.match(content, /const targetById = detailId/);
    assert.match(content, /const target = targetById \|\| mergedItems\.find/);
    assert.match(content, /return preservedItems/);
    assert.match(content, /DETAIL_FRAME_TIMEOUT_MS/);
    assert.match(content, /HOVER_REVEAL_DELAY_MS/);
    assert.match(content, /function normalizeMaxItems/);
    assert.match(content, /function normalizeFavoriteRange/);
    assert.match(content, /Web\\s\*Page\|WebPage/);
    assert.match(content, /const hasFavoriteRange = Number\(favoriteRange\.min/);
    assert.match(content, /favoriteRange: \(message\.enrichDetails \|\| message\.retryFailed \|\| hasFavoriteRange\) \? \{\} : favoriteRange/);
    assert.match(content, /function limitPayloadItems/);
    assert.match(content, /function filterPayloadByFavoriteRange/);
    assert.match(content, /function applyPayloadLimits/);
    assert.match(content, /message\.enrichDetails \|\| message\.retryFailed/);
    assert.match(content, /const interactiveItems = retryFailed\s*\?\s*\[\]\s*:\s*baseItems/);
    assert.match(content, /function markDetailResolved/);
    assert.match(content, /function isDetailResolved/);
    assert.match(content, /function getBestCardScopeFromDetailLink/);
    assert.match(content, /function getPromptIdFromUrl/);
    assert.match(content, /function prepareListPageForCollection/);
    assert.match(content, /list-collect-close-detail/);
    assert.match(content, /structuredEntries:\s*\[\]/);
    assert.match(content, /extractedPrompt\s*&&\s*!promptNeedsDetailEnrichment\(extractedPrompt\)/);
    assert.match(content, /prompt_complete:\s*true/);
    assert.match(content, /function itemPromptNeedsDetailEnrichment/);
    assert.match(content, /targetAuthorMatchesPrompt/);
    assert.match(content, /extractPromptText\?\.\(target\)/);
    assert.match(collector, /VERSION\s*=\s*'2026-07-12\.69'/);
    assert.match(collector, /ACTION_PROMPT_LINE_PATTERN/);
    assert.match(collector, /MIN_ARTWORK_AREA/);
    assert.match(collector, /function cleanPromptText/);
    assert.match(collector, /function isLikelyNonPromptListText/);
    assert.match(collector, /function getStatusIdFromImageUrl/);
    assert.match(collector, /function dedupeImageUrlsByArtwork/);
    assert.match(collector, /function getTweetImageSequenceInfo/);
    assert.match(collector, /function expandTweetImageSequence/);
    assert.match(collector, /function buildMeigenDetailUrlFromStatusId/);
    assert.match(collector, /function getTrustedDetailArtworkExpectedCount/);
    assert.match(collector, /function isOriginalWorkStatusUrl/);
    assert.match(collector, /function itemMatchesFavoriteRange/);
    assert.match(collector, /function getNodeDocumentOrderScore/);
    assert.match(collector, /function findDetailArtworkRoot/);
    assert.match(collector, /function collectUniqueDetailImageUrls/);
    assert.match(collector, /function collectStructuredItemCandidates/);
    assert.match(collector, /function getBestStructuredCandidate/);
    assert.match(collector, /function isLikelyListContainerScope/);
    assert.match(collector, /function scoreListItemScope/);
    assert.match(collector, /function filterDetailImageUrlsByStatus/);
    assert.match(collector, /function isLikelyUnboundMeigenCommunityImageUrl/);
    assert.match(collector, /function isCommunityDetailUrl/);
    assert.match(collector, /function filterDetailImageUrlsByIdentity/);
    assert.match(collector, /function isImageUrlTrustedForStatus/);
    assert.match(collector, /function isUnresolvablePlaceholderItem/);
    assert.match(collector, /function getMeigenGenerationImageIdentity/);
    assert.match(collector, /detailMetadataIndex/);
    assert.match(collector, /PROMPT_PREVIEW_HARD_LIMIT\s*=\s*160/);
    assert.match(collector, /getDetailLinkUrls\(scope, baseUrl\)\.length/);
    assert.match(collector, /structuredEntries/);
    assert.match(collector, /Object\.prototype\.hasOwnProperty\.call\(options, 'structuredEntries'\)/);
    assert.match(collector, /expected_image_count/);
    assert.match(collector, /detail_expected_count_authoritative/);
    assert.match(collector, /imageCountIsComplete/);
    assert.match(collector, /detail_image_count_authoritative/);
    assert.match(collector, /DETAIL_CAROUSEL_COUNT_PATTERN/);
    assert.match(content, /PROMPT_COPY_TEXT_PATTERN/);
    assert.match(content, /DETAIL_PROMPT_LABEL_PATTERN/);
    assert.match(content, /function findDetailPromptPanel/);
    assert.match(content, /const promptPanel = findDetailPromptPanel\(documentRef\);/);
    assert.match(content, /findPromptActionControls\(promptRoot, PROMPT_COPY_TEXT_PATTERN\)/);
    assert.match(content, /function readPromptFromCopyButton/);
    assert.match(content, /function enrichDetailItemsWithVisibleAuthor/);
    assert.match(content, /function getCompletePromptTextFromDocument/);
    assert.match(content, /function shouldAttemptPromptCopyClick/);
    assert.match(content, /PROMPT_COPY_CLICK_DELAY_MS\s*=\s*650/);
    assert.match(content, /function enablePromptCopyCapture/);
    assert.match(content, /function waitForPromptCopyCapture/);
    assert.match(content, /function refreshStructuredDataCache/);
    assert.match(content, /function logDiagnostic/);
    assert.match(content, /function getDiagnostics/);
    assert.match(content, /function getSessionState/);
    assert.match(content, /function rememberSessionPayload/);
    assert.match(content, /updatedAt:\s*sessionState\.updatedAt/);
    assert.match(content, /automationStatus:\s*getAutomationStatus\(\)/);
    assert.match(content, /页面曾刷新或关闭，原任务已中断/);
    assert.match(content, /message\?\.type === MESSAGE_SESSION_STATE/);
    assert.match(content, /sendResponse\(getSessionState\(\)\)/);
    assert.match(content, /rememberSessionPayload\(payload, scrollJob\.lastSummary\)/);
    assert.match(content, /rememberSessionPayload\(payload, pageBatchJob\.lastSummary\)/);
    assert.match(content, /rememberSessionPayload\(payload, summary\)/);
    assert.match(content, /detail-current-opened/);
    assert.match(content, /prompt-panel/);
    assert.match(content, /currentMatchesTarget/);
    assert.match(content, /image_urls:\s*getItemImageUrlPreview/);
    assert.match(content, /favorite_count:\s*item\.favorite_count/);
    assert.match(content, /imageUrls:\s*lastItems\.map/);
    assert.match(content, /collector_version/);
    assert.match(content, /function buildCollectionOptions/);
    assert.match(content, /function getDetailFavoriteCountFromPromptPanel/);
    assert.match(content, /expectedDetailImageCount: detailExpectedCount/);
    assert.match(content, /detailFavoriteCount: getDetailFavoriteCountFromPromptPanel/);
    assert.match(content, /FatherKeyMeigenDataCacheRequest/);
    assert.match(content, /const structuredEntries = Array\.isArray\(extra\.structuredEntries\)/);
    assert.match(content, /getStructuredEntriesForCollection\(\)/);
    assert.match(content, /FatherKeyMeigenEnablePromptCapture/);
    assert.match(content, /FatherKeyMeigenPromptCopied/);
    assert.match(content, /focusPromptCopyControl\(control\);/);
    assert.match(content, /await sleep\(PROMPT_COPY_CLICK_DELAY_MS\);/);
    assert.match(content, /const extractedPrompt = getCompletePromptTextFromDocument\(promptRoot, collector\);/);
    assert.match(content, /if \(!shouldAttemptPromptCopyClick\(documentRef\)\) continue;/);
    assert.match(content, /readPromptFromCopyButton\(promptPanel, collector\)/);
    assert.match(content, /source_item_id:\s*item\.source_item_id \|\| detailItem\.source_item_id/);
    assert.match(content, /source_page_url:\s*item\.source_page_url \|\| ''/);
    assert.match(content, /function enrichItemsWithCopiedPrompt/);
    assert.match(content, /function hasCompletePromptData/);
    assert.match(content, /function promptNeedsDetailEnrichment/);
    assert.match(content, /function filterUsableDetailItems/);
    assert.match(content, /clipboard\.readText/);
    assert.match(background, /action:\s*'stage_items'/);
    assert.match(background, /action:\s*'check_duplicates'/);
    assert.match(background, /FATHER_KEY_CHECK_IMPORT_DUPLICATES/);
    assert.match(background, /max_items:\s*normalizeMaxItems\(maxItems\)/);
    assert.match(background, /min_favorites:\s*normalizeOptionalCount\(minFavorites\)/);
    assert.match(background, /max_favorites:\s*normalizeOptionalCount\(maxFavorites\)/);
    assert.match(background, /credentials:\s*'include'/);
    assert.match(background, /\/api\/admin\/prompts\/imports/);
    assert.match(background, /MESSAGE_STAGE_VIA_ADMIN_TAB/);
    assert.match(background, /function stageImportPayloadViaAdminTab/);
    assert.match(background, /function ensureAdminBridgeInjected/);
    assert.match(background, /chrome\.scripting\.executeScript/);
    assert.match(background, /function createAdminBridgeConnectionError/);
    assert.match(background, /送入队列连接失败/);
    assert.match(background, /chrome\.tabs\.query\(\{\}\)/);
    assert.match(background, /chrome\.tabs\.sendMessage/);
    assert.match(background, /isUnauthorizedResponse\(response, result\)/);
    assert.match(background, /chrome\.downloads\.download/);
    assert.match(popup, /FATHER_KEY_STAGE_IMPORT/);
    assert.match(popup, /FATHER_KEY_DOWNLOAD_IMPORT/);
    assert.match(popup, /FATHER_KEY_MEIGEN_DETAIL_PAUSE/);
    assert.match(popup, /FATHER_KEY_MEIGEN_DETAIL_RESUME/);
    assert.match(popup, /FATHER_KEY_MEIGEN_SCROLL_COLLECT/);
    assert.match(popup, /FATHER_KEY_MEIGEN_SCROLL_STOP/);
    assert.match(popup, /FATHER_KEY_MEIGEN_PAGE_BATCH_COLLECT/);
    assert.match(popup, /FATHER_KEY_MEIGEN_PAGE_BATCH_STOP/);
    assert.match(popup, /FATHER_KEY_MEIGEN_DIAGNOSTICS/);
    assert.match(popup, /FATHER_KEY_MEIGEN_SESSION_STATE/);
    assert.match(popup, /function setCollectorVersion/);
    assert.match(popup, /function formatProgress/);
    assert.match(popup, /function setProgressStatus/);
    assert.match(popup, /function getDetailProgressTotal/);
    assert.match(popup, /startDetailPolling\(\{ waitForStart: true \}\)/);
    assert.match(popup, /startScrollPolling\(\{ waitForStart: true \}\)/);
    assert.match(popup, /startPageBatchPolling\(\{ waitForStart: true \}\)/);
    assert.match(popup, /if \(status\?\.running\) observedRunning = true/);
    assert.match(popup, /补抓详情中/);
    assert.match(popup, /滚动采集中/);
    assert.match(popup, /翻页采集中/);
    assert.match(popup, /function getFriendlyConnectionMessage/);
    assert.match(popup, /送入队列连接失败：请刷新 Admin Studio 页面/);
    assert.match(popup, /function copyDiagnostics/);
    assert.match(popup, /function restoreCollectorSession/);
    assert.match(popup, /function applySessionState/);
    assert.match(popup, /function resumeStatusPollingForRunningJobs/);
    assert.match(popup, /type: MESSAGE_SESSION_STATE/);
    assert.match(popup, /正在恢复采集进度/);
    assert.match(popup, /已恢复上次采集结果/);
    assert.match(popup, /await restoreCollectorSession\(\)/);
    assert.match(popup, /诊断已复制/);
    assert.match(popup, /retryFailed/);
    assert.match(popup, /function itemNeedsDetailEnrichment/);
    assert.match(popup, /state\.payload\.items\.filter\(\(item\) => itemNeedsDetailEnrichment\(item\)\)\.length/);
    assert.match(popup, /expectedImageCount = Number/);
    assert.match(popup, /imageCountIncomplete/);
    assert.match(popup, /favoriteCount <= 0/);
    assert.match(popup, /function payloadNeedsDetailEnrichment/);
    assert.match(popup, /function promptNeedsDetailEnrichment/);
    assert.match(popup, /function getMissingPromptCount/);
    assert.match(popup, /promptNeedsDetailEnrichment\(item\?\.prompt_text/);
    assert.match(popup, /function collectCurrentPageWithAutoEnrich\(\{ preflightDuplicates = false \} = \{\}\)/);
    assert.match(popup, /scrollCollectCurrentPage\(\{ automatic: true \}\)/);
    assert.match(popup, /pageBatchCollectCurrentPage\(\{ automatic: true \}\)/);
    assert.match(popup, /continueExisting:\s*automatic/);
    assert.match(popup, /automatic \? Math\.max\(DEFAULT_PAGE_BATCH_PAGES, getMaxItemsSetting\(\)\)/);
    assert.match(content, /return Math\.min\(parsed, 1000\)/);
    assert.match(content, /message\.continueExisting/);
    assert.match(content, /preflightDuplicates[\s\S]*filterRepositoryDuplicates\(currentItems/);
    assert.match(content, /markPendingDetail\(detailJob\.lastPayload\?\.items \|\| \[\]\)/);
    assert.match(content, /detailJob\.total \+= fallbackUrls\.length/);
    assert.match(content, /detailJob\.phase = 'fallback'/);
    assert.match(content, /detailJob\.processed \+= 1/);
    assert.match(popup, /state\.detailStatus\.phase === 'fallback' \? '详情页补抓中' : '卡片补抓中'/);
    assert.match(content, /String\(streamStageState\.batchId \|\| ''\) !== String\(message\.batchId \|\| ''\)/);
    assert.match(popup, /maxSteps:\s*automatic \? getMaxItemsSetting\(\) : DEFAULT_SCROLL_STEPS/);
    assert.match(popup, /检查 \$\{checked\} 条候选，实际入队 \$\{staged\} 条/);
    assert.match(content, /SCROLL_COLLECT_STABLE_LIMIT = 8/);
    assert.match(content, /checkedKeys:\s*new Set\(\)/);
    assert.match(content, /checkedCandidateCount:\s*checkedKeys\.size/);
    assert.match(popup, /preflightDuplicates:\s*automatic/);
    assert.match(popup, /streamToQueue:\s*automatic/);
    assert.match(popup, /batchId:\s*state\.streamedBatchId/);
    assert.match(popup, /已采集.*已入队/);
    assert.match(content, /async function filterRepositoryDuplicates/);
    assert.match(content, /repositoryDuplicateCount \+= duplicateCheck\.duplicateCount/);
    assert.match(content, /targetCount >= maxItems/);
    assert.match(popup, /正在自动滚动加载/);
    assert.match(popup, /发现待补内容，正在补抓详情/);
    assert.match(popup, /条待补提示词/);
    assert.match(popup, /先补抓详情，再下载结果/);
    assert.match(popup, /function getMaxItemsSetting/);
    assert.match(popup, /function getFavoriteFilterSettings/);
    assert.match(popup, /function filterPayloadByFavoriteSettings/);
    assert.match(popup, /maxItems:\s*getMaxItemsSetting\(\)/);
    assert.match(popup, /minFavoritesInput/);
    assert.match(popup, /maxFavoritesInput/);
    assert.match(popup, /先补抓详情，再送入队列/);
    assert.match(popup, /已通过 Admin Studio 登录态提交/);
    assert.match(popup, /仓库重复跳过/);
    assert.match(popup, /const ready = await ensureContentScriptReady\(tab\);/);
    assert.match(popup, /请刷新 Meigen 页面后再采集/);
    assert.match(popup, /当前页只发现/);
    assert.match(html, /id="collectBtn"/);
    assert.match(html, /id="scrollBtn"/);
    assert.match(html, /id="stopScrollBtn"/);
    assert.match(html, /id="pageBatchBtn"/);
    assert.match(html, /id="stopPageBatchBtn"/);
    assert.match(html, /id="enrichBtn"/);
    assert.match(html, /id="pauseBtn"/);
    assert.match(html, /id="retryBtn"/);
    assert.match(html, /id="stageBtn"/);
    assert.match(html, /id="downloadBtn"/);
    assert.match(html, /id="diagnosticsBtn"/);
    assert.match(html, /id="versionText"/);
    assert.match(html, /id="maxItemsInput"/);
    assert.match(html, /id="maxItemsInput"[^>]*max="1000"/);
    assert.match(html, /id="minFavoritesInput"/);
    assert.match(html, /id="maxFavoritesInput"/);
    assert.match(html, /实际入队目标/);
    assert.match(html, /收藏最少/);
    assert.match(html, /收藏最多/);
    assert.match(html, /全自动采集并入队/);
    assert.match(html, /滚动采集/);
    assert.match(html, /停止滚动/);
    assert.match(html, /翻页采集/);
    assert.match(html, /停止翻页/);
    assert.match(html, /补抓详情/);
    assert.match(html, /重试失败/);
    assert.match(html, /送入队列/);
    assert.match(html, /下载结果/);
    assert.match(html, /复制诊断/);
    assert.match(bridge, /FatherKeyMeigenClipboardBridgeInstalled/);
    assert.match(bridge, /FatherKeyMeigenEnablePromptCapture/);
    assert.match(bridge, /FatherKeyMeigenPromptCopied/);
    assert.match(bridge, /FatherKeyMeigenDataCacheRequest/);
    assert.match(bridge, /FatherKeyMeigenDataCacheResponse/);
    assert.match(bridge, /__FatherKeyMeigenDataCache/);
    assert.match(bridge, /DATA_CACHE_TOTAL_TEXT_LIMIT/);
    assert.match(bridge, /function dataCacheEntryMatchesContext/);
    assert.match(bridge, /getDataCacheSnapshot\(data\.currentUrl \|\| window\.location\.href\)/);
    assert.match(bridge, /window\.fetch/);
    assert.match(bridge, /XMLHttpRequest/);
    assert.match(bridge, /navigator\.clipboard/);
    assert.match(bridge, /execCommand/);
    assert.match(adminBridge, /FATHER_KEY_STAGE_IMPORT_VIA_ADMIN_TAB/);
    assert.match(adminBridge, /\/api\/admin\/prompts\/imports/);
    assert.match(adminBridge, /credentials:\s*'include'/);
});
