const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (filePath) => fs.readFileSync(path.join(root, filePath), 'utf8');

test('prompt palette data is wired through schema, admin saves, Meigen imports, and backfill', () => {
    const migration = read('supabase/migrations/20260716_add_prompt_image_palettes.sql');
    const manage = read('server/api-handlers/admin/prompts/manage.js');
    const imports = read('server/api-handlers/admin/prompts/imports.js');
    const backfill = read('scripts/backfill-prompt-image-palettes.js');
    const packageJson = JSON.parse(read('package.json'));

    assert.match(migration, /image_palettes JSONB NOT NULL DEFAULT '\[\]'::jsonb/);
    assert.match(manage, /resolvePromptImagePalettes/);
    assert.match(manage, /image_palettes: result\.palettes/);
    assert.match(imports, /extractPromptImagePalette\(downloaded\.buffer/);
    assert.match(imports, /image_palettes: alignPromptImagePalettes/);
    assert.match(backfill, /concurrency: 4/);
    assert.match(backfill, /hasCurrentPromptImagePalettes/);
    assert.equal(packageJson.scripts['backfill:prompt-palettes'], 'node scripts/backfill-prompt-image-palettes.js');
});

test('prompt detail loads the persisted palette and copies hex colors', () => {
    const html = read('prompts.html');
    const script = read('prompts-poetry.js');
    const styles = read('prompts-poetry.css');

    assert.match(html, /id="modalImagePalette"/);
    assert.match(html, /id="modalImagePaletteWide"/);
    assert.match(html, /data-prompt-image-palette/);
    assert.match(script, /'image_palettes'/);
    assert.match(script, /const imagePalettes = normalizePromptImagePalettesFromRecord\(item\)/);
    assert.match(script, /imagePalettes,\s*image_palettes: imagePalettes/);
    assert.match(script, /function renderModalImagePalette/);
    assert.match(script, /querySelectorAll\('\[data-prompt-image-palette\]'\)/);
    assert.match(script, /writePromptShareTextToClipboard\(hex\)/);
    assert.match(script, /button\.dataset\.tooltip = copyLabel/);
    assert.doesNotMatch(script, /button\.setAttribute\('title', getPromptPaletteCopyLabel/);
    assert.match(script, /currentModalImageIndex/);
    assert.match(styles, /\.prompt-image-palette-color/);
    const paletteColorRule = styles.match(/\.prompt-image-palette-color\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(paletteColorRule, /box-shadow:\s*none/);
    assert.doesNotMatch(paletteColorRule, /inset\s+0/);
    assert.match(styles, /\.prompt-image-palette-color::after/);
    assert.match(styles, /content:\s*attr\(data-tooltip\)/);
    assert.match(styles, /transition:\s*opacity 70ms ease-out, transform 90ms ease-out/);
    const copiedPaletteRule = styles.match(/\.prompt-image-palette-color\.copied\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.doesNotMatch(copiedPaletteRule, /opacity:/);
    const toastRule = styles.match(/\.gallery-toast\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(toastRule, /z-index:\s*30000/);
    assert.match(toastRule, /background:\s*#ffffff/);
    assert.match(toastRule, /backdrop-filter:\s*none/);
    const compactToastRule = styles.match(/\.gallery-toast--compact\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(compactToastRule, /padding:\s*9px 14px/);
    assert.match(compactToastRule, /border-radius:\s*12px/);
    assert.match(compactToastRule, /transform 200ms cubic-bezier\(0\.22, 1, 0\.36, 1\)/);
    assert.doesNotMatch(compactToastRule, /1\.56/);
    assert.match(script, /gallery-toast--compact/);
    assert.match(script, /1600,\s*true/);
    const promptHeaderRule = styles.match(/\.prompt-content-header\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(promptHeaderRule, /grid-template-columns:\s*minmax\(0, 1fr\) auto minmax\(0, 1fr\)/);
    const paletteRule = styles.match(/\.prompt-image-palette\s*\{[\s\S]*?\}/)?.[0] || '';
    const headerActionsRule = styles.match(/\.prompt-header-actions\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(paletteRule, /grid-column:\s*2/);
    assert.match(headerActionsRule, /grid-column:\s*3/);
    assert.match(styles, /@media \(max-width: 768px\)[\s\S]*?\.prompt-image-palette\s*\{[\s\S]*?align-self:\s*center/);
    assert.match(styles, /\.prompt-image-palette--image\.is-visible/);
    assert.match(styles, /bottom:\s*22px/);
    const imagePaletteRule = styles.match(/\.modal-inner \.prompt-image-palette--image\.is-visible\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(imagePaletteRule, /background:\s*#f8fafc/);
    assert.match(imagePaletteRule, /backdrop-filter:\s*none/);
    assert.match(imagePaletteRule, /border-radius:\s*18px/);
    assert.match(imagePaletteRule, /box-shadow:\s*0 6px 18px rgba\(15, 23, 42, 0\.1\)/);
    assert.match(styles, /\.prompt-image-palette--image\.is-visible\.is-over-image/);
    const overImagePaletteRule = styles.match(/\.modal-inner:not\(\.comment-mode\):not\(\.related-mode\) \.prompt-image-palette--image\.is-visible\.is-over-image\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(overImagePaletteRule, /background:\s*rgba\(15, 23, 42, 0\.28\)/);
    assert.match(overImagePaletteRule, /backdrop-filter:\s*blur\(18px\) saturate\(1\.18\)/);
    assert.match(overImagePaletteRule, /box-shadow:\s*0 8px 24px rgba\(15, 23, 42, 0\.14\)/);
    assert.match(styles, /\[data-theme="dark"\][\s\S]*?\.prompt-image-palette--image\.is-visible\s*\{[\s\S]*?background:\s*#1e293b/);
    assert.match(styles, /\[data-theme="dark"\][\s\S]*?\.prompt-image-palette--image\.is-visible\.is-over-image\s*\{[\s\S]*?background:\s*rgba\(15, 23, 42, 0\.28\)/);
    assert.match(styles, /\.modal-inner:not\(\.comment-mode\):not\(\.related-mode\) \.prompt-content-header > \.prompt-image-palette\.is-visible/);
    const defaultThumbPositionRule = styles.match(/\.modal-inner:not\(\.comment-mode\):not\(\.related-mode\) \.modal-img-thumbs\.is-visible\s*\{[\s\S]*?\}/)?.[0] || '';
    assert.match(defaultThumbPositionRule, /bottom:\s*68px/);
    assert.doesNotMatch(styles, /\.prompt-image-palette--image\.is-visible ~ \.modal-img-thumbs\.is-visible/);
    assert.match(styles, /\.modal-inner\.comment-mode \.prompt-image-palette--image\.is-visible/);
    assert.match(styles, /\.modal-inner\.comment-mode-returning \.prompt-image-palette--image\.is-visible/);
    assert.match(styles, /opacity 500ms cubic-bezier\(0\.16, 1, 0\.3, 1\)/);
    assert.match(styles, /transform 500ms cubic-bezier\(0\.16, 1, 0\.3, 1\)/);
    assert.match(styles, /@keyframes promptDesktopPaletteDockReveal/);
    assert.match(styles, /animation: promptDesktopPaletteDockReveal 500ms cubic-bezier\(0\.16, 1, 0\.3, 1\) both/);
    assert.match(styles, /@keyframes promptDesktopPaletteReturn/);
    assert.match(styles, /animation: promptDesktopPaletteReturn 500ms cubic-bezier\(0\.16, 1, 0\.3, 1\) both/);
    assert.match(styles, /translate3d\(-50%, -18px, 0\) scale\(0\.92\)/);
    assert.match(script, /function syncModalImagePaletteSurface/);
    assert.match(script, /paletteContainer\.classList\.toggle\('is-over-image'/);
    assert.match(script, /overlapRatio >= 0\.2/);
});
