const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const walletScriptPath = path.resolve(__dirname, '../js/components/WalletModal.js');
const walletStylesPath = path.resolve(__dirname, '../css/wallet.css');
const pointsServicePath = path.resolve(__dirname, '../js/services/PointsService.js');
const zhLocalePath = path.resolve(__dirname, '../lang/zh.json');
const enLocalePath = path.resolve(__dirname, '../lang/en.json');
const usdtPreviewHtmlPath = path.resolve(__dirname, '../usdt_payment_flow_preview.html');
const usdtPreviewRuntimePath = path.resolve(__dirname, '../js/usdt-payment-flow-preview-runtime.js');
const usdtPreviewBootPath = path.resolve(__dirname, '../js/usdt-payment-flow-preview-boot.js');

test('wallet recharge UI exposes pending feedback hooks for package and custom recharge actions', () => {
    const script = fs.readFileSync(walletScriptPath, 'utf8');

    assert.match(script, /pendingRechargeAction:\s*null/);
    assert.doesNotMatch(script, /id="wallet-recharge-progress"/);
    assert.match(script, /setRechargeActionPendingState\(state = null\)/);
    assert.match(script, /buildRechargePendingMarkup\(label = '处理中', options = \{\}\)/);
    assert.doesNotMatch(script, /priceEl\.innerHTML\s*=\s*this\.buildRechargePendingMarkup/);
    assert.match(script, /action === 'pay-selected-recharge'/);
    assert.match(script, /wallet-pending-dots/);
    assert.match(script, /wallet-recharge-package-loading/);
    assert.match(script, /wallet-recharge-package-loading-dots/);
    assert.match(script, /dotsOnly/);
    assert.match(script, /type="button" class="package-item"/);
    assert.match(script, /data-wallet-package-price/);
    assert.match(script, /id="wallet-custom-recharge-subtitle" hidden/);
    assert.match(script, /id="wallet-custom-recharge-badge" hidden/);
    assert.match(script, /id="wallet-custom-recharge-meta" hidden/);
    assert.match(script, /placeholder="请输入充值金额"/);
    assert.match(script, /id="wallet-recharge-payment-panel" hidden/);
    assert.match(script, /id="wallet-recharge-package-methods"/);
    assert.match(script, /id="wallet-recharge-method-dock" hidden/);
    assert.doesNotMatch(script, /wallet-recharge-method-dock-label/);
    assert.match(script, /id="wallet-custom-recharge-methods"/);
    assert.match(script, /action:\s*isPackageMode \? 'pay-selected-recharge' : 'custom-recharge'/);
    assert.match(script, /case 'pay-selected-recharge':/);
    assert.match(script, /'wallet-payment-method': method\.key/);
    assert.doesNotMatch(script, /前往\$\{providerLabel\}/);
    assert.doesNotMatch(script, /当前按 1 积分 = 1 元结算，支持 0\.01 精度/);
    assert.doesNotMatch(script, /按元测试换算成积分/);
    assert.match(script, /step="0\.01"/);
    assert.match(script, /inputmode="decimal"/);
    assert.match(script, /resolveCustomRechargeRequest\(rawValue, rechargeOptions = this\.rechargeOptionsConfig\)/);
    assert.match(script, /errorMessage: `请输入\$\{inputLabel\}`/);
    assert.match(script, /tryPresentHostedPaymentQrModal\(paymentResult,\s*\{/);
    assert.match(script, /tryPresentNowpaymentsCheckoutModal\(paymentResult,\s*\{/);
    assert.match(script, /normalizePaymentSurchargeRate\(value, fallback = 0\)/);
    assert.match(script, /estimatePaymentSurcharge\(provider = \{\}, baseAmount = null\)/);
    assert.match(script, /resolveCryptoPaymentPricingSummary\(paymentResult = \{\}, providerSummary = \{\}, options = \{\}\)/);
    assert.match(script, /resolvePaymentPricingSummary\(paymentResult = \{\}, providerSummary = \{\}\)/);
    assert.match(script, /wallet-recharge-method-fee/);
    assert.match(script, /payment_fee_amount/);
    assert.match(script, /base_amount/);
    assert.match(script, /paymentResult\.mode === 'crypto_checkout'/);
    assert.match(script, /wallet-crypto-primary-amount/);
    assert.match(script, /wallet-crypto-countdown/);
    assert.match(script, /wallet-crypto-timeout/);
    assert.match(script, /js-wallet-crypto-timeout/);
    assert.match(script, /wallet\.usdtPaymentExpiredTitle/);
    assert.match(script, /wallet\.usdtPaymentConfirmingTitle/);
    assert.match(script, /wallet\.usdtPaymentConfirmingAfterQuoteExpired/);
    assert.match(script, /startCryptoCheckoutCountdown\(detailOverlay, expiresAtIso\)/);
    assert.match(script, /resolveCryptoCheckoutExpiresAt\(providerSummary\)/);
    assert.match(script, /buildPaymentTimeoutPanel\(options = \{\}\)/);
    assert.match(script, /renderHostedPaymentQrTimeout\(detailOverlay\)/);
    assert.match(script, /isHostedPaymentTimeoutStatus\(statusResult = \{\}\)/);
    assert.match(script, /formatPaymentSuccessWithPoints\(pointsValue\)/);
    assert.match(script, /支付成功，积分\+\{points\}/);
    assert.doesNotMatch(script, /USDT-BEP20 付款信息已生成/);
    assert.doesNotMatch(script, /请在倒计时结束前完成转账，超时请重新发起支付。/);
    assert.doesNotMatch(script, /js-wallet-copy-usdt-address-bottom/);
    assert.doesNotMatch(script, /js-wallet-copy-usdt-amount-bottom/);
    assert.match(script, /startHostedPaymentQrPolling\(detailOverlay, paymentResult, \{\s*\.\.\.options,\s*initialStatusMessage,\s*waitingMessage\s*\}\)/);
    assert.match(script, /PointsService\.getPaymentRequestStatus\(/);
    assert.match(script, /qrcode_img_url/);
    assert.match(script, /qrcode_url/);
    assert.match(script, /pay_address/);
    assert.match(script, /pay_amount_text/);
    assert.match(script, /const cryptoPricing = this\.resolveCryptoPaymentPricingSummary\(paymentResult, providerSummary/);
    assert.match(script, /cryptoPricing\.totalText/);
    assert.match(script, /cryptoPricing\.feeText/);
    assert.match(script, /maxDecimals:\s*this\.getCryptoPayAmountPrecision\(providerSummary\)/);
    assert.match(script, /fixedDecimals:\s*true/);
    assert.match(script, /renderRechargePaymentMethodIcon\(method = \{\}\)/);
    assert.match(script, /renderRechargeMethodFeeMarkup\(method = \{\}, surcharge = \{\}\)/);
    assert.match(script, /wallet-recharge-method-fee-amount/);
    assert.match(script, /paymentMethodPayableWithFee/);
    assert.match(script, /clearSelectedRechargePackageForCustomInput\(rawValue = ''\)/);
    assert.match(script, /action:\s*isPackageMode \? 'pay-selected-recharge' : 'custom-recharge'/);
    assert.match(script, /timeoutMs:\s*Infinity/);
    assert.match(script, /deferTimeoutUntilQuoteExpired:\s*true/);
    assert.match(script, /continueAfterQuoteExpired:\s*true/);
    assert.match(script, /quoteExpiredWaitingMessage:/);
    assert.match(script, /isCryptoCheckoutQuoteActive\(detailOverlay\)/);
    assert.match(script, /请复制上方显示金额付款，二维码仅包含收款地址。/);
    assert.doesNotMatch(script, /请复制上方精确金额付款/);
});

test('wallet mobile zpay checkout preserves the wallet page and polls while Alipay opens', () => {
    const script = fs.readFileSync(walletScriptPath, 'utf8');
    const zh = JSON.parse(fs.readFileSync(zhLocalePath, 'utf8'));
    const en = JSON.parse(fs.readFileSync(enLocalePath, 'utf8'));

    assert.match(script, /openPaymentCheckoutUrl\(checkoutUrl, options = \{\}\)/);
    assert.match(script, /preserveCurrentPage = options\.preserveCurrentPage === true/);
    assert.match(script, /options\.sameTab === true \|\| \(this\.isMobilePaymentBrowser\(\) && !preserveCurrentPage\)/);
    assert.match(script, /window\.location\.assign\(url\)/);
    assert.match(script, /if \(provider !== 'zpay'\)/);
    assert.doesNotMatch(script, /provider !== 'zpay' \|\| this\.isMobilePaymentBrowser\(\)/);
    assert.match(script, /const isMobilePayment = this\.isMobilePaymentBrowser\(\)/);
    assert.match(script, /const qrcodeImgUrl = isMobilePayment \? '' : String\(providerSummary\.qrcode_img_url/);
    assert.match(script, /!qrcodeImgUrl && !qrcodeUrl && !checkoutUrl/);
    assert.match(script, /wallet-payment-qr-modal--mobile-handoff/);
    assert.match(script, /wallet\.openAlipayToPay/);
    assert.match(script, /mobileAlipayPaymentWaiting/);
    assert.match(script, /resolveMobileAlipayAppLaunchUrl\(...paymentUrls\)/);
    assert.match(script, /alipays:\/\/platformapi\/startapp\?appId=20000067&url=/);
    assert.match(script, /window\.location\.href = mobileAppLaunchUrl/);
    assert.match(script, /document\.addEventListener\('visibilitychange', handlePaymentResume\)/);
    assert.match(script, /window\.addEventListener\('pageshow', handlePaymentResume\)/);
    assert.match(script, /this\.openPaymentCheckoutUrl\(openUrl, \{\s*preserveCurrentPage: isMobilePayment,\s*mobileAppLaunchUrl\s*\}\)/);
    assert.match(script, /this\.startHostedPaymentQrPolling\(detailOverlay, paymentResult, \{\s*\.\.\.options,\s*initialStatusMessage,\s*waitingMessage\s*\}\)/);
    assert.doesNotMatch(script, /支付页面被浏览器拦截，请允许弹窗后重试/);

    assert.equal(zh.wallet.openAlipayToPay, '打开支付宝支付');
    assert.match(zh.wallet.mobileAlipayPaymentHint, /直接拉起支付宝 App/);
    assert.equal(en.wallet.openAlipayToPay, 'Open Alipay');
    assert.match(en.wallet.mobileAlipayPaymentHint, /Alipay app directly/);
});

test('wallet localizes payment intent creation errors from stable gateway codes', () => {
    const script = fs.readFileSync(walletScriptPath, 'utf8');
    const pointsService = fs.readFileSync(pointsServicePath, 'utf8');
    const zh = JSON.parse(fs.readFileSync(zhLocalePath, 'utf8'));
    const en = JSON.parse(fs.readFileSync(enLocalePath, 'utf8'));

    assert.match(script, /resolveLocalizedPaymentCreationErrorMessage\(error\)/);
    assert.match(script, /classifyPaymentCreationErrorMessage\(message = ''\)/);
    assert.match(script, /amount\\s\*to\\s\+is\\s\+too\\s\+small/);
    assert.match(script, /case 'payment_amount_too_small':/);
    assert.match(script, /wallet\.paymentErrorAmountTooSmall/);
    assert.match(pointsService, /error\.code = String\(responsePayload\?\.code \|\| responsePayload\?\.payment_error\?\.code \|\| ''\)\.trim\(\);/);
    assert.match(pointsService, /error\.rawMessage = String\(responsePayload\?\.raw_message \|\| responsePayload\?\.payment_error\?\.raw_message/);
    assert.equal(zh.wallet.paymentErrorAmountTooSmall, '支付金额低于支付通道最低限额，请提高充值金额后重新发起支付。');
    assert.equal(en.wallet.paymentErrorAmountTooSmall, "The payment amount is below this channel's minimum. Increase the recharge amount and start payment again.");
    assert.equal(Boolean(zh.wallet.paymentErrorGatewayUnavailable), true);
    assert.equal(Boolean(en.wallet.paymentErrorGatewayUnavailable), true);
});

test('USDT payment flow preview can simulate slow post-expiry confirmation', () => {
    const previewHtml = fs.readFileSync(usdtPreviewHtmlPath, 'utf8');
    const previewRuntime = fs.readFileSync(usdtPreviewRuntimePath, 'utf8');
    const previewBoot = fs.readFileSync(usdtPreviewBootPath, 'utf8');

    assert.match(previewHtml, /id="previewSlowConfirm"/);
    assert.match(previewHtml, /PAYMENT_METHOD_UNIFIED_1/);
    assert.match(previewRuntime, /surcharge_rate:\s*0\.01/);
    assert.match(previewRuntime, /pay_amount_precision:\s*2/);
    assert.match(previewRuntime, /function buildPaymentPricing\(baseAmount, providerKey\)/);
    assert.match(previewRuntime, /payment_fee_amount:\s*pricing\.paymentFeeAmount/);
    assert.match(previewRuntime, /checkout_session_status:\s*"expired"/);
    assert.match(previewRuntime, /预览环境继续等待后续链上确认/);
    assert.match(previewBoot, /triggerUsdt\(options = \{\}\)/);
    assert.match(previewBoot, /quoteTtlMs:\s*3000/);
    assert.match(previewBoot, /statusMode:\s*"expired"/);
    assert.match(previewBoot, /setStatusMode\("completed"\)/);
});

test('wallet recharge styles include visible processing states', () => {
    const styles = fs.readFileSync(walletStylesPath, 'utf8');

    assert.match(styles, /\.package-item\.is-processing/);
    assert.match(styles, /\.package-item\.is-dimmed/);
    assert.match(styles, /\.package-item\.is-selected/);
    assert.match(styles, /\.custom-recharge-btn\.is-processing/);
    assert.match(styles, /\.wallet-recharge-method-btn/);
    assert.match(styles, /\.wallet-recharge-method-dock/);
    assert.match(styles, /\.wallet-recharge-method-buttons--dock/);
    assert.match(styles, /grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
    assert.match(styles, /\.wallet-recharge-method-btn--alipay:hover:not\(:disabled\)/);
    assert.match(styles, /\.wallet-recharge-method-btn--usdt:hover:not\(:disabled\)/);
    assert.match(styles, /\.wallet-recharge-method-fee/);
    assert.match(styles, /\.wallet-recharge-method-fee-amount/);
    assert.match(styles, /\.wallet-recharge-brand-icon--alipay/);
    assert.match(styles, /\.wallet-recharge-brand-icon--usdt/);
    assert.match(styles, /\.custom-recharge-section\.is-package-mode/);
    assert.match(styles, /\.wallet-recharge-method-btn\.is-processing \.wallet-pending-badge/);
    assert.match(styles, /rgba\(22,\s*119,\s*255,\s*0\.14\)/);
    assert.match(styles, /\.wallet-recharge-payment-panel/);
    assert.match(styles, /\.wallet-pending-dots/);
    assert.match(styles, /\.wallet-recharge-package-loading/);
    assert.match(styles, /grid-column:\s*1 \/ -1/);
    assert.match(styles, /justify-content:\s*center/);
    assert.match(styles, /@keyframes walletPendingDots/);
    assert.doesNotMatch(styles, /@keyframes walletSpinnerRotate/);
    assert.match(styles, /\.wallet-payment-qr-modal/);
    assert.match(styles, /\.wallet-payment-qr-image/);
    assert.match(styles, /\.wallet-payment-qr-status/);
    assert.match(styles, /\.wallet-payment-qr-status\.is-reveal-pending/);
    assert.match(styles, /\.wallet-payment-qr-status\.is-revealing/);
    assert.match(styles, /\.wallet-payment-qr-status\.is-success/);
    assert.match(styles, /\.wallet-crypto-checkout-modal/);
    assert.match(styles, /\.wallet-crypto-countdown/);
    assert.match(styles, /\.wallet-crypto-countdown\.is-expired/);
    assert.match(styles, /\.wallet-crypto-countdown\.is-confirming/);
    assert.match(styles, /\.wallet-crypto-primary-amount/);
    assert.match(styles, /\.wallet-payment-qr-card\.is-timeout/);
    assert.match(styles, /\.wallet-crypto-qr-card\.is-timeout/);
    assert.match(styles, /\.wallet-crypto-timeout/);
    assert.match(styles, /\.wallet-crypto-timeout--pending/);
    assert.match(styles, /@keyframes walletCryptoTimeoutSpark/);
    assert.match(styles, /\.wallet-crypto-copy-card/);
    assert.match(styles, /\.wallet-crypto-warning/);
});

test('wallet recharge scroll cue follows the active scroll host and hides after scrolling', () => {
    const script = fs.readFileSync(walletScriptPath, 'utf8');
    const styles = fs.readFileSync(walletStylesPath, 'utf8');

    assert.match(script, /function getWalletModalScrollElements\(\)/);
    assert.match(script, /function getWalletRechargeScrollCueScroller\(\)/);
    assert.match(script, /candidates\.find\(el => el\.scrollTop > 2\)/);
    assert.match(script, /const scrollHost = getWalletRechargeScrollCueScroller\(\)/);
    assert.match(script, /if \(overflowAmount < 8\)/);
    assert.match(script, /const nearTop = scrollHost\.scrollTop <= 2/);
    assert.match(script, /scrollElements\.forEach\(el => el\.addEventListener\('scroll', handleContentScroll, \{ passive: true \}\)\)/);
    assert.doesNotMatch(script, /!isRechargeActive \|\| !isCompactMobile/);

    assert.match(styles, /\.wallet-recharge-scroll-cue \{\s*display: flex;/);
    assert.match(styles, /@media \(min-width: 601px\)[\s\S]*\.wallet-recharge-scroll-cue \{[\s\S]*left: 160px;/);
});

test('wallet payment order query section is driven by provider config instead of a hardcoded afdian-only branch', () => {
    const script = fs.readFileSync(walletScriptPath, 'utf8');

    assert.match(script, /order_query_enabled:\s*true/);
    assert.match(script, /order_query_title:\s*'订单号认领'/);
    assert.match(script, /const queryEnabled = activeProvider\?\.key === 'afdian'[\s\S]*activeProvider\?\.order_query_enabled === true/);
    assert.match(script, /recoverPaymentConfigsFromSystemConfig\(\)/);
    assert.match(script, /loadSystemConfigValue\('payment_channels'\)/);
    assert.match(script, /loadSystemConfigValue\('recharge_options'\)/);
    assert.match(script, /id="wallet-order-query-section" hidden/);
    assert.match(script, /const customRechargeVisible = !document\.getElementById\('wallet-custom-recharge-section'\)\?\.hidden/);
    assert.match(script, /&& !customRechargeVisible/);
    assert.doesNotMatch(script, /const shouldShowAfdianQuery = activeProvider === 'afdian';/);
});
