bind 127.0.0.1
port 6379
protected-mode yes
daemonize no
dir /Users/wangyongchao/.zaoyoe-services/redis/data
dbfilename dump.rdb
save 60 1
appendonly yes
appendfsync everysec
pidfile /Users/wangyongchao/.zaoyoe-services/redis/redis.pid
