BEGIN;

CREATE TABLE IF NOT EXISTS public.homepage_site_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site VARCHAR(10) NOT NULL,
    name TEXT NOT NULL,
    description TEXT NULL,
    template_type TEXT NOT NULL DEFAULT 'custom',
    payload JSONB NOT NULL,
    source_release_id BIGINT NULL REFERENCES public.homepage_site_releases (id) ON DELETE SET NULL,
    created_by UUID NULL REFERENCES auth.users (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT homepage_site_templates_site_check CHECK (site IN ('cn', 'intl'))
);

CREATE INDEX IF NOT EXISTS idx_homepage_site_templates_site_updated_at
    ON public.homepage_site_templates (site, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.homepage_site_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site VARCHAR(10) NOT NULL,
    template_id BIGINT NULL REFERENCES public.homepage_site_templates (id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    note TEXT NULL,
    payload JSONB NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NULL,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_by UUID NULL REFERENCES auth.users (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT homepage_site_schedules_site_check CHECK (site IN ('cn', 'intl')),
    CONSTRAINT homepage_site_schedules_status_check CHECK (status IN ('scheduled', 'cancelled', 'completed'))
);

CREATE INDEX IF NOT EXISTS idx_homepage_site_schedules_site_window
    ON public.homepage_site_schedules (site, status, starts_at DESC);

CREATE INDEX IF NOT EXISTS idx_homepage_site_schedules_site_starts_at
    ON public.homepage_site_schedules (site, starts_at ASC);

COMMENT ON TABLE public.homepage_site_templates IS 'Reusable homepage orchestration templates per site for Homepage P1.';
COMMENT ON TABLE public.homepage_site_schedules IS 'Scheduled homepage release payloads per site for Homepage P1.';

CREATE OR REPLACE FUNCTION public.fn_get_homepage_config(
    p_site VARCHAR DEFAULT 'cn',
    p_include_hidden BOOLEAN DEFAULT false
)
RETURNS TABLE (
    section VARCHAR,
    content JSONB,
    is_visible BOOLEAN,
    display_order INT
)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    WITH normalized_site AS (
        SELECT CASE WHEN p_site = 'intl' THEN 'intl' ELSE 'cn' END AS site_key
    ),
    active_schedule AS (
        SELECT hs.payload
        FROM public.homepage_site_schedules hs
        JOIN normalized_site ns ON ns.site_key = hs.site
        WHERE hs.status = 'scheduled'
          AND hs.starts_at <= NOW()
          AND (hs.ends_at IS NULL OR hs.ends_at > NOW())
        ORDER BY hs.starts_at DESC, hs.id DESC
        LIMIT 1
    ),
    schedule_sections AS (
        SELECT
            key::VARCHAR AS section,
            value AS section_payload
        FROM active_schedule,
             LATERAL jsonb_each(COALESCE(payload -> 'sections', '{}'::jsonb))
    ),
    merged_rows AS (
        SELECT
            hc.section,
            COALESCE(ss.section_payload -> 'content', hc.content) AS content,
            COALESCE((ss.section_payload ->> 'is_visible')::BOOLEAN, hc.is_visible) AS is_visible,
            COALESCE((ss.section_payload ->> 'display_order')::INT, hc.display_order) AS display_order
        FROM public.homepage_config hc
        JOIN normalized_site ns ON ns.site_key = hc.site
        LEFT JOIN schedule_sections ss ON ss.section = hc.section
    )
    SELECT
        mr.section,
        mr.content,
        mr.is_visible,
        mr.display_order
    FROM merged_rows mr
    WHERE (p_include_hidden OR mr.is_visible = true)
    ORDER BY mr.display_order ASC, mr.section ASC;
$$;

COMMIT;
