BEGIN;

CREATE TABLE IF NOT EXISTS public.homepage_site_drafts (
    site VARCHAR(10) PRIMARY KEY,
    sections JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_by UUID NULL REFERENCES auth.users (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT homepage_site_drafts_site_check CHECK (site IN ('cn', 'intl'))
);

CREATE TABLE IF NOT EXISTS public.homepage_site_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site VARCHAR(10) NOT NULL,
    payload JSONB NOT NULL,
    source TEXT NOT NULL DEFAULT 'publish',
    note TEXT NULL,
    published_by UUID NULL REFERENCES auth.users (id) ON DELETE SET NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rollback_from_release_id BIGINT NULL REFERENCES public.homepage_site_releases (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT homepage_site_releases_site_check CHECK (site IN ('cn', 'intl'))
);

CREATE INDEX IF NOT EXISTS idx_homepage_site_releases_site_published_at
    ON public.homepage_site_releases (site, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_homepage_site_releases_rollback_from_release_id
    ON public.homepage_site_releases (rollback_from_release_id);

COMMENT ON TABLE public.homepage_site_drafts IS 'Homepage draft snapshots per site for Admin Studio P0 publish workflow.';
COMMENT ON TABLE public.homepage_site_releases IS 'Homepage published release snapshots per site for publish / rollback history.';

COMMIT;
