-- ============================================
-- 2026-03-19 Admin Secret Store
-- Secure server-side storage for admin-managed API keys
-- ============================================

CREATE TABLE IF NOT EXISTS public.admin_secret_store (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    secret_key TEXT UNIQUE NOT NULL,
    encrypted_value JSONB NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    description TEXT,
    updated_by UUID REFERENCES auth.users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_secret_store_secret_key
    ON public.admin_secret_store(secret_key);

ALTER TABLE public.admin_secret_store ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view admin secrets" ON public.admin_secret_store;
CREATE POLICY "Admins can view admin secrets"
    ON public.admin_secret_store FOR SELECT
    TO authenticated
    USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can manage admin secrets" ON public.admin_secret_store;
CREATE POLICY "Admins can manage admin secrets"
    ON public.admin_secret_store FOR ALL
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

COMMENT ON TABLE public.admin_secret_store IS 'Encrypted service-side secret storage for admin-managed keys';
COMMENT ON COLUMN public.admin_secret_store.secret_key IS 'Stable secret identifier such as gemini_api_key';
COMMENT ON COLUMN public.admin_secret_store.encrypted_value IS 'AES-GCM encrypted payload generated by the server runtime';
